# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    # Wait a week after a release before proposing it.
    cooldown:
      default-days: 7
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    # Wait a week after a release before proposing it.
    cooldown:
      default-days: 7
    commit-message:
      prefix: build
      prefix-development: build
      include: scope
    groups:
      bundler:
        patterns: ["*"]
