# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  # API resources, one class per resource and API version. Each loads the
  # first time it is used.
  module Resources
    module V1
      autoload :Actions, "#{__dir__}/resources/v1/actions"
      autoload :AlertNotes, "#{__dir__}/resources/v1/alert_notes"
      autoload :ApiKeys, "#{__dir__}/resources/v1/api_keys"
      autoload :CustomFieldOptions, "#{__dir__}/resources/v1/custom_field_options"
      autoload :CustomFields, "#{__dir__}/resources/v1/custom_fields"
      autoload :IncidentAttachments, "#{__dir__}/resources/v1/incident_attachments"
      autoload :IncidentMemberships, "#{__dir__}/resources/v1/incident_memberships"
      autoload :IncidentRelationships, "#{__dir__}/resources/v1/incident_relationships"
      autoload :IncidentRoles, "#{__dir__}/resources/v1/incident_roles"
      autoload :IncidentStatuses, "#{__dir__}/resources/v1/incident_statuses"
      autoload :IncidentTemplates, "#{__dir__}/resources/v1/incident_templates"
      autoload :IncidentTypes, "#{__dir__}/resources/v1/incident_types"
      autoload :Incidents, "#{__dir__}/resources/v1/incidents"
      autoload :IpAllowlists, "#{__dir__}/resources/v1/ip_allowlists"
      autoload :MaintenanceWindows, "#{__dir__}/resources/v1/maintenance_windows"
      autoload :PostmortemDocuments, "#{__dir__}/resources/v1/postmortem_documents"
      autoload :Severities, "#{__dir__}/resources/v1/severities"
      autoload :StatusPages, "#{__dir__}/resources/v1/status_pages"
      autoload :Utilities, "#{__dir__}/resources/v1/utilities"

      # Every v1 resource, e.g. `client.v1.actions`.
      class Namespace
        def initialize(client)
          @client = client
          @resources = {}
        end

        def inspect
          "#<#{self.class.name}>"
        end

        # @return [Actions]
        def actions
          @resources[:actions] ||= Actions.new(@client)
        end

        # @return [AlertNotes]
        def alert_notes
          @resources[:alert_notes] ||= AlertNotes.new(@client)
        end

        # @return [ApiKeys]
        def api_keys
          @resources[:api_keys] ||= ApiKeys.new(@client)
        end

        # @return [CustomFieldOptions]
        def custom_field_options
          @resources[:custom_field_options] ||= CustomFieldOptions.new(@client)
        end

        # @return [CustomFields]
        def custom_fields
          @resources[:custom_fields] ||= CustomFields.new(@client)
        end

        # @return [IncidentAttachments]
        def incident_attachments
          @resources[:incident_attachments] ||= IncidentAttachments.new(@client)
        end

        # @return [IncidentMemberships]
        def incident_memberships
          @resources[:incident_memberships] ||= IncidentMemberships.new(@client)
        end

        # @return [IncidentRelationships]
        def incident_relationships
          @resources[:incident_relationships] ||= IncidentRelationships.new(@client)
        end

        # @return [IncidentRoles]
        def incident_roles
          @resources[:incident_roles] ||= IncidentRoles.new(@client)
        end

        # @return [IncidentStatuses]
        def incident_statuses
          @resources[:incident_statuses] ||= IncidentStatuses.new(@client)
        end

        # @return [IncidentTemplates]
        def incident_templates
          @resources[:incident_templates] ||= IncidentTemplates.new(@client)
        end

        # @return [IncidentTypes]
        def incident_types
          @resources[:incident_types] ||= IncidentTypes.new(@client)
        end

        # @return [Incidents]
        def incidents
          @resources[:incidents] ||= Incidents.new(@client)
        end

        # @return [IpAllowlists]
        def ip_allowlists
          @resources[:ip_allowlists] ||= IpAllowlists.new(@client)
        end

        # @return [MaintenanceWindows]
        def maintenance_windows
          @resources[:maintenance_windows] ||= MaintenanceWindows.new(@client)
        end

        # @return [PostmortemDocuments]
        def postmortem_documents
          @resources[:postmortem_documents] ||= PostmortemDocuments.new(@client)
        end

        # @return [Severities]
        def severities
          @resources[:severities] ||= Severities.new(@client)
        end

        # @return [StatusPages]
        def status_pages
          @resources[:status_pages] ||= StatusPages.new(@client)
        end

        # @return [Utilities]
        def utilities
          @resources[:utilities] ||= Utilities.new(@client)
        end
      end
    end

    module V2
      autoload :Actions, "#{__dir__}/resources/v2/actions"
      autoload :AlertAttributes, "#{__dir__}/resources/v2/alert_attributes"
      autoload :AlertEvents, "#{__dir__}/resources/v2/alert_events"
      autoload :AlertRoutes, "#{__dir__}/resources/v2/alert_routes"
      autoload :AlertSources, "#{__dir__}/resources/v2/alert_sources"
      autoload :Alerts, "#{__dir__}/resources/v2/alerts"
      autoload :AnnouncementRules, "#{__dir__}/resources/v2/announcement_rules"
      autoload :AnnouncementTemplates, "#{__dir__}/resources/v2/announcement_templates"
      autoload :CallRoutes, "#{__dir__}/resources/v2/call_routes"
      autoload :CallSessions, "#{__dir__}/resources/v2/call_sessions"
      autoload :CallTranscriptEntries, "#{__dir__}/resources/v2/call_transcript_entries"
      autoload :Catalog, "#{__dir__}/resources/v2/catalog"
      autoload :CustomFields, "#{__dir__}/resources/v2/custom_fields"
      autoload :EscalationPathTemplates, "#{__dir__}/resources/v2/escalation_path_templates"
      autoload :Escalations, "#{__dir__}/resources/v2/escalations"
      autoload :FollowUps, "#{__dir__}/resources/v2/follow_ups"
      autoload :Heartbeat, "#{__dir__}/resources/v2/heartbeat"
      autoload :IncidentActivityLogEntries, "#{__dir__}/resources/v2/incident_activity_log_entries"
      autoload :IncidentParticipantWorkloads, "#{__dir__}/resources/v2/incident_participant_workloads"
      autoload :IncidentParticipants, "#{__dir__}/resources/v2/incident_participants"
      autoload :IncidentRoles, "#{__dir__}/resources/v2/incident_roles"
      autoload :IncidentTimelineItems, "#{__dir__}/resources/v2/incident_timeline_items"
      autoload :IncidentTimestamps, "#{__dir__}/resources/v2/incident_timestamps"
      autoload :IncidentUpdates, "#{__dir__}/resources/v2/incident_updates"
      autoload :Incidents, "#{__dir__}/resources/v2/incidents"
      autoload :PayConfigs, "#{__dir__}/resources/v2/pay_configs"
      autoload :PayReports, "#{__dir__}/resources/v2/pay_reports"
      autoload :Policies, "#{__dir__}/resources/v2/policies"
      autoload :PolicyFindings, "#{__dir__}/resources/v2/policy_findings"
      autoload :ScheduleSyncTargets, "#{__dir__}/resources/v2/schedule_sync_targets"
      autoload :Schedules, "#{__dir__}/resources/v2/schedules"
      autoload :Secrets, "#{__dir__}/resources/v2/secrets"
      autoload :StatusPages, "#{__dir__}/resources/v2/status_pages"
      autoload :Telemetry, "#{__dir__}/resources/v2/telemetry"
      autoload :Users, "#{__dir__}/resources/v2/users"
      autoload :WorkflowRuns, "#{__dir__}/resources/v2/workflow_runs"
      autoload :Workflows, "#{__dir__}/resources/v2/workflows"

      # Every v2 resource, e.g. `client.v2.actions`.
      class Namespace
        def initialize(client)
          @client = client
          @resources = {}
        end

        def inspect
          "#<#{self.class.name}>"
        end

        # @return [Actions]
        def actions
          @resources[:actions] ||= Actions.new(@client)
        end

        # @return [AlertAttributes]
        def alert_attributes
          @resources[:alert_attributes] ||= AlertAttributes.new(@client)
        end

        # @return [AlertEvents]
        def alert_events
          @resources[:alert_events] ||= AlertEvents.new(@client)
        end

        # @return [AlertRoutes]
        def alert_routes
          @resources[:alert_routes] ||= AlertRoutes.new(@client)
        end

        # @return [AlertSources]
        def alert_sources
          @resources[:alert_sources] ||= AlertSources.new(@client)
        end

        # @return [Alerts]
        def alerts
          @resources[:alerts] ||= Alerts.new(@client)
        end

        # @return [AnnouncementRules]
        def announcement_rules
          @resources[:announcement_rules] ||= AnnouncementRules.new(@client)
        end

        # @return [AnnouncementTemplates]
        def announcement_templates
          @resources[:announcement_templates] ||= AnnouncementTemplates.new(@client)
        end

        # @return [CallRoutes]
        def call_routes
          @resources[:call_routes] ||= CallRoutes.new(@client)
        end

        # @return [CallSessions]
        def call_sessions
          @resources[:call_sessions] ||= CallSessions.new(@client)
        end

        # @return [CallTranscriptEntries]
        def call_transcript_entries
          @resources[:call_transcript_entries] ||= CallTranscriptEntries.new(@client)
        end

        # @return [Catalog]
        def catalog
          @resources[:catalog] ||= Catalog.new(@client)
        end

        # @return [CustomFields]
        def custom_fields
          @resources[:custom_fields] ||= CustomFields.new(@client)
        end

        # @return [EscalationPathTemplates]
        def escalation_path_templates
          @resources[:escalation_path_templates] ||= EscalationPathTemplates.new(@client)
        end

        # @return [Escalations]
        def escalations
          @resources[:escalations] ||= Escalations.new(@client)
        end

        # @return [FollowUps]
        def follow_ups
          @resources[:follow_ups] ||= FollowUps.new(@client)
        end

        # @return [Heartbeat]
        def heartbeat
          @resources[:heartbeat] ||= Heartbeat.new(@client)
        end

        # @return [IncidentActivityLogEntries]
        def incident_activity_log_entries
          @resources[:incident_activity_log_entries] ||= IncidentActivityLogEntries.new(@client)
        end

        # @return [IncidentParticipantWorkloads]
        def incident_participant_workloads
          @resources[:incident_participant_workloads] ||= IncidentParticipantWorkloads.new(@client)
        end

        # @return [IncidentParticipants]
        def incident_participants
          @resources[:incident_participants] ||= IncidentParticipants.new(@client)
        end

        # @return [IncidentRoles]
        def incident_roles
          @resources[:incident_roles] ||= IncidentRoles.new(@client)
        end

        # @return [IncidentTimelineItems]
        def incident_timeline_items
          @resources[:incident_timeline_items] ||= IncidentTimelineItems.new(@client)
        end

        # @return [IncidentTimestamps]
        def incident_timestamps
          @resources[:incident_timestamps] ||= IncidentTimestamps.new(@client)
        end

        # @return [IncidentUpdates]
        def incident_updates
          @resources[:incident_updates] ||= IncidentUpdates.new(@client)
        end

        # @return [Incidents]
        def incidents
          @resources[:incidents] ||= Incidents.new(@client)
        end

        # @return [PayConfigs]
        def pay_configs
          @resources[:pay_configs] ||= PayConfigs.new(@client)
        end

        # @return [PayReports]
        def pay_reports
          @resources[:pay_reports] ||= PayReports.new(@client)
        end

        # @return [Policies]
        def policies
          @resources[:policies] ||= Policies.new(@client)
        end

        # @return [PolicyFindings]
        def policy_findings
          @resources[:policy_findings] ||= PolicyFindings.new(@client)
        end

        # @return [ScheduleSyncTargets]
        def schedule_sync_targets
          @resources[:schedule_sync_targets] ||= ScheduleSyncTargets.new(@client)
        end

        # @return [Schedules]
        def schedules
          @resources[:schedules] ||= Schedules.new(@client)
        end

        # @return [Secrets]
        def secrets
          @resources[:secrets] ||= Secrets.new(@client)
        end

        # @return [StatusPages]
        def status_pages
          @resources[:status_pages] ||= StatusPages.new(@client)
        end

        # @return [Telemetry]
        def telemetry
          @resources[:telemetry] ||= Telemetry.new(@client)
        end

        # @return [Users]
        def users
          @resources[:users] ||= Users.new(@client)
        end

        # @return [WorkflowRuns]
        def workflow_runs
          @resources[:workflow_runs] ||= WorkflowRuns.new(@client)
        end

        # @return [Workflows]
        def workflows
          @resources[:workflows] ||= Workflows.new(@client)
        end
      end
    end

    module V3
      autoload :Actions, "#{__dir__}/resources/v3/actions"
      autoload :AlertRoutes, "#{__dir__}/resources/v3/alert_routes"
      autoload :Catalog, "#{__dir__}/resources/v3/catalog"
      autoload :FollowUps, "#{__dir__}/resources/v3/follow_ups"
      autoload :Teams, "#{__dir__}/resources/v3/teams"

      # Every v3 resource, e.g. `client.v3.actions`.
      class Namespace
        def initialize(client)
          @client = client
          @resources = {}
        end

        def inspect
          "#<#{self.class.name}>"
        end

        # @return [Actions]
        def actions
          @resources[:actions] ||= Actions.new(@client)
        end

        # @return [AlertRoutes]
        def alert_routes
          @resources[:alert_routes] ||= AlertRoutes.new(@client)
        end

        # @return [Catalog]
        def catalog
          @resources[:catalog] ||= Catalog.new(@client)
        end

        # @return [FollowUps]
        def follow_ups
          @resources[:follow_ups] ||= FollowUps.new(@client)
        end

        # @return [Teams]
        def teams
          @resources[:teams] ||= Teams.new(@client)
        end
      end
    end

    # Resource accessors added to IncidentIo::Client. `client.<name>` is the
    # newest version of each resource; `client.v1.<name>` and so on reach a
    # specific version.
    module Accessors
      # @return [V1::Namespace]
      def v1
        resource_cache[:v1] ||= V1::Namespace.new(self)
      end

      # @return [V2::Namespace]
      def v2
        resource_cache[:v2] ||= V2::Namespace.new(self)
      end

      # @return [V3::Namespace]
      def v3
        resource_cache[:v3] ||= V3::Namespace.new(self)
      end

      # @return [V3::Actions]
      def actions
        resource_cache[:actions] ||= V3::Actions.new(self)
      end

      # @return [V2::AlertAttributes]
      def alert_attributes
        resource_cache[:alert_attributes] ||= V2::AlertAttributes.new(self)
      end

      # @return [V2::AlertEvents]
      def alert_events
        resource_cache[:alert_events] ||= V2::AlertEvents.new(self)
      end

      # @return [V1::AlertNotes]
      def alert_notes
        resource_cache[:alert_notes] ||= V1::AlertNotes.new(self)
      end

      # @return [V3::AlertRoutes]
      def alert_routes
        resource_cache[:alert_routes] ||= V3::AlertRoutes.new(self)
      end

      # @return [V2::AlertSources]
      def alert_sources
        resource_cache[:alert_sources] ||= V2::AlertSources.new(self)
      end

      # @return [V2::Alerts]
      def alerts
        resource_cache[:alerts] ||= V2::Alerts.new(self)
      end

      # @return [V2::AnnouncementRules]
      def announcement_rules
        resource_cache[:announcement_rules] ||= V2::AnnouncementRules.new(self)
      end

      # @return [V2::AnnouncementTemplates]
      def announcement_templates
        resource_cache[:announcement_templates] ||= V2::AnnouncementTemplates.new(self)
      end

      # @return [V1::ApiKeys]
      def api_keys
        resource_cache[:api_keys] ||= V1::ApiKeys.new(self)
      end

      # @return [V2::CallRoutes]
      def call_routes
        resource_cache[:call_routes] ||= V2::CallRoutes.new(self)
      end

      # @return [V2::CallSessions]
      def call_sessions
        resource_cache[:call_sessions] ||= V2::CallSessions.new(self)
      end

      # @return [V2::CallTranscriptEntries]
      def call_transcript_entries
        resource_cache[:call_transcript_entries] ||= V2::CallTranscriptEntries.new(self)
      end

      # @return [V3::Catalog]
      def catalog
        resource_cache[:catalog] ||= V3::Catalog.new(self)
      end

      # @return [V1::CustomFieldOptions]
      def custom_field_options
        resource_cache[:custom_field_options] ||= V1::CustomFieldOptions.new(self)
      end

      # @return [V2::CustomFields]
      def custom_fields
        resource_cache[:custom_fields] ||= V2::CustomFields.new(self)
      end

      # @return [V2::EscalationPathTemplates]
      def escalation_path_templates
        resource_cache[:escalation_path_templates] ||= V2::EscalationPathTemplates.new(self)
      end

      # @return [V2::Escalations]
      def escalations
        resource_cache[:escalations] ||= V2::Escalations.new(self)
      end

      # @return [V3::FollowUps]
      def follow_ups
        resource_cache[:follow_ups] ||= V3::FollowUps.new(self)
      end

      # @return [V2::Heartbeat]
      def heartbeat
        resource_cache[:heartbeat] ||= V2::Heartbeat.new(self)
      end

      # @return [V2::IncidentActivityLogEntries]
      def incident_activity_log_entries
        resource_cache[:incident_activity_log_entries] ||= V2::IncidentActivityLogEntries.new(self)
      end

      # @return [V1::IncidentAttachments]
      def incident_attachments
        resource_cache[:incident_attachments] ||= V1::IncidentAttachments.new(self)
      end

      # @return [V1::IncidentMemberships]
      def incident_memberships
        resource_cache[:incident_memberships] ||= V1::IncidentMemberships.new(self)
      end

      # @return [V2::IncidentParticipantWorkloads]
      def incident_participant_workloads
        resource_cache[:incident_participant_workloads] ||= V2::IncidentParticipantWorkloads.new(self)
      end

      # @return [V2::IncidentParticipants]
      def incident_participants
        resource_cache[:incident_participants] ||= V2::IncidentParticipants.new(self)
      end

      # @return [V1::IncidentRelationships]
      def incident_relationships
        resource_cache[:incident_relationships] ||= V1::IncidentRelationships.new(self)
      end

      # @return [V2::IncidentRoles]
      def incident_roles
        resource_cache[:incident_roles] ||= V2::IncidentRoles.new(self)
      end

      # @return [V1::IncidentStatuses]
      def incident_statuses
        resource_cache[:incident_statuses] ||= V1::IncidentStatuses.new(self)
      end

      # @return [V1::IncidentTemplates]
      def incident_templates
        resource_cache[:incident_templates] ||= V1::IncidentTemplates.new(self)
      end

      # @return [V2::IncidentTimelineItems]
      def incident_timeline_items
        resource_cache[:incident_timeline_items] ||= V2::IncidentTimelineItems.new(self)
      end

      # @return [V2::IncidentTimestamps]
      def incident_timestamps
        resource_cache[:incident_timestamps] ||= V2::IncidentTimestamps.new(self)
      end

      # @return [V1::IncidentTypes]
      def incident_types
        resource_cache[:incident_types] ||= V1::IncidentTypes.new(self)
      end

      # @return [V2::IncidentUpdates]
      def incident_updates
        resource_cache[:incident_updates] ||= V2::IncidentUpdates.new(self)
      end

      # @return [V2::Incidents]
      def incidents
        resource_cache[:incidents] ||= V2::Incidents.new(self)
      end

      # @return [V1::IpAllowlists]
      def ip_allowlists
        resource_cache[:ip_allowlists] ||= V1::IpAllowlists.new(self)
      end

      # @return [V1::MaintenanceWindows]
      def maintenance_windows
        resource_cache[:maintenance_windows] ||= V1::MaintenanceWindows.new(self)
      end

      # @return [V2::PayConfigs]
      def pay_configs
        resource_cache[:pay_configs] ||= V2::PayConfigs.new(self)
      end

      # @return [V2::PayReports]
      def pay_reports
        resource_cache[:pay_reports] ||= V2::PayReports.new(self)
      end

      # @return [V2::Policies]
      def policies
        resource_cache[:policies] ||= V2::Policies.new(self)
      end

      # @return [V2::PolicyFindings]
      def policy_findings
        resource_cache[:policy_findings] ||= V2::PolicyFindings.new(self)
      end

      # @return [V1::PostmortemDocuments]
      def postmortem_documents
        resource_cache[:postmortem_documents] ||= V1::PostmortemDocuments.new(self)
      end

      # @return [V2::ScheduleSyncTargets]
      def schedule_sync_targets
        resource_cache[:schedule_sync_targets] ||= V2::ScheduleSyncTargets.new(self)
      end

      # @return [V2::Schedules]
      def schedules
        resource_cache[:schedules] ||= V2::Schedules.new(self)
      end

      # @return [V2::Secrets]
      def secrets
        resource_cache[:secrets] ||= V2::Secrets.new(self)
      end

      # @return [V1::Severities]
      def severities
        resource_cache[:severities] ||= V1::Severities.new(self)
      end

      # @return [V2::StatusPages]
      def status_pages
        resource_cache[:status_pages] ||= V2::StatusPages.new(self)
      end

      # @return [V3::Teams]
      def teams
        resource_cache[:teams] ||= V3::Teams.new(self)
      end

      # @return [V2::Telemetry]
      def telemetry
        resource_cache[:telemetry] ||= V2::Telemetry.new(self)
      end

      # @return [V2::Users]
      def users
        resource_cache[:users] ||= V2::Users.new(self)
      end

      # @return [V1::Utilities]
      def utilities
        resource_cache[:utilities] ||= V1::Utilities.new(self)
      end

      # @return [V2::WorkflowRuns]
      def workflow_runs
        resource_cache[:workflow_runs] ||= V2::WorkflowRuns.new(self)
      end

      # @return [V2::Workflows]
      def workflows
        resource_cache[:workflows] ||= V2::Workflows.new(self)
      end

      private

      def resource_cache
        @resource_cache ||= {}
      end
    end
  end
end
