# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V1
      # Manage custom field options.
      #
      # Single- and multi-select custom fields have a list of all available options,
      # which have a value, and a sort key. The value must be unique to the custom
      # field. For example, you might have an Incident Type custom field, with options
      # "Data breach", "Performance degradation", "API downtime", etc.
      class CustomFieldOptions < Resource
        # Create a custom field option
        #
        # Create a custom field option. If the sort key is not supplied, it'll default to 1000, so the option appears near the end of the list.
        #
        # Endpoint: `POST /v1/custom_field_options`. Scopes: organisation_settings.update.
        #
        # @param custom_field_id [String] ID of the custom field this option belongs to.
        # @param value [String] Human readable name for the custom field option. Values must not start or end with whitespace, or contain tabs or newlines.
        # @param sort_key [Integer] Sort key used to order the custom field options correctly.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CustomFieldOptionV1]
        def create(custom_field_id:, value:, sort_key: NOT_GIVEN, request_options: {})
          request(
            :post,
            "/v1/custom_field_options",
            body: given({custom_field_id:, sort_key:, value:}),
            unwrap: "custom_field_option",
            model: Models::CustomFieldOptionV1,
            request_options:
          )
        end

        # Delete a custom field option
        #
        # Endpoint: `DELETE /v1/custom_field_options/{id}`. Scopes: organisation_settings.update.
        #
        # @param id [String] Unique identifier for the custom field option.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def delete(id, request_options: {})
          request(
            :delete,
            path("/v1/custom_field_options/%s", id),
            request_options:
          )
        end

        # Show custom field options for a custom field
        #
        # Endpoint: `GET /v1/custom_field_options`. Scopes: custom_fields.view.
        #
        # @param custom_field_id [String] The custom field to list options for.
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] A custom field option's ID. This endpoint will return a list of custom field options created after this option.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::CustomFieldOptionV1>]
        def list(custom_field_id:, page_size: nil, after: nil, request_options: {})
          paginate(
            "/v1/custom_field_options",
            items_key: "custom_field_options",
            query: {page_size:, after:, custom_field_id:},
            model: Models::CustomFieldOptionV1,
            request_options:
          )
        end

        # Get a single custom field option
        #
        # Endpoint: `GET /v1/custom_field_options/{id}`. Scopes: custom_fields.view.
        #
        # @param id [String] Unique identifier for the custom field option.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CustomFieldOptionV1]
        def show(id, request_options: {})
          request(
            :get,
            path("/v1/custom_field_options/%s", id),
            unwrap: "custom_field_option",
            model: Models::CustomFieldOptionV1,
            request_options:
          )
        end

        # Update a custom field option
        #
        # Endpoint: `PUT /v1/custom_field_options/{id}`. Scopes: organisation_settings.update.
        #
        # @param id [String] Unique identifier for the custom field option.
        # @param sort_key [Integer] Sort key used to order the custom field options correctly.
        # @param value [String] Human readable name for the custom field option. Values must not start or end with whitespace, or contain tabs or newlines.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CustomFieldOptionV1]
        def update(id, sort_key:, value:, request_options: {})
          request(
            :put,
            path("/v1/custom_field_options/%s", id),
            body: given({sort_key:, value:}),
            unwrap: "custom_field_option",
            model: Models::CustomFieldOptionV1,
            request_options:
          )
        end
      end
    end
  end
end
