# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V1
      # Create and read incidents.
      #
      # Incidents are a core resource, on which many other resources (actions, etc) are created.
      #
      # Care should be taken around these endpoints, as automation that creates duplicate
      # incidents can be distracting, and impact reporting.
      #
      # The maximum page size that can be requested is 250.
      class Incidents < Resource
        # Create a new incident.
        #
        # Endpoint: `POST /v1/incidents`. Scopes: incidents.create.
        #
        # @deprecated Use `client.incidents.create` instead.
        # @param visibility [String] Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [docs](https://docs.incident.io/incidents/sensitive-incidents). One of: public, private.
        # @param custom_field_entries [Array<Models::CustomFieldEntryPayloadV1, Hash>] Set the incident's custom fields to these values.
        # @param idempotency_key [String] Unique string used to de-duplicate incident create requests. Generated when not given.
        # @param incident_role_assignments [Array<Models::IncidentRoleAssignmentPayloadV1, Hash>] Assign incident roles to these people.
        # @param incident_type_id [String] Incident type to create this incident as.
        # @param mode [String] Whether the incident is real or test One of: real, test.
        # @param name [String] Explanation of the incident.
        # @param severity_id [String] Severity to create incident as.
        # @param slack_team_id [String] ID of the Slack team / workspace. This is only required if you are using a Slack Enterprise Grid with multiple teams.
        # @param source_message_channel_id [String] Channel ID of the source message, if this incident was created from one.
        # @param source_message_timestamp [String] Timestamp of the source message, if this incident was created from one.
        # @param status [String] Current status of the incident One of: triage, investigating, fixing, monitoring, closed, declined.
        # @param summary [String] Detailed description of the incident.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentV1]
        def create(
          visibility:,
          custom_field_entries: nil,
          idempotency_key: SecureRandom.uuid,
          incident_role_assignments: nil,
          incident_type_id: nil,
          mode: nil,
          name: nil,
          severity_id: nil,
          slack_team_id: nil,
          source_message_channel_id: nil,
          source_message_timestamp: nil,
          status: nil,
          summary: nil,
          request_options: {}
        )
          deprecated!("client.v1.incidents.create", "client.incidents.create")
          request(
            :post,
            "/v1/incidents",
            body: {
              custom_field_entries:,
              idempotency_key:,
              incident_role_assignments:,
              incident_type_id:,
              mode:,
              name:,
              severity_id:,
              slack_team_id:,
              source_message_channel_id:,
              source_message_timestamp:,
              status:,
              summary:,
              visibility:
            }.compact,
            idempotent: true,
            unwrap: "incident",
            model: Models::IncidentV1,
            request_options:
          )
        end

        # List all incidents for an organisation.
        #
        # Endpoint: `GET /v1/incidents`. Scopes: incidents.view.
        #
        # @deprecated Use `client.incidents.list` instead.
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.
        # @param status [Array<String>] Filter for incidents in these statuses.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::IncidentV1>]
        def list(page_size: nil, after: nil, status: nil, request_options: {})
          deprecated!("client.v1.incidents.list", "client.incidents.list")
          paginate(
            "/v1/incidents",
            items_key: "incidents",
            query: {page_size:, after:, status:},
            model: Models::IncidentV1,
            request_options:
          )
        end

        # Get a single incident.
        #
        # Endpoint: `GET /v1/incidents/{id}`. Scopes: incidents.view.
        #
        # @deprecated Use `client.incidents.show` instead.
        # @param id [String] Unique identifier for the incident.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentV1]
        def show(id, request_options: {})
          deprecated!("client.v1.incidents.show", "client.incidents.show")
          request(
            :get,
            path("/v1/incidents/%s", id),
            unwrap: "incident",
            model: Models::IncidentV1,
            request_options:
          )
        end
      end
    end
  end
end
