# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V1
      # Create, list and delete incident attachments.
      #
      # Incident Attachments allows you to connect resources from external systems into incidents.
      # Examples include: PagerDuty incidents and GitHub pull requests.
      class IncidentAttachments < Resource
        # Attaches an external resource to an incident.
        #
        # You must provide a resource with resource_type and either external_id or url, but not both.
        #
        # When providing a url, the server will create the attachment from that link for the given resource type if the integration is installed and the link is valid.
        #
        # To attach an arbitrary link that isn't backed by an integration, use the arbitrary_url resource type with a url, and optionally a title and emoji.
        #
        # Endpoint: `POST /v1/incident_attachments`. Scopes: attachments.create.
        #
        # @param incident_id [String] ID of the incident to add an attachment to.
        # @param resource [Hash]
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentAttachmentV1]
        def create(incident_id:, resource:, request_options: {})
          request(
            :post,
            "/v1/incident_attachments",
            body: given({incident_id:, resource:}),
            unwrap: "incident_attachment",
            model: Models::IncidentAttachmentV1,
            request_options:
          )
        end

        # Unattaches an external resource from an incident
        #
        # Endpoint: `DELETE /v1/incident_attachments/{id}`. Scopes: attachments.destroy.
        #
        # @param id [String] Unique identifier of this incident membership.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def delete(id, request_options: {})
          request(
            :delete,
            path("/v1/incident_attachments/%s", id),
            request_options:
          )
        end

        # List all incident attachments for a given external resource or incident. You must provide either a specific incident ID or a specific external resource type and external ID.
        #
        # Endpoint: `GET /v1/incident_attachments`. Scopes: attachments.view.
        #
        # @param incident_id [String] Incident that this attachment is against.
        # @param external_id [String] ID of the resource in the external system.
        # @param resource_type [String] E.g. PagerDuty: the external system that holds the resource One of: pager_duty_incident, opsgenie_alert, datadog_monitor_alert, github_pull_request, gitlab_merge_request, sentry_issue, jira_issue, jsm_alert, atlassian_statuspage_incident, zendesk_ticket, google_calendar_event, outlook_calendar_event, slack_file, salesforce_case, arbitrary_url, scrubbed, statuspage_incident.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Array<Models::IncidentAttachmentV1>]
        def list(incident_id: nil, external_id: nil, resource_type: nil, request_options: {})
          request(
            :get,
            "/v1/incident_attachments",
            query: {incident_id:, external_id:, resource_type:},
            unwrap: "incident_attachments",
            model: [Models::IncidentAttachmentV1],
            request_options:
          )
        end
      end
    end
  end
end
