# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V1
      # Manage incident templates: reusable sets of values applied to incidents created from alerts.
      class IncidentTemplates < Resource
        # Create an incident template.
        #
        # Endpoint: `POST /v1/incident_templates`. Scopes: incident_template.create.
        #
        # @param name [String] The name of this incident template, for the user's reference.
        # @param template [Models::IncidentTemplateConfigPayloadV1, Hash]
        # @param expressions [Array<Models::ExpressionPayloadV3, Hash>] The expressions used by bindings in this template.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentTemplateV1]
        def create(name:, template:, expressions: NOT_GIVEN, request_options: {})
          request(
            :post,
            "/v1/incident_templates",
            body: given({expressions:, name:, template:}),
            unwrap: "incident_template",
            model: Models::IncidentTemplateV1,
            request_options:
          )
        end

        # Archive an incident template. Fails if the template is still referenced by an alert route.
        #
        # Endpoint: `DELETE /v1/incident_templates/{id}`. Scopes: incident_template.destroy.
        #
        # @param id [String] The incident template's ID.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def destroy(id, request_options: {})
          request(
            :delete,
            path("/v1/incident_templates/%s", id),
            request_options:
          )
        end

        # List all incident templates for this organisation.
        #
        # Endpoint: `GET /v1/incident_templates`. Scopes: incident_templates.view.
        #
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] An incident template's ID. This endpoint returns a list of templates after this ID in relation to the API response order.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::IncidentTemplateV1>]
        def list(page_size: nil, after: nil, request_options: {})
          paginate(
            "/v1/incident_templates",
            items_key: "incident_templates",
            query: {page_size:, after:},
            model: Models::IncidentTemplateV1,
            request_options:
          )
        end

        # Show a single incident template.
        #
        # Endpoint: `GET /v1/incident_templates/{id}`. Scopes: incident_templates.view.
        #
        # @param id [String] The incident template's ID.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentTemplateV1]
        def show(id, request_options: {})
          request(
            :get,
            path("/v1/incident_templates/%s", id),
            unwrap: "incident_template",
            model: Models::IncidentTemplateV1,
            request_options:
          )
        end

        # Update an incident template. This is a full replacement: any field not supplied is cleared.
        #
        # Endpoint: `PUT /v1/incident_templates/{id}`. Scopes: incident_template.update.
        #
        # @param id [String] The incident template's ID.
        # @param name [String] The name of this incident template, for the user's reference.
        # @param template [Models::IncidentTemplateConfigPayloadV1, Hash]
        # @param expressions [Array<Models::ExpressionPayloadV3, Hash>] The expressions used by bindings in this template.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentTemplateV1]
        def update(id, name:, template:, expressions: NOT_GIVEN, request_options: {})
          request(
            :put,
            path("/v1/incident_templates/%s", id),
            body: given({expressions:, name:, template:}),
            unwrap: "incident_template",
            model: Models::IncidentTemplateV1,
            request_options:
          )
        end

        # Check whether an incident template's config is valid, without creating or updating anything.
        #
        # This validates in the same way a create or update would: expressions are compiled and checked
        # against your catalog. An invalid config is an error. A config that is valid but probably not
        # what you meant — such as a name that's already taken — comes back as a warning on a successful
        # response, so a client can show it without blocking.
        #
        # Endpoint: `POST /v1/incident_templates/actions/validate`. Scopes: incident_templates.view.
        #
        # @param name [String] The name of this incident template, for the user's reference.
        # @param template [Models::IncidentTemplateConfigPayloadV1, Hash]
        # @param expressions [Array<Models::ExpressionPayloadV3, Hash>] The expressions used by bindings in this template.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Array<Models::IncidentTemplateValidateWarningV1>]
        def validate(name:, template:, expressions: NOT_GIVEN, request_options: {})
          request(
            :post,
            "/v1/incident_templates/actions/validate",
            body: given({expressions:, name:, template:}),
            unwrap: "warnings",
            model: [Models::IncidentTemplateValidateWarningV1],
            request_options:
          )
        end
      end
    end
  end
end
