# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V1
      # Manage team access to private incidents
      class IncidentTeamMemberships < Resource
        # Grants a team access to a private incident
        #
        # Endpoint: `POST /v1/incident_team_memberships`. Scopes: incident_team_memberships.grant.
        #
        # @param incident_id [String]
        # @param team_id [String]
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentTeamMembershipV1]
        def create(incident_id:, team_id:, request_options: {})
          request(
            :post,
            "/v1/incident_team_memberships",
            body: given({incident_id:, team_id:}),
            unwrap: "incident_team_membership",
            model: Models::IncidentTeamMembershipV1,
            request_options:
          )
        end

        # Revoke a team's access to a private incident
        #
        # Revoke a team's access to a private incident. Members who only had access through this team lose it too; directly-added members and members still covered by another team keep theirs.
        #
        # Endpoint: `POST /v1/incident_team_memberships/actions/revoke`. Scopes: incident_team_memberships.revoke.
        #
        # @param incident_id [String] Revoke team access to this incident.
        # @param team_id [String]
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def revoke(incident_id:, team_id:, request_options: {})
          request(
            :post,
            "/v1/incident_team_memberships/actions/revoke",
            body: given({incident_id:, team_id:}),
            request_options:
          )
        end
      end
    end
  end
end
