# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V1
      # Manage post-mortem documents.
      #
      # Post-mortem documents capture the learnings from an incident, and are associated with a specific
      # incident. Use this API to list and retrieve post-mortem documents, update their status, and fetch
      # the full document's content.
      class PostmortemDocuments < Resource
        # Link an externally-hosted post-mortem document to an incident.
        #
        # Use this to attach a retrospective document you've created in your own provider (for example
        # Confluence, Notion, or Google Docs) to an existing incident. This is the API equivalent of
        # pasting a document link into the incident.io dashboard, and is useful for automating your
        # retrospective workflow - for example, creating a document in the right space with the right
        # permissions when an incident is opened, then linking it back to the incident.
        #
        # Only one external post-mortem can be attached to an incident, and you cannot attach an external
        # document to an incident that already has an in-app post-mortem. Re-attaching the same incident
        # with a new permalink updates the existing link.
        #
        # Endpoint: `POST /v1/postmortem_documents/actions/attach`. Scopes: external_postmortems.create.
        #
        # @param incident_id [String] The unique identifier of the incident to attach the post-mortem document to.
        # @param permalink [String] A URL pointing to the externally-hosted post-mortem document.
        # @param document_provider [String] The provider hosting the document. Set this when it can't be inferred from the permalink so the link renders correctly. One of: , confluence, google_docs, notion, sharepoint, incident_io, copy_paste_basecamp, copy_paste_confluence, copy_paste_github_wiki, copy_paste_google_docs, copy_paste_notion, copy_paste_quip.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::PostmortemDocumentV1]
        def attach(incident_id:, permalink:, document_provider: nil, request_options: {})
          request(
            :post,
            "/v1/postmortem_documents/actions/attach",
            body: {document_provider:, incident_id:, permalink:}.compact,
            unwrap: "postmortem_document",
            model: Models::PostmortemDocumentV1,
            request_options:
          )
        end

        # List post-mortem documents for the organisation.
        #
        # Results can be filtered by incident and sorted by creation date. This endpoint returns document
        # metadata only. If you want to fetch the content of the post-mortem, use the ShowContent endpoint.
        #
        # Endpoint: `GET /v1/postmortem_documents`. Scopes: incidents.view.
        #
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] A post-mortem document's ID. This endpoint will return a list of post-mortem documents after this ID.
        # @param incident_id [String] Filter to only return post-mortem documents for the given incident.
        # @param sort_by [String] Controls the order that results are returned in One of: created_at_newest_first, created_at_oldest_first.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::PostmortemDocumentV1>]
        def list(page_size: nil, after: nil, incident_id: nil, sort_by: nil, request_options: {})
          paginate(
            "/v1/postmortem_documents",
            items_key: "postmortem_documents",
            query: {page_size:, after:, incident_id:, sort_by:},
            model: Models::PostmortemDocumentV1,
            request_options:
          )
        end

        # Get a single post-mortem document by ID.
        #
        # This returns the document's metadata. To retrieve the content of the post-mortem, use the ShowContent endpoint.
        #
        # Endpoint: `GET /v1/postmortem_documents/{id}`. Scopes: incidents.view.
        #
        # @param id [String] Unique identifier for the post-mortem document.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::PostmortemDocumentV1]
        def show(id, request_options: {})
          request(
            :get,
            path("/v1/postmortem_documents/%s", id),
            unwrap: "postmortem_document",
            model: Models::PostmortemDocumentV1,
            request_options:
          )
        end

        # Fetch the content of a post-mortem document, rendered as markdown.
        #
        # The response contains the full document content as a single markdown string. The markdown
        # follows standard formatting and is structured to mirror the post-mortem as it appears in
        # the incident.io dashboard:
        #
        # - **Headings** (`#`, `##`, `###`) for document title and sections
        # - **Bold** and *italic* text formatting
        # - Bullet lists and numbered lists
        # - [Links](url) to external resources, Slack threads, and pull requests
        # - Mentions of users, incidents, and catalog entries resolved to their display names
        # - Custom field values rendered as labelled bullet lists
        # - Timeline entries grouped by date with timestamps
        # - Follow-ups with assignees and descriptions
        #
        # To preview what this markdown will look like for a given post-mortem, open the document
        # in the incident.io dashboard and use the "Copy to clipboard" button. The copied content
        # uses the same rendering pipeline as this endpoint.
        #
        # If you only need document metadata, use the Show or List endpoints instead.
        #
        # Endpoint: `GET /v1/postmortem_documents/{id}/content`. Scopes: in_app_postmortems.copy_as_markdown.
        #
        # @param id [String] Unique identifier for the post-mortem document.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [String]
        def show_content(id, request_options: {})
          request(
            :get,
            path("/v1/postmortem_documents/%s/content", id),
            unwrap: "markdown",
            request_options:
          )
        end

        # Update the status of a post-mortem document.
        #
        # Endpoint: `PUT /v1/postmortem_documents/{id}`. Scopes: in_app_postmortems.update_status.
        #
        # @param id [String] Unique identifier for the post-mortem document.
        # @param status [String] The new status to set the post-mortem document to One of: in_progress, in_review, completed.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::PostmortemDocumentV1]
        def update_status(id, status:, request_options: {})
          request(
            :put,
            path("/v1/postmortem_documents/%s", id),
            body: {status:}.compact,
            unwrap: "postmortem_document",
            model: Models::PostmortemDocumentV1,
            request_options:
          )
        end
      end
    end
  end
end
