# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ActivityRoleUpdateV2 = Model.define(
      new_assignee: -> { UserV2 },
      previous_assignee: -> { UserV2 },
      role: -> { IncidentRoleV2 },
      updater: -> { ActorV2 }
    )

    class ActivityRoleUpdateV2
      # @!attribute [r] new_assignee
      #   The new_assignee field
      #   @return [UserV2, nil]
      # @!attribute [r] previous_assignee
      #   The previous_assignee field
      #   @return [UserV2, nil]
      # @!attribute [r] role
      #   The role field
      #   @return [IncidentRoleV2, nil]
      # @!attribute [r] updater
      #   The updater field
      #   @return [ActorV2, nil]
    end
  end
end
