# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ActionV2 = Model.define(
      assignee: -> { UserV2 },
      completed_at: :time,
      created_at: :time,
      creator: -> { ActorV2 },
      description: :string,
      id: :string,
      incident_id: :string,
      status: :string,
      updated_at: :time
    )

    class ActionV2
      # @!attribute [r] assignee
      #   The assignee field
      #   @return [UserV2, nil]
      # @!attribute [r] completed_at
      #   When the action was completed
      #   @return [Time, nil]
      # @!attribute [r] created_at
      #   When the action was created
      #   @return [Time, nil]
      # @!attribute [r] creator
      #   The creator field
      #   @return [ActorV2, nil]
      # @!attribute [r] description
      #   Description of the action
      #   @return [String, nil]
      # @!attribute [r] id
      #   Unique identifier for the action
      #   @return [String, nil]
      # @!attribute [r] incident_id
      #   Unique identifier of the incident the action belongs to
      #   @return [String, nil]
      # @!attribute [r] status
      #   Status of the action One of: outstanding, completed, deleted, not_doing
      #   @return [String, nil]
      # @!attribute [r] updated_at
      #   When the action was last updated
      #   @return [Time, nil]
    end
  end
end
