# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] incident_update_id
    #   @return [String, nil] The incident update that carried the merge.
    # @!attribute [r] merger
    #   @return [ActorV2, nil]
    # @!attribute [r] source_incident
    #   @return [IncidentSlimV2, nil]
    ActivityIncidentMergedV2 = Model.define(
      incident_update_id: :string,
      merger: -> { ActorV2 },
      source_incident: -> { IncidentSlimV2 }
    )
  end
end
