# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ActivityFollowUpUpdatedV2 = Model.define(
      follow_up_id: :string,
      new_assignee: -> { UserV2 },
      new_status: :string,
      new_title: :string,
      previous_assignee: -> { UserV2 },
      previous_status: :string,
      previous_title: :string,
      updater: -> { ActorV2 }
    )

    class ActivityFollowUpUpdatedV2
      # @!attribute [r] follow_up_id
      #   The follow-up that changed
      #   @return [String, nil]
      # @!attribute [r] new_assignee
      #   The new_assignee field
      #   @return [UserV2, nil]
      # @!attribute [r] new_status
      #   Status after, when the status changed One of: outstanding, completed,…
      #   @return [String, nil]
      # @!attribute [r] new_title
      #   Title after, when the title changed
      #   @return [String, nil]
      # @!attribute [r] previous_assignee
      #   The previous_assignee field
      #   @return [UserV2, nil]
      # @!attribute [r] previous_status
      #   Status before, when the status changed One of: outstanding, completed,…
      #   @return [String, nil]
      # @!attribute [r] previous_title
      #   Title before, when the title changed
      #   @return [String, nil]
      # @!attribute [r] updater
      #   The updater field
      #   @return [ActorV2, nil]
    end
  end
end
