# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] incident_timestamp
    #   @return [IncidentTimestampV2, nil]
    # @!attribute [r] new_value
    #   @return [Time, nil] What it was set to
    # @!attribute [r] previous_value
    #   @return [Time, nil] What it was before.
    # @!attribute [r] updater
    #   @return [ActorV2, nil]
    ActivityIncidentTimestampSetV2 = Model.define(
      incident_timestamp: -> { IncidentTimestampV2 },
      new_value: :time,
      previous_value: :time,
      updater: -> { ActorV2 }
    )
  end
end
