# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] new_visibility
    #   @return [String, nil] Visibility after the change One of: public, private.
    # @!attribute [r] previous_visibility
    #   @return [String, nil] Visibility before the change One of: public, private.
    # @!attribute [r] updater
    #   @return [ActorV2, nil]
    ActivityIncidentVisibilityChangedV2 = Model.define(
      new_visibility: :string,
      previous_visibility: :string,
      updater: -> { ActorV2 }
    )
  end
end
