# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] action_id
    #   @return [String, nil] The action.
    # @!attribute [r] actor
    #   @return [ActorV2, nil]
    ActivityActionRefV2 = Model.define(
      action_id: :string,
      actor: -> { ActorV2 }
    )
  end
end
