# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] assignee
    #   @return [UserV2, nil]
    # @!attribute [r] completed_at
    #   @return [Time, nil] When the action was completed
    # @!attribute [r] created_at
    #   @return [Time, nil] When the action was created
    # @!attribute [r] creator
    #   @return [ActorV2, nil]
    # @!attribute [r] description
    #   @return [String, nil] Description of the action
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier for the action
    # @!attribute [r] incident_id
    #   @return [String, nil] Unique identifier of the incident the action belongs to
    # @!attribute [r] status
    #   @return [String, nil] Status of the action One of: outstanding, completed, deleted, not_doing.
    # @!attribute [r] updated_at
    #   @return [Time, nil] When the action was last updated
    ActionV3 = Model.define(
      assignee: -> { UserV2 },
      completed_at: :time,
      created_at: :time,
      creator: -> { ActorV2 },
      description: :string,
      id: :string,
      incident_id: :string,
      status: :string,
      updated_at: :time
    )
  end
end
