# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] id
    #   @return [String, nil] ID of the incident update
    # @!attribute [r] message
    #   @return [String, nil] The update the responder wrote, in markdown
    # @!attribute [r] new_severity
    #   @return [SeverityV2, nil]
    # @!attribute [r] new_status
    #   @return [IncidentStatusV2, nil]
    # @!attribute [r] next_update_in_minutes
    #   @return [Integer, nil] When the responder said the next update would come
    # @!attribute [r] previous_severity
    #   @return [SeverityV2, nil]
    # @!attribute [r] previous_status
    #   @return [IncidentStatusV2, nil]
    # @!attribute [r] updater
    #   @return [ActorV2, nil]
    ActivityIncidentUpdateV2 = Model.define(
      id: :string,
      message: :string,
      new_severity: -> { SeverityV2 },
      new_status: -> { IncidentStatusV2 },
      next_update_in_minutes: :integer,
      previous_severity: -> { SeverityV2 },
      previous_status: -> { IncidentStatusV2 },
      updater: -> { ActorV2 }
    )
  end
end
