# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ActivityFollowUpRefV2 = Model.define(
      actor: -> { ActorV2 },
      follow_up_id: :string
    )

    class ActivityFollowUpRefV2
      # @!attribute [r] actor
      #   The actor field
      #   @return [ActorV2, nil]
      # @!attribute [r] follow_up_id
      #   The follow-up
      #   @return [String, nil]
    end
  end
end
