# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] new_incident_type
    #   @return [IncidentTypeV2, nil]
    # @!attribute [r] previous_incident_type
    #   @return [IncidentTypeV2, nil]
    # @!attribute [r] updater
    #   @return [ActorV2, nil]
    ActivityIncidentTypeChangedV2 = Model.define(
      new_incident_type: -> { IncidentTypeV2 },
      previous_incident_type: -> { IncidentTypeV2 },
      updater: -> { ActorV2 }
    )
  end
end
