# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ActivityAlertRefV2 = Model.define(
      actor: -> { ActorV2 },
      alert_id: :string
    )

    class ActivityAlertRefV2
      # @!attribute [r] actor
      #   The actor field
      #   @return [ActorV2, nil]
      # @!attribute [r] alert_id
      #   The alert
      #   @return [String, nil]
    end
  end
end
