# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] actor
    #   @return [ActorV2, nil]
    # @!attribute [r] alert_id
    #   @return [String, nil] The alert.
    ActivityAlertRefV2 = Model.define(
      actor: -> { ActorV2 },
      alert_id: :string
    )
  end
end
