# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] custom_field
    #   @return [CustomFieldTypeInfoV2, nil]
    # @!attribute [r] new_values
    #   @return [Array<CustomFieldValueV2>, nil] Values after the change, up to 100 of them
    # @!attribute [r] new_values_count
    #   @return [Integer, nil] How many values there are now, which can exceed the array above
    # @!attribute [r] previous_values
    #   @return [Array<CustomFieldValueV2>, nil] Values before the change, up to 100 of them
    # @!attribute [r] previous_values_count
    #   @return [Integer, nil] How many values there were before, which can exceed the array above
    # @!attribute [r] updater
    #   @return [ActorV2, nil]
    ActivityCustomFieldValueUpdateV2 = Model.define(
      custom_field: -> { CustomFieldTypeInfoV2 },
      new_values: [-> { CustomFieldValueV2 }],
      new_values_count: :integer,
      previous_values: [-> { CustomFieldValueV2 }],
      previous_values_count: :integer,
      updater: -> { ActorV2 }
    )
  end
end
