# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ActivityEscalationAcknowledgedV2 = Model.define(
      acknowledger: -> { UserV2 },
      escalation_id: :string
    )

    class ActivityEscalationAcknowledgedV2
      # @!attribute [r] acknowledger
      #   The acknowledger field
      #   @return [UserV2, nil]
      # @!attribute [r] escalation_id
      #   The escalation that was acknowledged
      #   @return [String, nil]
    end
  end
end
