# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] new_summary
    #   @return [String, nil] The summary after this change, in markdown
    # @!attribute [r] previous_summary
    #   @return [String, nil] The summary before this change, in markdown
    # @!attribute [r] updater
    #   @return [ActorV2, nil]
    ActivitySummaryUpdateV2 = Model.define(
      new_summary: :string,
      previous_summary: :string,
      updater: -> { ActorV2 }
    )
  end
end
