# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] action_id
    #   @return [String, nil] The action that changed.
    # @!attribute [r] new_assignee
    #   @return [UserV2, nil]
    # @!attribute [r] new_status
    #   @return [String, nil] Status after, when the status changed One of: outstanding, completed, deleted, not_doing.
    # @!attribute [r] previous_assignee
    #   @return [UserV2, nil]
    # @!attribute [r] previous_status
    #   @return [String, nil] Status before, when the status changed One of: outstanding, completed, deleted, not_doing.
    # @!attribute [r] updater
    #   @return [ActorV2, nil]
    ActivityActionUpdatedV2 = Model.define(
      action_id: :string,
      new_assignee: -> { UserV2 },
      new_status: :string,
      previous_assignee: -> { UserV2 },
      previous_status: :string,
      updater: -> { ActorV2 }
    )
  end
end
