# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertRouteCustomFieldBindingV3 = Model.define(
      binding: -> { EngineParamBindingV3 },
      custom_field_id: :string,
      merge_strategy: :string
    )

    class AlertRouteCustomFieldBindingV3
      # @!attribute [r] binding
      #   The binding field
      #   @return [EngineParamBindingV3, nil]
      # @!attribute [r] custom_field_id
      #   ID of the custom field
      #   @return [String, nil]
      # @!attribute [r] merge_strategy
      #   The strategy to use when multiple alerts match this route One of: first-wins,…
      #   @return [String, nil]
    end
  end
end
