# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] array
    #   @return [Boolean, nil] Whether this attribute is an array
    # @!attribute [r] emoji
    #   @return [String, nil] The emoji to display alongside this attribute in chat messages, stored without colons
    # @!attribute [r] id
    #   @return [String, nil] The ID of this attribute
    # @!attribute [r] name
    #   @return [String, nil] Unique name of this attribute
    # @!attribute [r] required
    #   @return [Boolean, nil] Whether this attribute is required.
    # @!attribute [r] type
    #   @return [String, nil] Engine resource name for this attribute
    AlertAttributeV2 = Model.define(
      array: :boolean,
      emoji: :string,
      id: :string,
      name: :string,
      required: :boolean,
      type: :string
    )
  end
end
