# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] alert_group_id
    #   @return [String, nil] ID of the alert group this note is attached to.
    # @!attribute [r] alert_id
    #   @return [String, nil] ID of the alert this note is attached to.
    # @!attribute [r] content
    #   @return [String, nil] Markdown body of the note
    # @!attribute [r] created_at
    #   @return [Time, nil] When this note was first created
    # @!attribute [r] creator
    #   @return [ActorV1, nil]
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier for the alert note
    # @!attribute [r] images
    #   @return [Array<ImageV1>, nil] Images attached to the current version of the note, with signed URLs valid for 10 minutes
    # @!attribute [r] last_edited_at
    #   @return [Time, nil] When this note was last edited, only set if it has been edited at least once since creation
    # @!attribute [r] updated_at
    #   @return [Time, nil] When this note was last updated
    AlertNoteV1 = Model.define(
      alert_group_id: :string,
      alert_id: :string,
      content: :string,
      created_at: :time,
      creator: -> { ActorV1 },
      id: :string,
      images: [-> { ImageV1 }],
      last_edited_at: :time,
      updated_at: :time
    )
  end
end
