# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] binding
    #   @return [EngineParamBindingPayloadV3, nil]
    # @!attribute [r] custom_field_id
    #   @return [String, nil] ID of the custom field
    # @!attribute [r] merge_strategy
    #   @return [String, nil] The strategy to use when multiple alerts match this route One of: first-wins, last-wins, append.
    AlertRouteCustomFieldBindingPayloadV3 = Model.define(
      binding: -> { EngineParamBindingPayloadV3 },
      custom_field_id: :string,
      merge_strategy: :string
    )
  end
end
