# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # Controls how this source's ingest rate limit is split into buckets.
    #
    # @!attribute [r] rate_limit_shard_key_path
    #   @return [String, nil] JSON path to a value that splits this source's rate limit into per-value buckets.
    AlertSourceRateLimitShardingV2 = Model.define(
      rate_limit_shard_key_path: :string
    )
  end
end
