# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertSourceJiraOptionsV2 = Model.define(
      project_ids: [:string]
    )

    class AlertSourceJiraOptionsV2
      # @!attribute [r] project_ids
      #   Which projects in Jira should this alert source watch for new issues?
      #   @return [Array<String>, nil]
    end
  end
end
