# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] project_ids
    #   @return [Array<String>, nil] Which Azure DevOps projects should this alert source watch for work item updates?
    AlertSourceAzureDevopsOptionsV2 = Model.define(
      project_ids: [:string]
    )
  end
end
