# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertSourceAzureDevopsOptionsV2 = Model.define(
      project_ids: [:string]
    )

    class AlertSourceAzureDevopsOptionsV2
      # @!attribute [r] project_ids
      #   Which Azure DevOps projects should this alert source watch for work item…
      #   @return [Array<String>, nil]
    end
  end
end
