# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertRouteAutoGeneratedTemplateBindingPayloadV2 = Model.define(
      autogenerated: :boolean,
      binding: -> { EngineParamBindingPayloadV2 }
    )

    class AlertRouteAutoGeneratedTemplateBindingPayloadV2
      # @!attribute [r] autogenerated
      #   Whether this attribute is autogenerated using AI or not
      #   @return [Boolean, nil]
      # @!attribute [r] binding
      #   The binding field
      #   @return [EngineParamBindingPayloadV2, nil]
    end
  end
end
