# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertRouteChannelConfigPayloadV2 = Model.define(
      condition_groups: [-> { ConditionGroupPayloadV2 }],
      ms_teams_targets: -> { AlertRouteChannelTargetPayloadV2 },
      slack_targets: -> { AlertRouteChannelTargetPayloadV2 }
    )

    class AlertRouteChannelConfigPayloadV2
      # @!attribute [r] condition_groups
      #   The conditions that must be met for this channel config to be used
      #   @return [Array<ConditionGroupPayloadV2>, nil]
      # @!attribute [r] ms_teams_targets
      #   The ms_teams_targets field
      #   @return [AlertRouteChannelTargetPayloadV2, nil]
      # @!attribute [r] slack_targets
      #   The slack_targets field
      #   @return [AlertRouteChannelTargetPayloadV2, nil]
    end
  end
end
