# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertActorV2 = Model.define(
      id: :string,
      title: :string
    )

    class AlertActorV2
      # @!attribute [r] id
      #   The ID of this alert
      #   @return [String, nil]
      # @!attribute [r] title
      #   The title of the alert, parsed from the alert payload according to the alert…
      #   @return [String, nil]
    end
  end
end
