# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] binding
    #   @return [EngineParamBindingV2, nil]
    # @!attribute [r] channel_visibility
    #   @return [String, nil] The visibility of the channel
    AlertRouteChannelTargetV2 = Model.define(
      binding: -> { EngineParamBindingV2 },
      channel_visibility: :string
    )
  end
end
