# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertRouteTemplateBindingV3 = Model.define(
      binding: -> { EngineParamBindingV3 }
    )

    class AlertRouteTemplateBindingV3
      # @!attribute [r] binding
      #   The binding field
      #   @return [EngineParamBindingV3, nil]
    end
  end
end
