# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] binding
    #   @return [EngineParamBindingPayloadV2, nil]
    # @!attribute [r] merge_strategy
    #   @return [String, nil] Strategy for merging severity when multiple alerts create/update the same incident One of: first-wins, max.
    AlertRouteSeverityBindingPayloadV2 = Model.define(
      binding: -> { EngineParamBindingPayloadV2 },
      merge_strategy: :string
    )
  end
end
