# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertsRemoveTagsPayloadV2 = Model.define(
      tags: [:string]
    )

    class AlertsRemoveTagsPayloadV2
      # @!attribute [r] tags
      #   Tag names to remove from this alert
      #   @return [Array<String>, nil]
    end
  end
end
