# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertRoutesUpdatePayloadV3 = Model.define(
      alert_sources: [-> { AlertRouteAlertSourcePayloadV3 }],
      condition_groups: [-> { ConditionGroupPayloadV3 }],
      enabled: :boolean,
      escalation_config: -> { AlertRouteEscalationConfigPayloadV3 },
      expressions: [-> { ExpressionPayloadV3 }],
      grouping_config: -> { AlertGroupingConfigV3 },
      incident_config: -> { AlertRouteIncidentConfigPayloadV3 },
      is_private: :boolean,
      message_config: -> { AlertMessageConfigPayloadV3 },
      name: :string,
      owning_team_ids: [:string],
      version: :integer
    )

    class AlertRoutesUpdatePayloadV3
      # @!attribute [r] alert_sources
      #   Which alert sources this route matches
      #   @return [Array<AlertRouteAlertSourcePayloadV3>, nil]
      # @!attribute [r] condition_groups
      #   Filter: the condition groups that must be true for this route to fire
      #   @return [Array<ConditionGroupPayloadV3>, nil]
      # @!attribute [r] enabled
      #   Whether this alert route is enabled
      #   @return [Boolean, nil]
      # @!attribute [r] escalation_config
      #   The escalation_config field
      #   @return [AlertRouteEscalationConfigPayloadV3, nil]
      # @!attribute [r] expressions
      #   The expressions used by bindings in this route
      #   @return [Array<ExpressionPayloadV3>, nil]
      # @!attribute [r] grouping_config
      #   The grouping_config field
      #   @return [AlertGroupingConfigV3, nil]
      # @!attribute [r] incident_config
      #   The incident_config field
      #   @return [AlertRouteIncidentConfigPayloadV3, nil]
      # @!attribute [r] is_private
      #   Whether this alert route is private
      #   @return [Boolean, nil]
      # @!attribute [r] message_config
      #   The message_config field
      #   @return [AlertMessageConfigPayloadV3, nil]
      # @!attribute [r] name
      #   The name of this alert route, for the user's reference
      #   @return [String, nil]
      # @!attribute [r] owning_team_ids
      #   IDs of teams that own this alert route
      #   @return [Array<String>, nil]
      # @!attribute [r] version
      #   The version this update will create
      #   @return [Integer, nil]
    end
  end
end
