# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # The template an alert route applies to the incidents it creates. Disabling incident creation clears it.
    #
    # @!attribute [r] custom_fields
    #   @return [Array<AlertRouteCustomFieldBindingV3>, nil] Custom fields configuration
    # @!attribute [r] incident_mode
    #   @return [AlertRouteTemplateBindingV3, nil]
    # @!attribute [r] incident_type
    #   @return [AlertRouteTemplateBindingV3, nil]
    # @!attribute [r] membership_teams
    #   @return [AlertRouteTemplateBindingV3, nil]
    # @!attribute [r] name
    #   @return [AlertRouteAutoGeneratedTemplateBindingV3, nil]
    # @!attribute [r] severity
    #   @return [AlertRouteSeverityBindingV3, nil]
    # @!attribute [r] start_in_triage
    #   @return [AlertRouteTemplateBindingV3, nil]
    # @!attribute [r] summary
    #   @return [AlertRouteAutoGeneratedTemplateBindingV3, nil]
    AlertRouteIncidentTemplateV3 = Model.define(
      custom_fields: [-> { AlertRouteCustomFieldBindingV3 }],
      incident_mode: -> { AlertRouteTemplateBindingV3 },
      incident_type: -> { AlertRouteTemplateBindingV3 },
      membership_teams: -> { AlertRouteTemplateBindingV3 },
      name: -> { AlertRouteAutoGeneratedTemplateBindingV3 },
      severity: -> { AlertRouteSeverityBindingV3 },
      start_in_triage: -> { AlertRouteTemplateBindingV3 },
      summary: -> { AlertRouteAutoGeneratedTemplateBindingV3 }
    )
  end
end
