# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertRouteIncidentTemplatePayloadV3 = Model.define(
      custom_fields: [-> { AlertRouteCustomFieldBindingPayloadV3 }],
      incident_mode: -> { AlertRouteTemplateBindingPayloadV3 },
      incident_type: -> { AlertRouteTemplateBindingPayloadV3 },
      membership_teams: -> { AlertRouteTemplateBindingPayloadV3 },
      name: -> { AlertRouteAutoGeneratedTemplateBindingPayloadV3 },
      severity: -> { AlertRouteSeverityBindingPayloadV3 },
      start_in_triage: -> { AlertRouteTemplateBindingPayloadV3 },
      summary: -> { AlertRouteAutoGeneratedTemplateBindingPayloadV3 }
    )

    # The template this alert route applies to the incidents it creates. It must be unset when incident creation is disabled. Disabling incident creation clears a template the route already has.
    class AlertRouteIncidentTemplatePayloadV3
      # @!attribute [r] custom_fields
      #   Custom fields configuration
      #   @return [Array<AlertRouteCustomFieldBindingPayloadV3>, nil]
      # @!attribute [r] incident_mode
      #   The incident_mode field
      #   @return [AlertRouteTemplateBindingPayloadV3, nil]
      # @!attribute [r] incident_type
      #   The incident_type field
      #   @return [AlertRouteTemplateBindingPayloadV3, nil]
      # @!attribute [r] membership_teams
      #   The membership_teams field
      #   @return [AlertRouteTemplateBindingPayloadV3, nil]
      # @!attribute [r] name
      #   The name field
      #   @return [AlertRouteAutoGeneratedTemplateBindingPayloadV3, nil]
      # @!attribute [r] severity
      #   The severity field
      #   @return [AlertRouteSeverityBindingPayloadV3, nil]
      # @!attribute [r] start_in_triage
      #   The start_in_triage field
      #   @return [AlertRouteTemplateBindingPayloadV3, nil]
      # @!attribute [r] summary
      #   The summary field
      #   @return [AlertRouteAutoGeneratedTemplateBindingPayloadV3, nil]
    end
  end
end
