# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertSourceRateLimitShardingV2 = Model.define(
      rate_limit_shard_key_path: :string
    )

    # Controls how this source's ingest rate limit is split into buckets.
    class AlertSourceRateLimitShardingV2
      # @!attribute [r] rate_limit_shard_key_path
      #   JSON path to a value that splits this source's rate limit into per-value…
      #   @return [String, nil]
    end
  end
end
