# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] tags
    #   @return [Array<String>, nil] Tag names to add to this alert
    AlertsAddTagsPayloadV2 = Model.define(
      tags: [:string]
    )
  end
end
