# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] alert_sources
    #   @return [Array<AlertRouteAlertSourcePayloadV3>, nil] Which alert sources this route matches
    # @!attribute [r] condition_groups
    #   @return [Array<ConditionGroupPayloadV3>, nil] Filter: the condition groups that must be true for this route to fire
    # @!attribute [r] enabled
    #   @return [Boolean, nil] Whether this alert route is enabled
    # @!attribute [r] escalation_config
    #   @return [AlertRouteEscalationConfigPayloadV3, nil]
    # @!attribute [r] expressions
    #   @return [Array<ExpressionPayloadV3>, nil] The expressions used by bindings in this route
    # @!attribute [r] grouping_config
    #   @return [AlertGroupingConfigV3, nil]
    # @!attribute [r] incident_config
    #   @return [AlertRouteIncidentConfigPayloadV3, nil]
    # @!attribute [r] is_private
    #   @return [Boolean, nil] Whether this alert route is private.
    # @!attribute [r] message_config
    #   @return [AlertMessageConfigPayloadV3, nil]
    # @!attribute [r] name
    #   @return [String, nil] The name of this alert route, for the user's reference
    # @!attribute [r] owning_team_ids
    #   @return [Array<String>, nil] IDs of teams that own this alert route
    AlertRoutesCreatePayloadV3 = Model.define(
      alert_sources: [-> { AlertRouteAlertSourcePayloadV3 }],
      condition_groups: [-> { ConditionGroupPayloadV3 }],
      enabled: :boolean,
      escalation_config: -> { AlertRouteEscalationConfigPayloadV3 },
      expressions: [-> { ExpressionPayloadV3 }],
      grouping_config: -> { AlertGroupingConfigV3 },
      incident_config: -> { AlertRouteIncidentConfigPayloadV3 },
      is_private: :boolean,
      message_config: -> { AlertMessageConfigPayloadV3 },
      name: :string,
      owning_team_ids: [:string]
    )
  end
end
