# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertSourcesValidatePayloadV2 = Model.define(
      owning_team_ids: [:string],
      source_type: :string,
      template: -> { AlertTemplatePayloadV2 }
    )

    class AlertSourcesValidatePayloadV2
      # @!attribute [r] owning_team_ids
      #   IDs of teams that own this alert source
      #   @return [Array<String>, nil]
      # @!attribute [r] source_type
      #   Type of alert source One of: alertmanager, app_optics, azure_monitor,…
      #   @return [String, nil]
      # @!attribute [r] template
      #   The template field
      #   @return [AlertTemplatePayloadV2, nil]
    end
  end
end
