# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertSourceHTTPCustomOptionsV2 = Model.define(
      deduplication_key_path: :string,
      transform_expression: :string
    )

    class AlertSourceHTTPCustomOptionsV2
      # @!attribute [r] deduplication_key_path
      #   JSON path to extract the deduplication key from the payload
      #   @return [String, nil]
      # @!attribute [r] transform_expression
      #   JavaScript expression that returns an object with all alert fields
      #   @return [String, nil]
    end
  end
end
