# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertRouteChannelTargetPayloadV2 = Model.define(
      binding: -> { EngineParamBindingPayloadV2 },
      channel_visibility: :string
    )

    class AlertRouteChannelTargetPayloadV2
      # @!attribute [r] binding
      #   The binding field
      #   @return [EngineParamBindingPayloadV2, nil]
      # @!attribute [r] channel_visibility
      #   The visibility of the channel
      #   @return [String, nil]
    end
  end
end
