# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] alert_attribute_id
    #   @return [String, nil] ID of the alert attribute to set with this binding
    # @!attribute [r] binding
    #   @return [AlertTemplateAttributeBindingPayloadV2, nil]
    AlertTemplateAttributePayloadV2 = Model.define(
      alert_attribute_id: :string,
      binding: -> { AlertTemplateAttributeBindingPayloadV2 }
    )
  end
end
