# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertRouteIncidentTemplateV3 = Model.define(
      custom_fields: [-> { AlertRouteCustomFieldBindingV3 }],
      incident_mode: -> { AlertRouteTemplateBindingV3 },
      incident_type: -> { AlertRouteTemplateBindingV3 },
      membership_teams: -> { AlertRouteTemplateBindingV3 },
      name: -> { AlertRouteAutoGeneratedTemplateBindingV3 },
      severity: -> { AlertRouteSeverityBindingV3 },
      start_in_triage: -> { AlertRouteTemplateBindingV3 },
      summary: -> { AlertRouteAutoGeneratedTemplateBindingV3 }
    )

    # The template an alert route applies to the incidents it creates. Disabling incident creation clears it.
    class AlertRouteIncidentTemplateV3
      # @!attribute [r] custom_fields
      #   Custom fields configuration
      #   @return [Array<AlertRouteCustomFieldBindingV3>, nil]
      # @!attribute [r] incident_mode
      #   The incident_mode field
      #   @return [AlertRouteTemplateBindingV3, nil]
      # @!attribute [r] incident_type
      #   The incident_type field
      #   @return [AlertRouteTemplateBindingV3, nil]
      # @!attribute [r] membership_teams
      #   The membership_teams field
      #   @return [AlertRouteTemplateBindingV3, nil]
      # @!attribute [r] name
      #   The name field
      #   @return [AlertRouteAutoGeneratedTemplateBindingV3, nil]
      # @!attribute [r] severity
      #   The severity field
      #   @return [AlertRouteSeverityBindingV3, nil]
      # @!attribute [r] start_in_triage
      #   The start_in_triage field
      #   @return [AlertRouteTemplateBindingV3, nil]
      # @!attribute [r] summary
      #   The summary field
      #   @return [AlertRouteAutoGeneratedTemplateBindingV3, nil]
    end
  end
end
