# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] condition_groups
    #   @return [Array<ConditionGroupV2>, nil] The conditions that must be met for this channel config to be used
    # @!attribute [r] ms_teams_targets
    #   @return [AlertRouteChannelTargetV2, nil]
    # @!attribute [r] slack_targets
    #   @return [AlertRouteChannelTargetV2, nil]
    AlertRouteChannelConfigV2 = Model.define(
      condition_groups: [-> { ConditionGroupV2 }],
      ms_teams_targets: -> { AlertRouteChannelTargetV2 },
      slack_targets: -> { AlertRouteChannelTargetV2 }
    )
  end
end
