# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AlertRouteSeverityBindingV2 = Model.define(
      binding: -> { EngineParamBindingV2 },
      merge_strategy: :string
    )

    class AlertRouteSeverityBindingV2
      # @!attribute [r] binding
      #   The binding field
      #   @return [EngineParamBindingV2, nil]
      # @!attribute [r] merge_strategy
      #   Strategy for merging severity when multiple alerts create/update the same…
      #   @return [String, nil]
    end
  end
end
