# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] alert_sources
    #   @return [Array<AlertRouteAlertSourcePayloadV2>, nil] Which alert sources should this alert route match?
    # @!attribute [r] channel_config
    #   @return [Array<AlertRouteChannelConfigPayloadV2>, nil] The channel configuration for this alert route
    # @!attribute [r] condition_groups
    #   @return [Array<ConditionGroupPayloadV2>, nil] What condition groups must be true for this alert route to fire?
    # @!attribute [r] created_at
    #   @return [Time, nil] The time of creation of this alert route
    # @!attribute [r] enabled
    #   @return [Boolean, nil] Whether this alert route is enabled or not
    # @!attribute [r] escalation_config
    #   @return [AlertRouteEscalationConfigPayloadV2, nil]
    # @!attribute [r] expressions
    #   @return [Array<ExpressionPayloadV2>, nil] The expressions used in this template
    # @!attribute [r] incident_config
    #   @return [AlertRouteIncidentConfigPayloadV2, nil]
    # @!attribute [r] incident_template
    #   @return [AlertRouteIncidentTemplatePayloadV2, nil]
    # @!attribute [r] is_private
    #   @return [Boolean, nil] Whether this alert route is private.
    # @!attribute [r] message_template
    #   @return [EngineParamBindingPayloadV2, nil]
    # @!attribute [r] name
    #   @return [String, nil] The name of this alert route config, for the user's reference
    # @!attribute [r] owning_team_ids
    #   @return [Array<String>, nil] IDs of teams that own this alert route
    # @!attribute [r] updated_at
    #   @return [Time, nil] The time of last update of this alert route
    AlertRoutesCreatePayloadV2 = Model.define(
      alert_sources: [-> { AlertRouteAlertSourcePayloadV2 }],
      channel_config: [-> { AlertRouteChannelConfigPayloadV2 }],
      condition_groups: [-> { ConditionGroupPayloadV2 }],
      created_at: :time,
      enabled: :boolean,
      escalation_config: -> { AlertRouteEscalationConfigPayloadV2 },
      expressions: [-> { ExpressionPayloadV2 }],
      incident_config: -> { AlertRouteIncidentConfigPayloadV2 },
      incident_template: -> { AlertRouteIncidentTemplatePayloadV2 },
      is_private: :boolean,
      message_template: -> { EngineParamBindingPayloadV2 },
      name: :string,
      owning_team_ids: [:string],
      updated_at: :time
    )
  end
end
