# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] custom_field_id
    #   @return [String, nil] ID of the custom field to show.
    # @!attribute [r] emoji
    #   @return [String, nil] Emoji shown next to this field, as a Slack emoji name
    # @!attribute [r] field_type
    #   @return [String, nil] Type of this field One of: announcement_post_fields_status, announcement_post_fields_incident_type, announcement_post_fields_severity, announcement_post_fields_role, announcement_post_fields_description, announcement_post_fields_custom_field, announcement_post_fields_timestamp, announcement_post_fields_creator, announcement_post_fields_slack, announcement_post_fields_rich_text.
    # @!attribute [r] incident_role_id
    #   @return [String, nil] ID of the incident role to show.
    # @!attribute [r] incident_timestamp_id
    #   @return [String, nil] ID of the incident timestamp to show.
    # @!attribute [r] rank
    #   @return [Integer, nil] Position of this field on the post, lowest first
    # @!attribute [r] rich_text
    #   @return [AnnouncementTemplateRichTextV2, nil]
    AnnouncementTemplateFieldPayloadV2 = Model.define(
      custom_field_id: :string,
      emoji: :string,
      field_type: :string,
      incident_role_id: :string,
      incident_timestamp_id: :string,
      rank: :integer,
      rich_text: -> { AnnouncementTemplateRichTextV2 }
    )
  end
end
