# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AnnouncementRuleV2 = Model.define(
      condition_groups: [-> { ConditionGroupV2 }],
      conditions_no_longer_apply_behaviour: :string,
      created_at: :time,
      id: :string,
      microsoft_teams_channel_ids: [:string],
      mode: :string,
      name: :string,
      owning_team_ids: [:string],
      private_incident_scope: :string,
      slack_channel_ids: [:string],
      template_id: :string,
      update_sharing_mode: :string,
      updated_at: :time
    )

    # An announcement rule posts an announcement of matching incidents into one or more channels.
    class AnnouncementRuleV2
      # @!attribute [r] condition_groups
      #   Incidents are announced when they match any of these condition groups
      #   @return [Array<ConditionGroupV2>, nil]
      # @!attribute [r] conditions_no_longer_apply_behaviour
      #   Whether to remove announcement posts when the incident no longer matches this…
      #   @return [String, nil]
      # @!attribute [r] created_at
      #   When the rule was created
      #   @return [Time, nil]
      # @!attribute [r] id
      #   Unique identifier for this announcement rule
      #   @return [String, nil]
      # @!attribute [r] microsoft_teams_channel_ids
      #   Microsoft Teams channels to post announcements into, as team_id/channel_id,…
      #   @return [Array<String>, nil]
      # @!attribute [r] mode
      #   Which incidents are announced: live incidents only, or triage incidents too…
      #   @return [String, nil]
      # @!attribute [r] name
      #   Human readable name for the rule
      #   @return [String, nil]
      # @!attribute [r] owning_team_ids
      #   IDs of the teams that own this rule
      #   @return [Array<String>, nil]
      # @!attribute [r] private_incident_scope
      #   Which private incidents this rule announces: every private incident (all),…
      #   @return [String, nil]
      # @!attribute [r] slack_channel_ids
      #   IDs of the Slack channels to post announcements into, when the organisation…
      #   @return [Array<String>, nil]
      # @!attribute [r] template_id
      #   ID of the announcement template used to render this rule's posts
      #   @return [String, nil]
      # @!attribute [r] update_sharing_mode
      #   Where incident updates are shared once the incident is announced One of:…
      #   @return [String, nil]
      # @!attribute [r] updated_at
      #   When the rule was last updated
      #   @return [Time, nil]
    end
  end
end
