# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AnnouncementTemplateFieldV2 = Model.define(
      custom_field_id: :string,
      emoji: :string,
      field_type: :string,
      incident_role_id: :string,
      incident_timestamp_id: :string,
      rank: :integer,
      rich_text: -> { AnnouncementTemplateRichTextV2 },
      title: :string
    )

    class AnnouncementTemplateFieldV2
      # @!attribute [r] custom_field_id
      #   ID of the custom field to show, for custom field fields
      #   @return [String, nil]
      # @!attribute [r] emoji
      #   Emoji shown next to this field
      #   @return [String, nil]
      # @!attribute [r] field_type
      #   Type of this field One of: announcement_post_fields_status,…
      #   @return [String, nil]
      # @!attribute [r] incident_role_id
      #   ID of the incident role to show, for incident role fields
      #   @return [String, nil]
      # @!attribute [r] incident_timestamp_id
      #   ID of the incident timestamp to show, for incident timestamp fields
      #   @return [String, nil]
      # @!attribute [r] rank
      #   Position of this field on the post, lowest first
      #   @return [Integer, nil]
      # @!attribute [r] rich_text
      #   The rich_text field
      #   @return [AnnouncementTemplateRichTextV2, nil]
      # @!attribute [r] title
      #   Title shown next to this field, derived from its type
      #   @return [String, nil]
    end
  end
end
