# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    APIKeyV1 = Model.define(
      comments: :string,
      created_at: :time,
      creator: -> { ActorV1 },
      id: :string,
      last_used_at: :time,
      name: :string,
      roles: [-> { APIKeyRoleV1 }],
      team_ids: [:string],
      team_roles: [-> { APIKeyTeamRoleV1 }],
      token_last_issued_at: :time
    )

    class APIKeyV1
      # @!attribute [r] comments
      #   Freeform notes about this API key
      #   @return [String, nil]
      # @!attribute [r] created_at
      #   When the API key was created
      #   @return [Time, nil]
      # @!attribute [r] creator
      #   The creator field
      #   @return [ActorV1, nil]
      # @!attribute [r] id
      #   Unique identifier for this API key
      #   @return [String, nil]
      # @!attribute [r] last_used_at
      #   When the key was last used to authenticate a request
      #   @return [Time, nil]
      # @!attribute [r] name
      #   The name of the API key, for the user's reference
      #   @return [String, nil]
      # @!attribute [r] roles
      #   The account-level roles assigned to this API key
      #   @return [Array<APIKeyRoleV1>, nil]
      # @!attribute [r] team_ids
      #   IDs of teams that this API key is scoped to
      #   @return [Array<String>, nil]
      # @!attribute [r] team_roles
      #   The team-level roles assigned to this API key
      #   @return [Array<APIKeyTeamRoleV1>, nil]
      # @!attribute [r] token_last_issued_at
      #   When the current token for this API was last issued
      #   @return [Time, nil]
    end
  end
end
