# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    APIKeysCreatePayloadV1 = Model.define(
      comments: :string,
      name: :string,
      role_names: [:string],
      team_ids: [:string],
      team_role_names: [:string]
    )

    class APIKeysCreatePayloadV1
      # @!attribute [r] comments
      #   Freeform notes about the API key
      #   @return [String, nil]
      # @!attribute [r] name
      #   Human-readable name for the new API key
      #   @return [String, nil]
      # @!attribute [r] role_names
      #   Account-level roles to assign to the API key
      #   @return [Array<String>, nil]
      # @!attribute [r] team_ids
      #   IDs of teams to scope the `team_role_names` to
      #   @return [Array<String>, nil]
      # @!attribute [r] team_role_names
      #   Roles to grant for the teams specified in `team_ids`
      #   @return [Array<String>, nil]
    end
  end
end
