# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    APIKeyActorV1 = Model.define(
      id: :string,
      name: :string
    )

    class APIKeyActorV1
      # @!attribute [r] id
      #   Unique identifier for this API key
      #   @return [String, nil]
      # @!attribute [r] name
      #   The name of the API key, for the user's reference
      #   @return [String, nil]
    end
  end
end
