# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] action
    #   @return [String, nil] The type of log entry that this is
    # @!attribute [r] actor
    #   @return [AuditLogActorV2, nil]
    # @!attribute [r] context
    #   @return [AuditLogEntryContextV2, nil]
    # @!attribute [r] metadata
    #   @return [AuditLogQrCodeMobileLoginSettingUpdatedMetadataV2, nil]
    # @!attribute [r] occurred_at
    #   @return [Time, nil] When the entry occurred
    # @!attribute [r] targets
    #   @return [Array<AuditLogTargetV2>, nil] The custom field that was created
    # @!attribute [r] version
    #   @return [Integer, nil] Which version the event is
    AuditLogsQrCodeMobileLoginSettingUpdatedV1 = Model.define(
      action: :string,
      actor: -> { AuditLogActorV2 },
      context: -> { AuditLogEntryContextV2 },
      metadata: -> { AuditLogQrCodeMobileLoginSettingUpdatedMetadataV2 },
      occurred_at: :time,
      targets: [-> { AuditLogTargetV2 }],
      version: :integer
    )
  end
end
