# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] id
    #   @return [String, nil] The ID of the actor
    # @!attribute [r] metadata
    #   @return [AuditLogActorMetadataV2, nil]
    # @!attribute [r] name
    #   @return [String, nil] The name of the actor
    # @!attribute [r] type
    #   @return [String, nil] The type of actor One of: user, system, api_key, workflow, external_resource.
    AuditLogActorV2 = Model.define(
      id: :string,
      metadata: -> { AuditLogActorMetadataV2 },
      name: :string,
      type: :string
    )
  end
end
