# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] after_default_team_ids
    #   @return [String, nil] Catalog entry IDs of the default teams after the change, comma separated
    # @!attribute [r] before_default_team_ids
    #   @return [String, nil] Catalog entry IDs of the default teams before the change, comma separated
    AuditLogIncidentTypeDefaultTeamsMetadataV2 = Model.define(
      after_default_team_ids: :string,
      before_default_team_ids: :string
    )
  end
end
