# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AuditLogMobileIntuneEnabledSettingUpdatedMetadataV2 = Model.define(
      enabled: :string
    )

    class AuditLogMobileIntuneEnabledSettingUpdatedMetadataV2
      # @!attribute [r] enabled
      #   Whether Intune is enabled after the update
      #   @return [String, nil]
    end
  end
end
