# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AuditLogTelemetryDataSourceQueriedMetadataV2V2 = Model.define(
      access_mode: :string,
      investigation_id: :string,
      outcome: :string,
      surface: :string,
      telemetry_query_id: :string
    )

    class AuditLogTelemetryDataSourceQueriedMetadataV2V2
      # @!attribute [r] access_mode
      #   The data source's access mode at query time (default, restricted)
      #   @return [String, nil]
      # @!attribute [r] investigation_id
      #   The investigation the query ran for, when investigation-driven
      #   @return [String, nil]
      # @!attribute [r] outcome
      #   Whether the query was granted or denied
      #   @return [String, nil]
      # @!attribute [r] surface
      #   The product surface the query ran from (chat, investigation, explore,…
      #   @return [String, nil]
      # @!attribute [r] telemetry_query_id
      #   ID of the recorded query, pointing at our full stored record of it
      #   @return [String, nil]
    end
  end
end
