# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AuditLogAnnouncementRuleMetadataV2 = Model.define(
      after_owning_team_ids: :string,
      after_private_incident_scope: :string,
      before_owning_team_ids: :string,
      before_private_incident_scope: :string
    )

    class AuditLogAnnouncementRuleMetadataV2
      # @!attribute [r] after_owning_team_ids
      #   Catalog entry IDs of the owning teams after the change, comma separated
      #   @return [String, nil]
      # @!attribute [r] after_private_incident_scope
      #   Which private incidents the rule acts on after the change (all, owning_teams,…
      #   @return [String, nil]
      # @!attribute [r] before_owning_team_ids
      #   Catalog entry IDs of the owning teams before the change, comma separated
      #   @return [String, nil]
      # @!attribute [r] before_private_incident_scope
      #   Which private incidents the rule acted on before the change (all,…
      #   @return [String, nil]
    end
  end
end
