# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] outcome
    #   @return [String, nil] Whether or not the user was able to access the private incident One of: granted, denied.
    AuditLogPrivateIncidentAccessAttemptedMetadataV2 = Model.define(
      outcome: :string
    )
  end
end
