# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AuditLogExtensionConnectorCalledMetadataV3V2 = Model.define(
      access_source: :string,
      class: :string,
      incident_id: :string,
      outcome: :string,
      reason: :string,
      source_kind: :string,
      surface: :string,
      telemetry_query_id: :string,
      write: :string
    )

    class AuditLogExtensionConnectorCalledMetadataV3V2
      # @!attribute [r] access_source
      #   What decided: the connector's access policy, or a decision pinned on this…
      #   @return [String, nil]
      # @!attribute [r] class_
      #   What calling the tool does to the connected system, as the tool's own server…
      #   @return [String, nil]
      # @!attribute [r] incident_id
      #   The incident the call was made for, when incident-scoped
      #   @return [String, nil]
      # @!attribute [r] outcome
      #   How the call ended (success, error, denied)
      #   @return [String, nil]
      # @!attribute [r] reason
      #   Why the call was allowed or refused (allowed, denied_by_rule, disabled,…
      #   @return [String, nil]
      # @!attribute [r] source_kind
      #   The kind of connector that was called (mcp, http)
      #   @return [String, nil]
      # @!attribute [r] surface
      #   The product surface the call ran from (chat, investigation, explore,…
      #   @return [String, nil]
      # @!attribute [r] telemetry_query_id
      #   ID of our stored record of this call, absent for a call that was refused
      #   @return [String, nil]
      # @!attribute [r] write
      #   Whether the call was permitted to change the connected system (true, false)
      #   @return [String, nil]
    end
  end
end
