# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AuditLogPrivateIncidentAccessAttemptedMetadataV2V2 = Model.define(
      access_type: :string,
      outcome: :string,
      team_id: :string
    )

    class AuditLogPrivateIncidentAccessAttemptedMetadataV2V2
      # @!attribute [r] access_type
      #   How the user was granted access to the private incident, or N/A when access…
      #   @return [String, nil]
      # @!attribute [r] outcome
      #   Whether or not the user was able to access the private incident One of:…
      #   @return [String, nil]
      # @!attribute [r] team_id
      #   The ID of the team through which access was granted, or N/A when access_type…
      #   @return [String, nil]
    end
  end
end
