# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] tenant_domain
    #   @return [String, nil] The email domain we verified the tenant owns
    # @!attribute [r] tenant_id
    #   @return [String, nil] The Microsoft Entra tenant that was linked
    AuditLogMicrosoftEntraTenantLinkedMetadataV2 = Model.define(
      tenant_domain: :string,
      tenant_id: :string
    )
  end
end
