# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] enabled
    #   @return [String, nil] Whether QR code mobile login is enabled after the update
    AuditLogQrCodeMobileLoginSettingUpdatedMetadataV2 = Model.define(
      enabled: :string
    )
  end
end
