# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    AuditLogIncidentTypeDefaultTeamsMetadataV2 = Model.define(
      after_default_team_ids: :string,
      before_default_team_ids: :string
    )

    class AuditLogIncidentTypeDefaultTeamsMetadataV2
      # @!attribute [r] after_default_team_ids
      #   Catalog entry IDs of the default teams after the change, comma separated
      #   @return [String, nil]
      # @!attribute [r] before_default_team_ids
      #   Catalog entry IDs of the default teams before the change, comma separated
      #   @return [String, nil]
    end
  end
end
