# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] run_on_private_incidents
    #   @return [String, nil] Whether the policy evaluates private incidents
    AuditLogPolicyMetadataV2 = Model.define(
      run_on_private_incidents: :string
    )
  end
end
