# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CallRouteAllowedCallerV2 = Model.define(
      id: :string,
      name: :string,
      phone_number: :string
    )

    # A phone number allowed to reach a call route.
    class CallRouteAllowedCallerV2
      # @!attribute [r] id
      #   Unique identifier for this allowed caller
      #   @return [String, nil]
      # @!attribute [r] name
      #   Label for whose number this is
      #   @return [String, nil]
      # @!attribute [r] phone_number
      #   The number allowed to call this route, in international format
      #   @return [String, nil]
    end
  end
end
