# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier for this node.
    # @!attribute [r] level
    #   @return [CallRoutePathNodeLevelV2, nil]
    # @!attribute [r] type
    #   @return [String, nil] The type of this node.
    # @!attribute [r] voicemail
    #   @return [CallRoutePathNodeVoicemailV2, nil]
    CallRoutePathNodePayloadV2 = Model.define(
      id: :string,
      level: -> { CallRoutePathNodeLevelV2 },
      type: :string,
      voicemail: -> { CallRoutePathNodeVoicemailV2 }
    )
  end
end
