# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CallRoutePathNodePayloadV2 = Model.define(
      id: :string,
      level: -> { CallRoutePathNodeLevelV2 },
      type: :string,
      voicemail: -> { CallRoutePathNodeVoicemailV2 }
    )

    class CallRoutePathNodePayloadV2
      # @!attribute [r] id
      #   Unique identifier for this node
      #   @return [String, nil]
      # @!attribute [r] level
      #   The level field
      #   @return [CallRoutePathNodeLevelV2, nil]
      # @!attribute [r] type
      #   The type of this node
      #   @return [String, nil]
      # @!attribute [r] voicemail
      #   The voicemail field
      #   @return [CallRoutePathNodeVoicemailV2, nil]
    end
  end
end
