# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # Records a message from the caller, and enriches the resulting alert with the transcript.
    #
    # @!attribute [r] greeting_text
    #   @return [String, nil] What we read to the caller before recording, via text-to-speech in the route's language, exactly as written
    CallRoutePathNodeVoicemailV2 = Model.define(
      greeting_text: :string
    )
  end
end
