# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # A call session is a single occurrence of a call that Scribe attended,
    # for example one Zoom or Google Meet meeting. Several call sessions can exist for
    # the same context: one for each time a call was started.
    #
    # Use the Call Transcript Entries endpoint to page through what Scribe transcribed
    # during a session.
    #
    # @!attribute [r] ended_at
    #   @return [Time, nil] When the call session ended.
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier for this call session
    # @!attribute [r] incident_id
    #   @return [String, nil] The incident this call session belongs to
    # @!attribute [r] started_at
    #   @return [Time, nil] When the call session started
    CallSessionV2 = Model.define(
      ended_at: :time,
      id: :string,
      incident_id: :string,
      started_at: :time
    )
  end
end
