# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # One entry in a call route's phone-tree menu: the digit a caller presses, the
    # prompt we read out to offer it, and who we page when they choose it.
    #
    # @!attribute [r] digit
    #   @return [String, nil] The keypad digit a caller presses to choose this option One of: 1, 2, 3, 4, 5, 6, 7, 8, 9.
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier for this option
    # @!attribute [r] path
    #   @return [Array<CallRoutePathNodeV2>, nil] Who we page when a caller chooses this option
    # @!attribute [r] prompt
    #   @return [String, nil] What we read out to offer this option, via text-to-speech in the route's language, exactly as written
    CallRouteOptionV2 = Model.define(
      digit: :string,
      id: :string,
      path: [-> { CallRoutePathNodeV2 }],
      prompt: :string
    )
  end
end
