# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # Someone a call route pages when a call comes in.
    #
    # @!attribute [r] id
    #   @return [String, nil] Uniquely identifies an entity of this type
    # @!attribute [r] schedule_mode
    #   @return [String, nil] Only set for schedule targets, this specifies which users to fetch from the schedule.
    # @!attribute [r] selected_rota_id
    #   @return [String, nil] For schedule targets, identifies which rota on the schedule the schedule_mode applies to.
    # @!attribute [r] type
    #   @return [String, nil] Whether a call route target is a user or a schedule One of: user, schedule.
    # @!attribute [r] urgency
    #   @return [String, nil] The urgency of this escalation path target One of: high, low.
    CallRouteTargetV2 = Model.define(
      id: :string,
      schedule_mode: :string,
      selected_rota_id: :string,
      type: :string,
      urgency: :string
    )
  end
end
