# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] aliases
    #   @return [Array<String>, nil] Optional aliases that can be used to reference this entry
    # @!attribute [r] attribute_values
    #   @return [Hash{String => EngineParamBindingPayloadV2}, nil] Values of this entry
    # @!attribute [r] catalog_type_id
    #   @return [String, nil] ID of this catalog type
    # @!attribute [r] external_id
    #   @return [String, nil] An optional alternative ID for this entry, which is ensured to be unique for the type
    # @!attribute [r] name
    #   @return [String, nil] Name is the human readable name of this entry
    # @!attribute [r] rank
    #   @return [Integer, nil] When catalog type is ranked, this is used to help order things
    CatalogCreateEntryPayloadV2 = Model.define(
      aliases: [:string],
      attribute_values: Model.map_of(-> { EngineParamBindingPayloadV2 }),
      catalog_type_id: :string,
      external_id: :string,
      name: :string,
      rank: :integer
    )
  end
end
