# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] attributes
    #   @return [Array<CatalogTypeAttributePayloadV2>, nil]
    # @!attribute [r] version
    #   @return [Integer, nil]
    CatalogUpdateTypeSchemaPayloadV2 = Model.define(
      attributes: [-> { CatalogTypeAttributePayloadV2 }],
      version: :integer
    )
  end
end
