# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CatalogEntryV3 = Model.define(
      aliases: [:string],
      archived_at: :time,
      attribute_values: Model.map_of(-> { CatalogEntryEngineParamBindingV3 }),
      catalog_type_id: :string,
      created_at: :time,
      external_id: :string,
      id: :string,
      name: :string,
      rank: :integer,
      updated_at: :time
    )

    class CatalogEntryV3
      # @!attribute [r] aliases
      #   Optional aliases that can be used to reference this entry
      #   @return [Array<String>, nil]
      # @!attribute [r] archived_at
      #   When this entry was archived
      #   @return [Time, nil]
      # @!attribute [r] attribute_values
      #   Values of this entry
      #   @return [Hash{String => CatalogEntryEngineParamBindingV3}, nil]
      # @!attribute [r] catalog_type_id
      #   ID of this catalog type
      #   @return [String, nil]
      # @!attribute [r] created_at
      #   When this entry was created
      #   @return [Time, nil]
      # @!attribute [r] external_id
      #   An optional alternative ID for this entry, which is ensured to be unique for…
      #   @return [String, nil]
      # @!attribute [r] id
      #   ID of this catalog entry
      #   @return [String, nil]
      # @!attribute [r] name
      #   Name is the human readable name of this entry
      #   @return [String, nil]
      # @!attribute [r] rank
      #   When catalog type is ranked, this is used to help order things
      #   @return [Integer, nil]
      # @!attribute [r] updated_at
      #   When this entry was last updated
      #   @return [Time, nil]
    end
  end
end
