# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CatalogUpdateTypeSchemaPayloadV3 = Model.define(
      attributes: [-> { CatalogTypeAttributePayloadV3 }],
      version: :integer
    )

    class CatalogUpdateTypeSchemaPayloadV3
      # @!attribute [r] attributes
      #   The attributes field
      #   @return [Array<CatalogTypeAttributePayloadV3>, nil]
      # @!attribute [r] version
      #   The version field
      #   @return [Integer, nil]
    end
  end
end
