# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] attribute_id
    #   @return [String, nil] the ID of the attribute to use
    # @!attribute [r] attribute_name
    #   @return [String, nil] the name of the attribute to use
    CatalogTypeAttributePathItemV3 = Model.define(
      attribute_id: :string,
      attribute_name: :string
    )
  end
end
