# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] external_id
    #   @return [String, nil] An optional alternative ID for this entry, which is ensured to be unique for the type
    # @!attribute [r] id
    #   @return [String, nil] ID of this catalog entry
    # @!attribute [r] name
    #   @return [String, nil] Name is the human readable name of this entry
    CatalogEntrySlimV3V3 = Model.define(
      external_id: :string,
      id: :string,
      name: :string
    )
  end
end
