# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CatalogTypeSchemaV2 = Model.define(
      attributes: [-> { CatalogTypeAttributeV2 }],
      version: :integer
    )

    class CatalogTypeSchemaV2
      # @!attribute [r] attributes
      #   Attributes of this catalog type
      #   @return [Array<CatalogTypeAttributeV2>, nil]
      # @!attribute [r] version
      #   The version number of this schema
      #   @return [Integer, nil]
    end
  end
end
