# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] annotations
    #   @return [Hash{String => String}, nil] Annotations that can track metadata about this type
    # @!attribute [r] categories
    #   @return [Array<String>, nil] What categories is this type considered part of One of: customer, issue-tracker, product-feature, service, on-call, team, user.
    # @!attribute [r] color
    #   @return [String, nil] Sets the display color of this type in the dashboard One of: yellow, green, blue, violet, pink, cyan, orange.
    # @!attribute [r] description
    #   @return [String, nil] Human readble description of this type
    # @!attribute [r] icon
    #   @return [String, nil] Sets the display icon of this type in the dashboard One of: alert, bolt, box, briefcase, browser, bulb, calendar, clock, cog, components, database, doc, email, escalation-path, files, flag, folder, globe, incident-template, money, server, severity, status-page, store, star, tag, user, users.
    # @!attribute [r] name
    #   @return [String, nil] Name is the human readable name of this type
    # @!attribute [r] owning_team_ids
    #   @return [Array<String>, nil] IDs of the teams that own this catalog type
    # @!attribute [r] ranked
    #   @return [Boolean, nil] If this type should be ranked
    # @!attribute [r] source_repo_url
    #   @return [String, nil] The url of the external repository where this type is managed
    # @!attribute [r] type_name
    #   @return [String, nil] The type name of this catalog type, to be used when defining attributes.
    # @!attribute [r] use_name_as_identifier
    #   @return [Boolean, nil] If enabled, you can refer to entries of this type by their name, as well as their external ID and any aliases.
    CatalogCreateTypePayloadV3 = Model.define(
      annotations: Model.map_of(:string),
      categories: [:string],
      color: :string,
      description: :string,
      icon: :string,
      name: :string,
      owning_team_ids: [:string],
      ranked: :boolean,
      source_repo_url: :string,
      type_name: :string,
      use_name_as_identifier: :boolean
    )
  end
end
