# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] catalog_entry
    #   @return [CatalogEntryReferenceV2, nil]
    # @!attribute [r] helptext
    #   @return [String, nil] This field is deprecated.
    # @!attribute [r] image_url
    #   @return [String, nil] This field is deprecated.
    # @!attribute [r] is_image_slack_icon
    #   @return [Boolean, nil] This field is deprecated.
    # @!attribute [r] label
    #   @return [String, nil] Human readable label to be displayed for user to select
    # @!attribute [r] literal
    #   @return [String, nil] If set, this is the literal value of the step parameter
    # @!attribute [r] reference
    #   @return [String, nil] This field is deprecated.
    # @!attribute [r] sort_key
    #   @return [String, nil] This field is deprecated.
    # @!attribute [r] unavailable
    #   @return [Boolean, nil] This field is deprecated.
    # @!attribute [r] value
    #   @return [String, nil] This field is deprecated.
    CatalogEntryEngineParamBindingValueV2 = Model.define(
      catalog_entry: -> { CatalogEntryReferenceV2 },
      helptext: :string,
      image_url: :string,
      is_image_slack_icon: :boolean,
      label: :string,
      literal: :string,
      reference: :string,
      sort_key: :string,
      unavailable: :boolean,
      value: :string
    )
  end
end
