# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] literal
    #   @return [String, nil] If set, this is the literal value of the step parameter
    CatalogEngineParamBindingValuePayloadV3 = Model.define(
      literal: :string
    )
  end
end
