# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] aliases
    #   @return [Array<String>, nil] Optional aliases that can be used to reference this entry
    # @!attribute [r] archived_at
    #   @return [Time, nil] When this entry was archived
    # @!attribute [r] attribute_values
    #   @return [Hash{String => CatalogEntryEngineParamBindingV3}, nil] Values of this entry
    # @!attribute [r] catalog_type_id
    #   @return [String, nil] ID of this catalog type
    # @!attribute [r] created_at
    #   @return [Time, nil] When this entry was created
    # @!attribute [r] external_id
    #   @return [String, nil] An optional alternative ID for this entry, which is ensured to be unique for the type
    # @!attribute [r] id
    #   @return [String, nil] ID of this catalog entry
    # @!attribute [r] name
    #   @return [String, nil] Name is the human readable name of this entry
    # @!attribute [r] rank
    #   @return [Integer, nil] When catalog type is ranked, this is used to help order things
    # @!attribute [r] updated_at
    #   @return [Time, nil] When this entry was last updated
    CatalogEntryV3 = Model.define(
      aliases: [:string],
      archived_at: :time,
      attribute_values: Model.map_of(-> { CatalogEntryEngineParamBindingV3 }),
      catalog_type_id: :string,
      created_at: :time,
      external_id: :string,
      id: :string,
      name: :string,
      rank: :integer,
      updated_at: :time
    )
  end
end
