# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CatalogTypeAttributePayloadV3 = Model.define(
      array: :boolean,
      backlink_attribute: :string,
      id: :string,
      mode: :string,
      name: :string,
      path: [-> { CatalogTypeAttributePathItemPayloadV3 }],
      type: :string
    )

    class CatalogTypeAttributePayloadV3
      # @!attribute [r] array
      #   Whether this attribute is an array
      #   @return [Boolean, nil]
      # @!attribute [r] backlink_attribute
      #   The attribute to use (if this is a backlink)
      #   @return [String, nil]
      # @!attribute [r] id
      #   The ID of this attribute
      #   @return [String, nil]
      # @!attribute [r] mode
      #   Controls how this attribute is modified One of: , api, dashboard, external,…
      #   @return [String, nil]
      # @!attribute [r] name
      #   Unique name of this attribute
      #   @return [String, nil]
      # @!attribute [r] path
      #   The path to use (if this is an path)
      #   @return [Array<CatalogTypeAttributePathItemPayloadV3>, nil]
      # @!attribute [r] type
      #   Catalog type name for this attribute
      #   @return [String, nil]
    end
  end
end
