# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CatalogUpdateTypeSchemaPayloadV2 = Model.define(
      attributes: [-> { CatalogTypeAttributePayloadV2 }],
      version: :integer
    )

    class CatalogUpdateTypeSchemaPayloadV2
      # @!attribute [r] attributes
      #   The attributes field
      #   @return [Array<CatalogTypeAttributePayloadV2>, nil]
      # @!attribute [r] version
      #   The version field
      #   @return [Integer, nil]
    end
  end
end
