# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ChatChannelSlimV2 = Model.define(
      microsoft_teams_channel_id: :string,
      microsoft_teams_team_id: :string,
      slack_channel_id: :string,
      slack_team_id: :string
    )

    class ChatChannelSlimV2
      # @!attribute [r] microsoft_teams_channel_id
      #   ID of the Microsoft Teams channel, if there is one
      #   @return [String, nil]
      # @!attribute [r] microsoft_teams_team_id
      #   ID of the Microsoft Teams team, if there is one
      #   @return [String, nil]
      # @!attribute [r] slack_channel_id
      #   ID of the Slack channel, if there is one
      #   @return [String, nil]
      # @!attribute [r] slack_team_id
      #   ID of the Slack team, if there is one
      #   @return [String, nil]
    end
  end
end
