# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] operation
    #   @return [String, nil] The name of the operation on the subject
    # @!attribute [r] param_bindings
    #   @return [Array<EngineParamBindingPayloadV2>, nil] List of parameter bindings
    # @!attribute [r] subject
    #   @return [String, nil] The reference of the subject in the trigger scope
    ConditionPayloadV2 = Model.define(
      operation: :string,
      param_bindings: [-> { EngineParamBindingPayloadV2 }],
      subject: :string
    )
  end
end
