# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ConditionPayloadV3 = Model.define(
      operation: :string,
      param_bindings: [-> { EngineParamBindingPayloadV3 }],
      subject: :string
    )

    class ConditionPayloadV3
      # @!attribute [r] operation
      #   The name of the operation on the subject
      #   @return [String, nil]
      # @!attribute [r] param_bindings
      #   List of parameter bindings
      #   @return [Array<EngineParamBindingPayloadV3>, nil]
      # @!attribute [r] subject
      #   The reference of the subject in the trigger scope
      #   @return [String, nil]
    end
  end
end
