# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ConditionGroupPayloadV2 = Model.define(
      conditions: [-> { ConditionPayloadV2 }]
    )

    class ConditionGroupPayloadV2
      # @!attribute [r] conditions
      #   All conditions in this list must be satisfied for the group to be satisfied
      #   @return [Array<ConditionPayloadV2>, nil]
    end
  end
end
