# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ConditionGroupV3 = Model.define(
      conditions: [-> { ConditionV3 }]
    )

    class ConditionGroupV3
      # @!attribute [r] conditions
      #   All conditions in this list must be satisfied for the group to be satisfied
      #   @return [Array<ConditionV3>, nil]
    end
  end
end
