# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] label
    #   @return [String, nil] Human readable label to be displayed for user to select
    # @!attribute [r] value
    #   @return [String, nil] Unique identifier for this option
    ConditionOperationV2 = Model.define(
      label: :string,
      value: :string
    )
  end
end
