# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] label
    #   @return [String, nil] Human readable identifier for the subject
    # @!attribute [r] reference
    #   @return [String, nil] Reference into the scope for the value of the subject
    ConditionSubjectV3 = Model.define(
      label: :string,
      reference: :string
    )
  end
end
