# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ConditionOperationV3 = Model.define(
      label: :string,
      value: :string
    )

    class ConditionOperationV3
      # @!attribute [r] label
      #   Human readable label to be displayed for user to select
      #   @return [String, nil]
      # @!attribute [r] value
      #   Unique identifier for this option
      #   @return [String, nil]
    end
  end
end
