# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ConditionV2 = Model.define(
      operation: -> { ConditionOperationV2 },
      param_bindings: [-> { EngineParamBindingV2 }],
      subject: -> { ConditionSubjectV2 }
    )

    class ConditionV2
      # @!attribute [r] operation
      #   The operation field
      #   @return [ConditionOperationV2, nil]
      # @!attribute [r] param_bindings
      #   Bindings for the operation parameters
      #   @return [Array<EngineParamBindingV2>, nil]
      # @!attribute [r] subject
      #   The subject field
      #   @return [ConditionSubjectV2, nil]
    end
  end
end
