# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier for the custom field value
    # @!attribute [r] value_catalog_entry_id
    #   @return [String, nil] ID of the catalog entry.
    # @!attribute [r] value_link
    #   @return [String, nil] If the custom field type is 'link', this will contain the value assigned.
    # @!attribute [r] value_numeric
    #   @return [String, nil] If the custom field type is 'numeric', this will contain the value assigned.
    # @!attribute [r] value_option_id
    #   @return [String, nil] ID of the custom field option
    # @!attribute [r] value_text
    #   @return [String, nil] If the custom field type is 'text', this will contain the value assigned.
    # @!attribute [r] value_timestamp
    #   @return [String, nil] Deprecated: please use incident timestamp values instead
    CustomFieldValuePayloadV1 = Model.define(
      id: :string,
      value_catalog_entry_id: :string,
      value_link: :string,
      value_numeric: :string,
      value_option_id: :string,
      value_text: :string,
      value_timestamp: :string
    )
  end
end
