# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CustomFieldV2 = Model.define(
      catalog_type_id: :string,
      created_at: :time,
      description: :string,
      field_type: :string,
      filter_by: -> { CustomFieldFilterByOptionsV2 },
      fixed_filter: -> { CustomFieldFixedFilterOptionsV2 },
      group_by_catalog_attribute_id: :string,
      helptext_catalog_attribute_id: :string,
      id: :string,
      name: :string,
      updated_at: :time
    )

    class CustomFieldV2
      # @!attribute [r] catalog_type_id
      #   For catalog fields, the ID of the associated catalog type
      #   @return [String, nil]
      # @!attribute [r] created_at
      #   When the action was created
      #   @return [Time, nil]
      # @!attribute [r] description
      #   Description of the custom field
      #   @return [String, nil]
      # @!attribute [r] field_type
      #   Type of custom field One of: single_select, multi_select, text, link, numeric
      #   @return [String, nil]
      # @!attribute [r] filter_by
      #   The filter_by field
      #   @return [CustomFieldFilterByOptionsV2, nil]
      # @!attribute [r] fixed_filter
      #   The fixed_filter field
      #   @return [CustomFieldFixedFilterOptionsV2, nil]
      # @!attribute [r] group_by_catalog_attribute_id
      #   For catalog fields, the ID of the attribute used to group catalog entries (if…
      #   @return [String, nil]
      # @!attribute [r] helptext_catalog_attribute_id
      #   Which catalog attribute provides helptext for the options
      #   @return [String, nil]
      # @!attribute [r] id
      #   Unique identifier for the custom field
      #   @return [String, nil]
      # @!attribute [r] name
      #   Human readable name for the custom field
      #   @return [String, nil]
      # @!attribute [r] updated_at
      #   When the action was last updated
      #   @return [Time, nil]
    end
  end
end
