# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CustomFieldFixedFilterOptionsV2 = Model.define(
      catalog_attribute_id: :string,
      values: [:string]
    )

    class CustomFieldFixedFilterOptionsV2
      # @!attribute [r] catalog_attribute_id
      #   This must be an attribute of the catalog type of this custom field
      #   @return [String, nil]
      # @!attribute [r] values
      #   The catalog entry IDs (of the type the attribute points at) that the…
      #   @return [Array<String>, nil]
    end
  end
end
