# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CustomFieldOptionV1 = Model.define(
      custom_field_id: :string,
      id: :string,
      sort_key: :integer,
      value: :string
    )

    class CustomFieldOptionV1
      # @!attribute [r] custom_field_id
      #   ID of the custom field this option belongs to
      #   @return [String, nil]
      # @!attribute [r] id
      #   Unique identifier for the custom field option
      #   @return [String, nil]
      # @!attribute [r] sort_key
      #   Sort key used to order the custom field options correctly
      #   @return [Integer, nil]
      # @!attribute [r] value
      #   Human readable name for the custom field option
      #   @return [String, nil]
    end
  end
end
