# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    CustomFieldOptionsUpdatePayloadV1 = Model.define(
      sort_key: :integer,
      value: :string
    )

    class CustomFieldOptionsUpdatePayloadV1
      # @!attribute [r] sort_key
      #   Sort key used to order the custom field options correctly
      #   @return [Integer, nil]
      # @!attribute [r] value
      #   Human readable name for the custom field option
      #   @return [String, nil]
    end
  end
end
