# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] created_at
    #   @return [Time, nil] When the role was created
    # @!attribute [r] description
    #   @return [String, nil] Describes the purpose of the role
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier for the role
    # @!attribute [r] instructions
    #   @return [String, nil] Provided to whoever is nominated for the role.
    # @!attribute [r] name
    #   @return [String, nil] Human readable name of the incident role
    # @!attribute [r] required
    #   @return [Boolean, nil] This field is deprecated.
    # @!attribute [r] role_type
    #   @return [String, nil] Type of incident role One of: lead, reporter, custom.
    # @!attribute [r] shortform
    #   @return [String, nil] Short human readable name for Slack.
    # @!attribute [r] updated_at
    #   @return [Time, nil] When the role was last updated
    EmbeddedIncidentRoleV2 = Model.define(
      created_at: :time,
      description: :string,
      id: :string,
      instructions: :string,
      name: :string,
      required: :boolean,
      role_type: :string,
      shortform: :string,
      updated_at: :time
    )
  end
end
