# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] array_value
    #   @return [Array<EngineParamBindingValuePayloadV3>, nil] If set, this is the array value of the step parameter
    # @!attribute [r] value
    #   @return [EngineParamBindingValuePayloadV3, nil]
    EngineParamBindingPayloadV3 = Model.define(
      array_value: [-> { EngineParamBindingValuePayloadV3 }],
      value: -> { EngineParamBindingValuePayloadV3 }
    )
  end
end
