# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    EngineParamBindingPayloadV2 = Model.define(
      array_value: [-> { EngineParamBindingValuePayloadV2 }],
      value: -> { EngineParamBindingValuePayloadV2 }
    )

    class EngineParamBindingPayloadV2
      # @!attribute [r] array_value
      #   If set, this is the array value of the step parameter
      #   @return [Array<EngineParamBindingValuePayloadV2>, nil]
      # @!attribute [r] value
      #   The value field
      #   @return [EngineParamBindingValuePayloadV2, nil]
    end
  end
end
