# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ErrorSingle = Model.define(
      code: :string,
      message: :string,
      metadata: Model.map_of(:string),
      source: -> { ErrorSource }
    )

    class ErrorSingle
      # @!attribute [r] code
      #   Machine-readable identifier for this specific error
      #   @return [String, nil]
      # @!attribute [r] message
      #   Human readable description of the error
      #   @return [String, nil]
      # @!attribute [r] metadata
      #   Additional metadata about the error, keyed by a string identifier
      #   @return [Hash{String => String}, nil]
      # @!attribute [r] source
      #   The source field
      #   @return [ErrorSource, nil]
    end
  end
end
