# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] message
    #   @return [String, nil] Original internal error message
    # @!attribute [r] stacktrace
    #   @return [Array<String>, nil] Stacktrace of the error, if applicable
    ErrorDebug = Model.define(
      message: :string,
      stacktrace: [:string]
    )
  end
end
