# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    EscalationPathRoundRobinConfigV2 = Model.define(
      enabled: :boolean,
      rotate_after_seconds: :integer
    )

    class EscalationPathRoundRobinConfigV2
      # @!attribute [r] enabled
      #   Whether round robin is enabled for this level
      #   @return [Boolean, nil]
      # @!attribute [r] rotate_after_seconds
      #   How long should we wait before rotating to the next target in a round robin,…
      #   @return [Integer, nil]
    end
  end
end
