# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    EscalationPathNodeIfElsePayloadV2 = Model.define(
      conditions: [-> { ConditionPayloadV2 }],
      else_path: [-> { EscalationPathNodePayloadV2 }],
      then_path: [-> { EscalationPathNodePayloadV2 }]
    )

    class EscalationPathNodeIfElsePayloadV2
      # @!attribute [r] conditions
      #   The condition that defines which branch to take
      #   @return [Array<ConditionPayloadV2>, nil]
      # @!attribute [r] else_path
      #   The nodes that form the levels if our condition is not met
      #   @return [Array<EscalationPathNodePayloadV2>, nil]
      # @!attribute [r] then_path
      #   The nodes that form the levels if our condition is met
      #   @return [Array<EscalationPathNodePayloadV2>, nil]
    end
  end
end
