# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    EscalationPathTemplateNodeIfElseV2 = Model.define(
      conditions: [-> { ConditionV2 }],
      else_path: [-> { EscalationPathTemplateNodeV2 }],
      then_path: [-> { EscalationPathTemplateNodeV2 }]
    )

    class EscalationPathTemplateNodeIfElseV2
      # @!attribute [r] conditions
      #   The condition that defines which branch to take
      #   @return [Array<ConditionV2>, nil]
      # @!attribute [r] else_path
      #   The nodes taken if the condition is not met
      #   @return [Array<EscalationPathTemplateNodeV2>, nil]
      # @!attribute [r] then_path
      #   The nodes taken if the condition is met
      #   @return [Array<EscalationPathTemplateNodeV2>, nil]
    end
  end
end
