# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    EscalationPathNodeRepeatV2 = Model.define(
      repeat_times: :integer,
      to_node: :string
    )

    class EscalationPathNodeRepeatV2
      # @!attribute [r] repeat_times
      #   How many times to repeat these nodes
      #   @return [Integer, nil]
      # @!attribute [r] to_node
      #   Which node ID we begin repeating from
      #   @return [String, nil]
    end
  end
end
