# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    EscalationPathRetryConfigV2 = Model.define(
      attempts: :integer,
      interval_seconds: :integer
    )

    class EscalationPathRetryConfigV2
      # @!attribute [r] attempts
      #   The total number of times we page this level, counting the initial page
      #   @return [Integer, nil]
      # @!attribute [r] interval_seconds
      #   How long we wait between attempts at this level, in seconds
      #   @return [Integer, nil]
    end
  end
end
