# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] response
    #   @return [String, nil] Whether to acknowledge, decline or snooze the escalation One of: ack, nack, snooze.
    # @!attribute [r] snooze_details
    #   @return [EscalationRespondSnoozeDetailsPayloadV2, nil]
    EscalationsRespondEscalationPayloadV2 = Model.define(
      response: :string,
      snooze_details: -> { EscalationRespondSnoozeDetailsPayloadV2 }
    )
  end
end
