# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    EscalationEventV2 = Model.define(
      channels: [-> { ChatChannelSlimV2 }],
      event: :string,
      id: :string,
      occurred_at: :time,
      urgency: :string,
      users: [-> { UserV2 }]
    )

    class EscalationEventV2
      # @!attribute [r] channels
      #   This field will be populated for notified_channels events
      #   @return [Array<ChatChannelSlimV2>, nil]
      # @!attribute [r] event
      #   The type of event that occured
      #   @return [String, nil]
      # @!attribute [r] id
      #   The unique ID for this escalation event
      #   @return [String, nil]
      # @!attribute [r] occurred_at
      #   The time when this escalation event was processed
      #   @return [Time, nil]
      # @!attribute [r] urgency
      #   The urgency at which we tried to notify users
      #   @return [String, nil]
      # @!attribute [r] users
      #   This field will be populated for notified_users and acked events
      #   @return [Array<UserV2>, nil]
    end
  end
end
