# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] attempts
    #   @return [Integer, nil] The total number of times we page this level, counting the initial page.
    # @!attribute [r] interval_seconds
    #   @return [Integer, nil] How long we wait between attempts at this level, in seconds.
    EscalationPathRetryConfigV2 = Model.define(
      attempts: :integer,
      interval_seconds: :integer
    )
  end
end
