# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] actor
    #   @return [ActorV2, nil]
    # @!attribute [r] escalation
    #   @return [EscalationV2, nil]
    # @!attribute [r] new_status
    #   @return [String, nil] The new status of the escalation One of: pending, triggered, acked, resolved, expired, cancelled, snoozed, delayed, pending_repeat.
    # @!attribute [r] previous_status
    #   @return [String, nil] The previous status of the escalation One of: pending, triggered, acked, resolved, expired, cancelled, snoozed, delayed, pending_repeat.
    EscalationWithStatusChangeV2 = Model.define(
      actor: -> { ActorV2 },
      escalation: -> { EscalationV2 },
      new_status: :string,
      previous_status: :string
    )
  end
end
