# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] description
    #   @return [String, nil] A description of what this template is for.
    # @!attribute [r] expressions
    #   @return [Array<ExpressionPayloadV2>, nil] Expressions backing the template's binding targets.
    # @!attribute [r] name
    #   @return [String, nil] The name of this template, for the user's reference.
    # @!attribute [r] params
    #   @return [Array<EngineParamV2>, nil] The parameters declared by this template, bound per templated path.
    # @!attribute [r] path
    #   @return [Array<EscalationPathTemplateNodePayloadV2>, nil] The nodes that form the levels and branches of this template.
    # @!attribute [r] repeat_config
    #   @return [EscalationPathRepeatConfigV2, nil]
    # @!attribute [r] working_hours
    #   @return [Array<WeekdayIntervalConfigV2>, nil] The working hours for this template.
    EscalationPathTemplatesCreatePayloadV2 = Model.define(
      description: :string,
      expressions: [-> { ExpressionPayloadV2 }],
      name: :string,
      params: [-> { EngineParamV2 }],
      path: [-> { EscalationPathTemplateNodePayloadV2 }],
      repeat_config: -> { EscalationPathRepeatConfigV2 },
      working_hours: [-> { WeekdayIntervalConfigV2 }]
    )
  end
end
