# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] user_ids
    #   @return [Array<String>, nil] The IDs of the users to check response options for
    EscalationsCheckEscalationPermissionsPayloadV2 = Model.define(
      user_ids: [:string]
    )
  end
end
