# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] created_at
    #   @return [Time, nil] When this escalation was created
    # @!attribute [r] creator
    #   @return [EscalationCreatorV2, nil]
    # @!attribute [r] description
    #   @return [String, nil] Additional detail provided with this escalation.
    # @!attribute [r] escalation_path_id
    #   @return [String, nil] Unique identifier of the escalation path that the escalation was created from
    # @!attribute [r] events
    #   @return [Array<EscalationEventV2>, nil] Events which describe the history of this escalation.
    # @!attribute [r] id
    #   @return [String, nil] Unique ID of the escalation
    # @!attribute [r] priority
    #   @return [EscalationPriorityV2, nil]
    # @!attribute [r] related_alerts
    #   @return [Array<AlertSlimV2>, nil] Alerts related to this escalation
    # @!attribute [r] related_incidents
    #   @return [Array<IncidentSlimV2>, nil] Incidents related to this escalation
    # @!attribute [r] status
    #   @return [String, nil] Status of the escalation One of: pending, triggered, acked, resolved, expired, cancelled, snoozed, delayed, pending_repeat.
    # @!attribute [r] title
    #   @return [String, nil] The title of this escalation
    # @!attribute [r] updated_at
    #   @return [Time, nil] When this escalation was last updated
    EscalationV2 = Model.define(
      created_at: :time,
      creator: -> { EscalationCreatorV2 },
      description: :string,
      escalation_path_id: :string,
      events: [-> { EscalationEventV2 }],
      id: :string,
      priority: -> { EscalationPriorityV2 },
      related_alerts: [-> { AlertSlimV2 }],
      related_incidents: [-> { IncidentSlimV2 }],
      status: :string,
      title: :string,
      updated_at: :time
    )
  end
end
