# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ExpressionNavigateOptsPayloadV3 = Model.define(
      reference: :string
    )

    class ExpressionNavigateOptsPayloadV3
      # @!attribute [r] reference
      #   The reference that you want to navigate to
      #   @return [String, nil]
    end
  end
end
