# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] condition_groups
    #   @return [Array<ConditionGroupPayloadV3>, nil] The condition groups to apply in this filter.
    ExpressionFilterOptsPayloadV3 = Model.define(
      condition_groups: [-> { ConditionGroupPayloadV3 }]
    )
  end
end
