# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] branches
    #   @return [ExpressionBranchesOptsV3, nil]
    # @!attribute [r] cast
    #   @return [ExpressionCastOptsV3, nil]
    # @!attribute [r] concatenate
    #   @return [ExpressionConcatenateOptsV3, nil]
    # @!attribute [r] filter
    #   @return [ExpressionFilterOptsV3, nil]
    # @!attribute [r] navigate
    #   @return [ExpressionNavigateOptsV3, nil]
    # @!attribute [r] operation_type
    #   @return [String, nil] The type of the operation One of: navigate, filter, concatenate, count, min, max, sum, random, first, parse, branches, cast.
    # @!attribute [r] parse
    #   @return [ExpressionParseOptsV3, nil]
    # @!attribute [r] returns
    #   @return [ReturnsMetaV3, nil]
    ExpressionOperationV3 = Model.define(
      branches: -> { ExpressionBranchesOptsV3 },
      cast: -> { ExpressionCastOptsV3 },
      concatenate: -> { ExpressionConcatenateOptsV3 },
      filter: -> { ExpressionFilterOptsV3 },
      navigate: -> { ExpressionNavigateOptsV3 },
      operation_type: :string,
      parse: -> { ExpressionParseOptsV3 },
      returns: -> { ReturnsMetaV3 }
    )
  end
end
