# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] else_branch
    #   @return [ExpressionElseBranchPayloadV3, nil]
    # @!attribute [r] label
    #   @return [String, nil] The human readable label of the expression
    # @!attribute [r] operations
    #   @return [Array<ExpressionOperationPayloadV3>, nil]
    # @!attribute [r] reference
    #   @return [String, nil] A short ID that can be used to reference the expression
    # @!attribute [r] root_reference
    #   @return [String, nil] The root reference for this expression (i.e.
    ExpressionPayloadV3 = Model.define(
      else_branch: -> { ExpressionElseBranchPayloadV3 },
      label: :string,
      operations: [-> { ExpressionOperationPayloadV3 }],
      reference: :string,
      root_reference: :string
    )
  end
end
