# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ExpressionParseOptsPayloadV3 = Model.define(
      returns: -> { ReturnsMetaV3 },
      source: :string
    )

    class ExpressionParseOptsPayloadV3
      # @!attribute [r] returns
      #   The returns field
      #   @return [ReturnsMetaV3, nil]
      # @!attribute [r] source
      #   Source expression that is evaluated to a result
      #   @return [String, nil]
    end
  end
end
