# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] reference
    #   @return [String, nil] The reference that you want to navigate to
    ExpressionNavigateOptsPayloadV3 = Model.define(
      reference: :string
    )
  end
end
