# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ExpressionBranchV2 = Model.define(
      condition_groups: [-> { ConditionGroupV2 }],
      result: -> { EngineParamBindingV2 }
    )

    class ExpressionBranchV2
      # @!attribute [r] condition_groups
      #   When one of these condition groups are satisfied, this branch will be evaluated
      #   @return [Array<ConditionGroupV2>, nil]
      # @!attribute [r] result
      #   The result field
      #   @return [EngineParamBindingV2, nil]
    end
  end
end
