# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] branches
    #   @return [Array<ExpressionBranchV2>, nil] The branches to apply for this operation
    # @!attribute [r] returns
    #   @return [ReturnsMetaV2, nil]
    ExpressionBranchesOptsV2 = Model.define(
      branches: [-> { ExpressionBranchV2 }],
      returns: -> { ReturnsMetaV2 }
    )
  end
end
