# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ExpressionPayloadV3 = Model.define(
      else_branch: -> { ExpressionElseBranchPayloadV3 },
      label: :string,
      operations: [-> { ExpressionOperationPayloadV3 }],
      reference: :string,
      root_reference: :string
    )

    class ExpressionPayloadV3
      # @!attribute [r] else_branch
      #   The else_branch field
      #   @return [ExpressionElseBranchPayloadV3, nil]
      # @!attribute [r] label
      #   The human readable label of the expression
      #   @return [String, nil]
      # @!attribute [r] operations
      #   The operations field
      #   @return [Array<ExpressionOperationPayloadV3>, nil]
      # @!attribute [r] reference
      #   A short ID that can be used to reference the expression
      #   @return [String, nil]
      # @!attribute [r] root_reference
      #   The root reference for this expression (i.e
      #   @return [String, nil]
    end
  end
end
