# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] reference
    #   @return [String, nil] The reference within the scope to navigate to
    # @!attribute [r] reference_label
    #   @return [String, nil] The name of the reference to navigate to
    ExpressionNavigateOptsV2 = Model.define(
      reference: :string,
      reference_label: :string
    )
  end
end
