# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ExpressionBranchV3 = Model.define(
      condition_groups: [-> { ConditionGroupV3 }],
      result: -> { EngineParamBindingV3 }
    )

    class ExpressionBranchV3
      # @!attribute [r] condition_groups
      #   When one of these condition groups are satisfied, this branch will be evaluated
      #   @return [Array<ConditionGroupV3>, nil]
      # @!attribute [r] result
      #   The result field
      #   @return [EngineParamBindingV3, nil]
    end
  end
end
