# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ExpressionElseBranchV2 = Model.define(
      result: -> { EngineParamBindingV2 }
    )

    class ExpressionElseBranchV2
      # @!attribute [r] result
      #   The result field
      #   @return [EngineParamBindingV2, nil]
    end
  end
end
