# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] result
    #   @return [EngineParamBindingPayloadV2, nil]
    ExpressionElseBranchPayloadV2 = Model.define(
      result: -> { EngineParamBindingPayloadV2 }
    )
  end
end
