# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] result
    #   @return [EngineParamBindingV2, nil]
    ExpressionElseBranchV2 = Model.define(
      result: -> { EngineParamBindingV2 }
    )
  end
end
