# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] else_branch
    #   @return [ExpressionElseBranchPayloadV2, nil]
    # @!attribute [r] label
    #   @return [String, nil] The human readable label of the expression
    # @!attribute [r] operations
    #   @return [Array<ExpressionOperationPayloadV2>, nil]
    # @!attribute [r] reference
    #   @return [String, nil] A short ID that can be used to reference the expression
    # @!attribute [r] root_reference
    #   @return [String, nil] The root reference for this expression (i.e.
    ExpressionPayloadV2 = Model.define(
      else_branch: -> { ExpressionElseBranchPayloadV2 },
      label: :string,
      operations: [-> { ExpressionOperationPayloadV2 }],
      reference: :string,
      root_reference: :string
    )
  end
end
