# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] condition_groups
    #   @return [Array<ConditionGroupPayloadV3>, nil] When one of these condition groups are satisfied, this branch will be evaluated
    # @!attribute [r] result
    #   @return [EngineParamBindingPayloadV3, nil]
    ExpressionBranchPayloadV3 = Model.define(
      condition_groups: [-> { ConditionGroupPayloadV3 }],
      result: -> { EngineParamBindingPayloadV3 }
    )
  end
end
