# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] assignee_id
    #   @return [String, nil] ID of the user this follow-up is assigned to
    # @!attribute [r] assignee_team_id
    #   @return [String, nil] ID of the team this follow-up is assigned to
    # @!attribute [r] description
    #   @return [String, nil] Description of the follow-up.
    # @!attribute [r] external_issue_reference_id
    #   @return [String, nil] If this follow-up is related to an external issue, the ID of that issue
    # @!attribute [r] follow_up_category_id
    #   @return [String, nil] ID of the category for this follow-up
    # @!attribute [r] follow_up_priority_option_id
    #   @return [String, nil] ID of the priority for this follow-up
    # @!attribute [r] incident_id
    #   @return [String, nil] Unique identifier of the incident the follow-up belongs to
    # @!attribute [r] labels
    #   @return [Array<String>, nil] Labels associated with this follow-up
    # @!attribute [r] title
    #   @return [String, nil] Title of the follow-up
    FollowUpsCreatePayloadV3 = Model.define(
      assignee_id: :string,
      assignee_team_id: :string,
      description: :string,
      external_issue_reference_id: :string,
      follow_up_category_id: :string,
      follow_up_priority_option_id: :string,
      incident_id: :string,
      labels: [:string],
      title: :string
    )
  end
end
