# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] incident_id
    #   @return [String, nil] Unique identifier of the incident the follow-up belongs to
    # @!attribute [r] url
    #   @return [String, nil] URL of the issue in the external provider
    FollowUpsCreateFromLinkPayloadV3 = Model.define(
      incident_id: :string,
      url: :string
    )
  end
end
