# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] provider
    #   @return [String, nil] The issue tracker provider the issue belongs to One of: asana, azure_devops, click_up, freshservice, linear, jira, salesforce, jira_server, github, gitlab, service_now, shortcut, notion.
    # @!attribute [r] url
    #   @return [String, nil] URL of the issue in the external provider
    FollowUpsConnectExternalIssuePayloadV2 = Model.define(
      provider: :string,
      url: :string
    )
  end
end
