# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] reference
    #   @return [String, nil] A reference to a property of the alert to group on
    GroupingKeyV3 = Model.define(
      reference: :string
    )
  end
end
