# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    GroupingSettingsV3 = Model.define(
      ai_enabled: :boolean,
      enabled: :boolean,
      grouping_keys: [-> { GroupingKeyV3 }],
      window_seconds: :integer,
      window_type: :string
    )

    class GroupingSettingsV3
      # @!attribute [r] ai_enabled
      #   Use AI to group similar looking alerts
      #   @return [Boolean, nil]
      # @!attribute [r] enabled
      #   Whether grouping is enabled
      #   @return [Boolean, nil]
      # @!attribute [r] grouping_keys
      #   Which attributes should this alert route use to group alerts?
      #   @return [Array<GroupingKeyV3>, nil]
      # @!attribute [r] window_seconds
      #   How long the grouping window is, in seconds
      #   @return [Integer, nil]
      # @!attribute [r] window_type
      #   Controls how the grouping window behaves
      #   @return [String, nil]
    end
  end
end
