# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IdentityTeamV1 = Model.define(
      id: :string,
      name: :string
    )

    class IdentityTeamV1
      # @!attribute [r] id
      #   Unique identifier for the team
      #   @return [String, nil]
      # @!attribute [r] name
      #   Human readable name of the team
      #   @return [String, nil]
    end
  end
end
