# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] value
    #   @return [Time, nil] The current value of this timestamp, for this incident
    IncidentTimestampValueV2 = Model.define(
      value: :time
    )
  end
end
