# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] description
    #   @return [String, nil] Describes the purpose of the role
    # @!attribute [r] instructions
    #   @return [String, nil] Provided to whoever is nominated for the role.
    # @!attribute [r] name
    #   @return [String, nil] Human readable name of the incident role
    # @!attribute [r] shortform
    #   @return [String, nil] Short human readable name for Slack.
    IncidentRolesUpdatePayloadV2 = Model.define(
      description: :string,
      instructions: :string,
      name: :string,
      shortform: :string
    )
  end
end
