# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] assignee
    #   @return [UserV2, nil]
    # @!attribute [r] role
    #   @return [EmbeddedIncidentRoleV2, nil]
    IncidentRoleAssignmentV2 = Model.define(
      assignee: -> { UserV2 },
      role: -> { EmbeddedIncidentRoleV2 }
    )
  end
end
