# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] incident
    #   @return [IncidentEditPayloadV2, nil]
    # @!attribute [r] notify_incident_channel
    #   @return [Boolean, nil] Should we send Slack channel notifications to inform responders of this update?
    IncidentsEditPayloadV2 = Model.define(
      incident: -> { IncidentEditPayloadV2 },
      notify_incident_channel: :boolean
    )
  end
end
