# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentDurationMetricWithValueV2 = Model.define(
      duration_metric: -> { IncidentDurationMetricV2 },
      status: :string,
      value_seconds: :integer
    )

    class IncidentDurationMetricWithValueV2
      # @!attribute [r] duration_metric
      #   The duration_metric field
      #   @return [IncidentDurationMetricV2, nil]
      # @!attribute [r] status
      #   Whether value_seconds matches this incident's current timestamps ('success'),…
      #   @return [String, nil]
      # @!attribute [r] value_seconds
      #   The duration we last calculated for this metric, omitted if we've never…
      #   @return [Integer, nil]
    end
  end
end
