# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentStatusesCreatePayloadV1 = Model.define(
      category: :string,
      description: :string,
      name: :string,
      rank: :integer
    )

    class IncidentStatusesCreatePayloadV1
      # @!attribute [r] category
      #   Whether the status should be considered 'live' (now renamed to active),…
      #   @return [String, nil]
      # @!attribute [r] description
      #   Rich text description of the incident status
      #   @return [String, nil]
      # @!attribute [r] name
      #   Unique name of this status
      #   @return [String, nil]
      # @!attribute [r] rank
      #   Where this status sits within its category, lowest rank first
      #   @return [Integer, nil]
    end
  end
end
