# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentTemplatesUpdatePayloadV1 = Model.define(
      expressions: [-> { ExpressionPayloadV3 }],
      name: :string,
      template: -> { IncidentTemplateConfigPayloadV1 }
    )

    class IncidentTemplatesUpdatePayloadV1
      # @!attribute [r] expressions
      #   The expressions used by bindings in this template
      #   @return [Array<ExpressionPayloadV3>, nil]
      # @!attribute [r] name
      #   The name of this incident template, for the user's reference
      #   @return [String, nil]
      # @!attribute [r] template
      #   The template field
      #   @return [IncidentTemplateConfigPayloadV1, nil]
    end
  end
end
