# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] duration_metric
    #   @return [IncidentDurationMetricV2, nil]
    # @!attribute [r] status
    #   @return [String, nil] Whether value_seconds matches this incident's current timestamps ('success'), or why it doesn't One of: success, timestamps_missing, calculating, invalid_timestamps.
    # @!attribute [r] value_seconds
    #   @return [Integer, nil] The duration we last calculated for this metric, omitted if we've never calculated one.
    IncidentDurationMetricWithValueV2 = Model.define(
      duration_metric: -> { IncidentDurationMetricV2 },
      status: :string,
      value_seconds: :integer
    )
  end
end
