# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] incident_timestamp_id
    #   @return [String, nil] The id of the incident timestamp that this incident timestamp value is associated with.
    # @!attribute [r] value
    #   @return [Time, nil] The current value of this timestamp, for this incident
    IncidentTimestampValuePayloadV2 = Model.define(
      incident_timestamp_id: :string,
      value: :time
    )
  end
end
