# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentTimelineItemsUpdatePayloadV2 = Model.define(
      description: :string,
      timestamp: :time,
      title: :string
    )

    class IncidentTimelineItemsUpdatePayloadV2
      # @!attribute [r] description
      #   Description of the timeline item, in markdown
      #   @return [String, nil]
      # @!attribute [r] timestamp
      #   When the thing this item describes happened
      #   @return [Time, nil]
      # @!attribute [r] title
      #   Title of the timeline item
      #   @return [String, nil]
    end
  end
end
