# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentMembershipV1 = Model.define(
      created_at: :time,
      id: :string,
      incident_id: :string,
      updated_at: :time,
      user: -> { UserV1 }
    )

    class IncidentMembershipV1
      # @!attribute [r] created_at
      #   When the membership was created
      #   @return [Time, nil]
      # @!attribute [r] id
      #   Unique identifier of this incident membership
      #   @return [String, nil]
      # @!attribute [r] incident_id
      #   Unique identifier of the incident
      #   @return [String, nil]
      # @!attribute [r] updated_at
      #   When the membership was last updated
      #   @return [Time, nil]
      # @!attribute [r] user
      #   The user field
      #   @return [UserV1, nil]
    end
  end
end
