# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentTimestampV2 = Model.define(
      id: :string,
      name: :string,
      rank: :integer
    )

    class IncidentTimestampV2
      # @!attribute [r] id
      #   Unique ID of this incident timestamp
      #   @return [String, nil]
      # @!attribute [r] name
      #   Unique name of this timestamp
      #   @return [String, nil]
      # @!attribute [r] rank
      #   Order in which this timestamp should be shown
      #   @return [Integer, nil]
    end
  end
end
