# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentTimelineItemV2 = Model.define(
      activity_log_id: :string,
      created_at: :time,
      creator: -> { ActorV2 },
      description: :string,
      id: :string,
      incident_id: :string,
      timestamp: :time,
      title: :string,
      updated_at: :time
    )

    # An item on an incident's curated timeline.
    #
    # The timeline is the narrative of an incident, as opposed to the activity log, which records
    # everything that happened. Some of that activity - a pinned message, an escalation, an event a
    # workflow added - is promoted onto the timeline, and those items carry the ID of the activity
    # log entry they came from. The rest are custom, written by hand in the dashboard or through
    # the API, and have no activity_log_id.
    class IncidentTimelineItemV2
      # @!attribute [r] activity_log_id
      #   ID of the activity log entry this item was promoted from
      #   @return [String, nil]
      # @!attribute [r] created_at
      #   When this item was added to the timeline
      #   @return [Time, nil]
      # @!attribute [r] creator
      #   The creator field
      #   @return [ActorV2, nil]
      # @!attribute [r] description
      #   Description of the timeline item, in markdown
      #   @return [String, nil]
      # @!attribute [r] id
      #   Unique identifier of the timeline item
      #   @return [String, nil]
      # @!attribute [r] incident_id
      #   ID of the incident this item belongs to
      #   @return [String, nil]
      # @!attribute [r] timestamp
      #   When the thing this item describes happened
      #   @return [Time, nil]
      # @!attribute [r] title
      #   Title of the timeline item
      #   @return [String, nil]
      # @!attribute [r] updated_at
      #   When this item was last edited
      #   @return [Time, nil]
    end
  end
end
