# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentUpdatesCreatePayloadV2 = Model.define(
      idempotency_key: :string,
      incident_id: :string,
      message: :string,
      to_incident_status_id: :string,
      to_severity_id: :string
    )

    class IncidentUpdatesCreatePayloadV2
      # @!attribute [r] idempotency_key
      #   Unique string used to de-duplicate incident update requests
      #   @return [String, nil]
      # @!attribute [r] incident_id
      #   The incident you want to update
      #   @return [String, nil]
      # @!attribute [r] message
      #   Message that explains the context behind the update, in markdown
      #   @return [String, nil]
      # @!attribute [r] to_incident_status_id
      #   Move the incident to this status
      #   @return [String, nil]
      # @!attribute [r] to_severity_id
      #   Move the incident to this severity
      #   @return [String, nil]
    end
  end
end
