# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentRoleAssignmentV1 = Model.define(
      assignee: -> { UserV1 },
      role: -> { IncidentRoleV1 }
    )

    class IncidentRoleAssignmentV1
      # @!attribute [r] assignee
      #   The assignee field
      #   @return [UserV1, nil]
      # @!attribute [r] role
      #   The role field
      #   @return [IncidentRoleV1, nil]
    end
  end
end
