# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentParticipantV2 = Model.define(
      participant_type: :string,
      user: -> { UserV2 }
    )

    class IncidentParticipantV2
      # @!attribute [r] participant_type
      #   The role they took in the incident One of: observer, collaborator, responder
      #   @return [String, nil]
      # @!attribute [r] user
      #   The user field
      #   @return [UserV2, nil]
    end
  end
end
