# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # One thing that happened on an incident.
    #
    # The activity log records everything. The timeline is the narrative, made of the entries
    # someone promoted onto it and the items they wrote by hand.
    #
    # @!attribute [r] content
    #   @return [IncidentActivityLogContentV2, nil]
    # @!attribute [r] created_at
    #   @return [Time, nil] When we recorded the activity
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier of the activity log entry
    # @!attribute [r] incident_id
    #   @return [String, nil] ID of the incident this happened on.
    # @!attribute [r] occurred_at
    #   @return [Time, nil] When the activity happened.
    # @!attribute [r] title
    #   @return [String, nil] Human-readable summary of what happened
    # @!attribute [r] type
    #   @return [String, nil] What kind of activity this is.
    IncidentActivityLogEntryV2 = Model.define(
      content: -> { IncidentActivityLogContentV2 },
      created_at: :time,
      id: :string,
      incident_id: :string,
      occurred_at: :time,
      title: :string,
      type: :string
    )
  end
end
