# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentTeamMembershipsRevokePayloadV1 = Model.define(
      incident_id: :string,
      team_id: :string
    )

    class IncidentTeamMembershipsRevokePayloadV1
      # @!attribute [r] incident_id
      #   Revoke team access to this incident
      #   @return [String, nil]
      # @!attribute [r] team_id
      #   The team_id field
      #   @return [String, nil]
    end
  end
end
