# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentDurationMetricV2 = Model.define(
      id: :string,
      name: :string
    )

    class IncidentDurationMetricV2
      # @!attribute [r] id
      #   Unique ID of this incident duration metric
      #   @return [String, nil]
      # @!attribute [r] name
      #   Unique name of this duration metric
      #   @return [String, nil]
    end
  end
end
