# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentTemplateBindingPayloadV1 = Model.define(
      binding: -> { EngineParamBindingPayloadV3 }
    )

    class IncidentTemplateBindingPayloadV1
      # @!attribute [r] binding
      #   The binding field
      #   @return [EngineParamBindingPayloadV3, nil]
    end
  end
end
