# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] participant_type
    #   @return [String, nil] The role they took in the incident One of: observer, collaborator, responder.
    # @!attribute [r] user
    #   @return [UserV2, nil]
    IncidentParticipantV2 = Model.define(
      participant_type: :string,
      user: -> { UserV2 }
    )
  end
end
