# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentV1 = Model.define(
      call_url: :string,
      created_at: :time,
      creator: -> { ActorV1 },
      custom_field_entries: [-> { CustomFieldEntryV1 }],
      id: :string,
      incident_role_assignments: [-> { IncidentRoleAssignmentV1 }],
      incident_type: -> { IncidentTypeV1 },
      mode: :string,
      name: :string,
      permalink: :string,
      postmortem_document_url: :string,
      reference: :string,
      severity: -> { SeverityV1 },
      slack_channel_id: :string,
      slack_channel_name: :string,
      slack_team_id: :string,
      status: :string,
      summary: :string,
      timestamps: [-> { IncidentTimestampValueV1 }],
      updated_at: :time,
      visibility: :string
    )

    class IncidentV1
      # @!attribute [r] call_url
      #   The call URL attached to this incident
      #   @return [String, nil]
      # @!attribute [r] created_at
      #   When the incident was created
      #   @return [Time, nil]
      # @!attribute [r] creator
      #   The creator field
      #   @return [ActorV1, nil]
      # @!attribute [r] custom_field_entries
      #   Custom field entries for this incident
      #   @return [Array<CustomFieldEntryV1>, nil]
      # @!attribute [r] id
      #   Unique identifier for the incident
      #   @return [String, nil]
      # @!attribute [r] incident_role_assignments
      #   A list of who is assigned to each role for this incident
      #   @return [Array<IncidentRoleAssignmentV1>, nil]
      # @!attribute [r] incident_type
      #   The incident_type field
      #   @return [IncidentTypeV1, nil]
      # @!attribute [r] mode
      #   Whether the incident is real, a test, a tutorial, or importing as a…
      #   @return [String, nil]
      # @!attribute [r] name
      #   Explanation of the incident
      #   @return [String, nil]
      # @!attribute [r] permalink
      #   A permanent link to the homepage for this incident
      #   @return [String, nil]
      # @!attribute [r] postmortem_document_url
      #   The URL of the incident post-mortem document
      #   @return [String, nil]
      # @!attribute [r] reference
      #   Reference to this incident, as displayed across the product
      #   @return [String, nil]
      # @!attribute [r] severity
      #   The severity field
      #   @return [SeverityV1, nil]
      # @!attribute [r] slack_channel_id
      #   ID of the Slack channel in the organisation Slack workspace
      #   @return [String, nil]
      # @!attribute [r] slack_channel_name
      #   Name of the slack channel
      #   @return [String, nil]
      # @!attribute [r] slack_team_id
      #   ID of the Slack team / workspace
      #   @return [String, nil]
      # @!attribute [r] status
      #   Current status of the incident One of: triage, investigating, fixing,…
      #   @return [String, nil]
      # @!attribute [r] summary
      #   Detailed description of the incident
      #   @return [String, nil]
      # @!attribute [r] timestamps
      #   Incident lifecycle events and when they last occurred
      #   @return [Array<IncidentTimestampValueV1>, nil]
      # @!attribute [r] updated_at
      #   When the incident was last updated
      #   @return [Time, nil]
      # @!attribute [r] visibility
      #   Whether the incident should be open to anyone in your Slack workspace…
      #   @return [String, nil]
    end
  end
end
