# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentRoleAssignmentPayloadV2 = Model.define(
      assignee: -> { UserReferencePayloadV2 },
      incident_role_id: :string
    )

    class IncidentRoleAssignmentPayloadV2
      # @!attribute [r] assignee
      #   The assignee field
      #   @return [UserReferencePayloadV2, nil]
      # @!attribute [r] incident_role_id
      #   Unique ID of an incident role
      #   @return [String, nil]
    end
  end
end
