# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] call_url
    #   @return [String, nil] The call URL attached to this incident
    # @!attribute [r] custom_field_entries
    #   @return [Array<CustomFieldEntryPayloadV2>, nil] Set the incident's custom fields to these values
    # @!attribute [r] incident_role_assignments
    #   @return [Array<IncidentRoleAssignmentPayloadV2>, nil] Assign incident roles to these people
    # @!attribute [r] incident_status_id
    #   @return [String, nil] Incident status to move the incident to.
    # @!attribute [r] incident_timestamp_values
    #   @return [Array<IncidentTimestampValuePayloadV2>, nil] Assign the incident's timestamps to these values
    # @!attribute [r] name
    #   @return [String, nil] Explanation of the incident
    # @!attribute [r] severity_id
    #   @return [String, nil] The ID of the current severity of this incident
    # @!attribute [r] slack_channel_name_override
    #   @return [String, nil] Override the name of the incident Slack channel
    # @!attribute [r] summary
    #   @return [String, nil] Detailed description of the incident
    IncidentEditPayloadV2 = Model.define(
      call_url: :string,
      custom_field_entries: [-> { CustomFieldEntryPayloadV2 }],
      incident_role_assignments: [-> { IncidentRoleAssignmentPayloadV2 }],
      incident_status_id: :string,
      incident_timestamp_values: [-> { IncidentTimestampValuePayloadV2 }],
      name: :string,
      severity_id: :string,
      slack_channel_name_override: :string,
      summary: :string
    )
  end
end
