# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentV2 = Model.define(
      call_url: :string,
      created_at: :time,
      creator: -> { ActorV2 },
      custom_field_entries: [-> { CustomFieldEntryV2 }],
      debriefs: [-> { IncidentDebriefV2 }],
      duration_metrics: [-> { IncidentDurationMetricWithValueV2 }],
      external_issue_reference: -> { ExternalIssueReferenceV2 },
      has_debrief: :boolean,
      id: :string,
      incident_role_assignments: [-> { IncidentRoleAssignmentV2 }],
      incident_status: -> { IncidentStatusV2 },
      incident_timestamp_values: [-> { IncidentTimestampWithValueV2 }],
      incident_type: -> { IncidentTypeV2 },
      last_activity_at: :time,
      mode: :string,
      ms_teams_channel_url: :string,
      name: :string,
      permalink: :string,
      postmortem_document_ids: [:string],
      postmortem_document_url: :string,
      reference: :string,
      severity: -> { SeverityV2 },
      slack_channel_id: :string,
      slack_channel_name: :string,
      slack_channel_url: :string,
      slack_team_id: :string,
      summary: :string,
      team_ids: [:string],
      updated_at: :time,
      visibility: :string,
      workload_minutes_late: :float,
      workload_minutes_sleeping: :float,
      workload_minutes_total: :float,
      workload_minutes_working: :float
    )

    class IncidentV2
      # @!attribute [r] call_url
      #   The call URL attached to this incident
      #   @return [String, nil]
      # @!attribute [r] created_at
      #   When the incident was created
      #   @return [Time, nil]
      # @!attribute [r] creator
      #   The creator field
      #   @return [ActorV2, nil]
      # @!attribute [r] custom_field_entries
      #   Custom field entries for this incident
      #   @return [Array<CustomFieldEntryV2>, nil]
      # @!attribute [r] debriefs
      #   Debriefs scheduled for this incident, ordered by start time
      #   @return [Array<IncidentDebriefV2>, nil]
      # @!attribute [r] duration_metrics
      #   Incident duration metrics and their measurements for this incident
      #   @return [Array<IncidentDurationMetricWithValueV2>, nil]
      # @!attribute [r] external_issue_reference
      #   The external_issue_reference field
      #   @return [ExternalIssueReferenceV2, nil]
      # @!attribute [r] has_debrief
      #   If this incident has a debrief attached
      #   @return [Boolean, nil]
      # @!attribute [r] id
      #   Unique identifier for the incident
      #   @return [String, nil]
      # @!attribute [r] incident_role_assignments
      #   A list of who is assigned to each role for this incident
      #   @return [Array<IncidentRoleAssignmentV2>, nil]
      # @!attribute [r] incident_status
      #   The incident_status field
      #   @return [IncidentStatusV2, nil]
      # @!attribute [r] incident_timestamp_values
      #   Incident lifecycle events and when they occurred
      #   @return [Array<IncidentTimestampWithValueV2>, nil]
      # @!attribute [r] incident_type
      #   The incident_type field
      #   @return [IncidentTypeV2, nil]
      # @!attribute [r] last_activity_at
      #   When the incident last recorded 'activity'
      #   @return [Time, nil]
      # @!attribute [r] mode
      #   Whether the incident is real, a test, a tutorial, or importing as a…
      #   @return [String, nil]
      # @!attribute [r] ms_teams_channel_url
      #   URL to link to the Microsoft Teams channel
      #   @return [String, nil]
      # @!attribute [r] name
      #   Explanation of the incident
      #   @return [String, nil]
      # @!attribute [r] permalink
      #   A permanent link to the homepage for this incident
      #   @return [String, nil]
      # @!attribute [r] postmortem_document_ids
      #   An array of IDs of postmortem documents for this incident
      #   @return [Array<String>, nil]
      # @!attribute [r] postmortem_document_url
      #   The URL of the incident post-mortem document
      #   @return [String, nil]
      # @!attribute [r] reference
      #   Reference to this incident, as displayed across the product
      #   @return [String, nil]
      # @!attribute [r] severity
      #   The severity field
      #   @return [SeverityV2, nil]
      # @!attribute [r] slack_channel_id
      #   ID of the Slack channel in the organisation Slack workspace
      #   @return [String, nil]
      # @!attribute [r] slack_channel_name
      #   Name of the slack channel
      #   @return [String, nil]
      # @!attribute [r] slack_channel_url
      #   URL to link to the slack channel
      #   @return [String, nil]
      # @!attribute [r] slack_team_id
      #   ID of the Slack team / workspace
      #   @return [String, nil]
      # @!attribute [r] summary
      #   Detailed description of the incident
      #   @return [String, nil]
      # @!attribute [r] team_ids
      #   IDs of the teams that own this incident, resolved from your team settings
      #   @return [Array<String>, nil]
      # @!attribute [r] updated_at
      #   When the incident was last updated
      #   @return [Time, nil]
      # @!attribute [r] visibility
      #   Whether the incident should be open to anyone in your Slack workspace…
      #   @return [String, nil]
      # @!attribute [r] workload_minutes_late
      #   Amount of time spent on the incident in late hours
      #   @return [Float, nil]
      # @!attribute [r] workload_minutes_sleeping
      #   Amount of time spent on the incident in sleeping hours
      #   @return [Float, nil]
      # @!attribute [r] workload_minutes_total
      #   Amount of time spent on the incident in total
      #   @return [Float, nil]
      # @!attribute [r] workload_minutes_working
      #   Amount of time spent on the incident in working hours
      #   @return [Float, nil]
    end
  end
end
