# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # A reusable set of values applied to incidents created from alerts.
    #
    # @!attribute [r] created_at
    #   @return [Time, nil] When this incident template was created
    # @!attribute [r] expressions
    #   @return [Array<ExpressionV3>, nil] The expressions used by bindings in this template
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier for this incident template
    # @!attribute [r] name
    #   @return [String, nil] The name of this incident template, for the user's reference
    # @!attribute [r] template
    #   @return [IncidentTemplateConfigV1, nil]
    # @!attribute [r] updated_at
    #   @return [Time, nil] When this incident template was last updated
    IncidentTemplateV1 = Model.define(
      created_at: :time,
      expressions: [-> { ExpressionV3 }],
      id: :string,
      name: :string,
      template: -> { IncidentTemplateConfigV1 },
      updated_at: :time
    )
  end
end
