# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    IncidentSlimV2 = Model.define(
      external_id: :integer,
      id: :string,
      name: :string,
      reference: :string,
      status_category: :string,
      summary: :string,
      visibility: :string
    )

    # Incident slim is a subset of the full incident object, listing key fields.
    class IncidentSlimV2
      # @!attribute [r] external_id
      #   External identifier for the incident - often displayed with an INC- prefix
      #   @return [Integer, nil]
      # @!attribute [r] id
      #   Unique identifier for the incident
      #   @return [String, nil]
      # @!attribute [r] name
      #   Explanation of the incident
      #   @return [String, nil]
      # @!attribute [r] reference
      #   Reference to this incident, as displayed across the product
      #   @return [String, nil]
      # @!attribute [r] status_category
      #   The category of the incidents status One of: triage, declined, merged,…
      #   @return [String, nil]
      # @!attribute [r] summary
      #   Detailed description of the incident
      #   @return [String, nil]
      # @!attribute [r] visibility
      #   Whether the incident should be open to anyone in your Slack workspace…
      #   @return [String, nil]
    end
  end
end
