# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] incident_timestamp
    #   @return [IncidentTimestampV2, nil]
    # @!attribute [r] value
    #   @return [IncidentTimestampValueV2, nil]
    IncidentTimestampWithValueV2 = Model.define(
      incident_timestamp: -> { IncidentTimestampV2 },
      value: -> { IncidentTimestampValueV2 }
    )
  end
end
