# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    MaintenanceWindowNotifyChannelV1 = Model.define(
      channel_id: :string,
      channel_name: :string,
      channel_type: :string,
      is_private: :boolean
    )

    # A channel that will receive notifications about this maintenance window
    class MaintenanceWindowNotifyChannelV1
      # @!attribute [r] channel_id
      #   The external provider channel ID (e.g
      #   @return [String, nil]
      # @!attribute [r] channel_name
      #   Human readable name of the channel
      #   @return [String, nil]
      # @!attribute [r] channel_type
      #   The type of channel (e.g
      #   @return [String, nil]
      # @!attribute [r] is_private
      #   Whether the channel is private
      #   @return [Boolean, nil]
    end
  end
end
