# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    MaintenanceWindowNotifyChannelPayloadV1 = Model.define(
      channel_id: :string,
      channel_name: :string,
      channel_type: :string
    )

    # A channel to receive notifications about this maintenance window
    class MaintenanceWindowNotifyChannelPayloadV1
      # @!attribute [r] channel_id
      #   The external provider channel ID (e.g
      #   @return [String, nil]
      # @!attribute [r] channel_name
      #   Human readable name of the channel
      #   @return [String, nil]
      # @!attribute [r] channel_type
      #   The type of channel (e.g
      #   @return [String, nil]
    end
  end
end
