# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    OnCallNotificationRulePhoneDetailsPublicV2 = Model.define(
      channel: :string
    )

    class OnCallNotificationRulePhoneDetailsPublicV2
      # @!attribute [r] channel
      #   Which channel of a phone notification method this rule uses
      #   @return [String, nil]
    end
  end
end
