# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] address
    #   @return [String, nil] The address of this method (e.g.
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier for this notification method
    # @!attribute [r] is_usable
    #   @return [Boolean, nil] Whether this method is ready to receive notifications.
    # @!attribute [r] method_type
    #   @return [String, nil] The high-level type of notification method.
    # @!attribute [r] phone_details
    #   @return [OnCallNotificationMethodPhoneDetailsPublicV2, nil]
    OnCallNotificationMethodPublicV2 = Model.define(
      address: :string,
      id: :string,
      is_usable: :boolean,
      method_type: :string,
      phone_details: -> { OnCallNotificationMethodPhoneDetailsPublicV2 }
    )
  end
end
