# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    OnCallNotificationRuleMethodTargetPublicV2 = Model.define(
      all: -> { OnCallNotificationRuleMethodTargetAllPublicV2 },
      specific: -> { OnCallNotificationRuleMethodTargetSpecificPublicV2 },
      type: :string
    )

    class OnCallNotificationRuleMethodTargetPublicV2
      # @!attribute [r] all
      #   The all field
      #   @return [OnCallNotificationRuleMethodTargetAllPublicV2, nil]
      # @!attribute [r] specific
      #   The specific field
      #   @return [OnCallNotificationRuleMethodTargetSpecificPublicV2, nil]
      # @!attribute [r] type
      #   Whether this targets a specific method or all methods of a given type
      #   @return [String, nil]
    end
  end
end
