# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PayReportsPublishPayloadV2 = Model.define(
      cc_emails: [:string],
      send_user_breakdowns: :string
    )

    class PayReportsPublishPayloadV2
      # @!attribute [r] cc_emails
      #   Email addresses to send a copy of the report to
      #   @return [Array<String>, nil]
      # @!attribute [r] send_user_breakdowns
      #   Whether each user in the report is emailed their own pay breakdown One of:…
      #   @return [String, nil]
    end
  end
end
