# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PayReportRotationFilterV2 = Model.define(
      rotation_ids: [:string],
      schedule_id: :string
    )

    # Narrows one of a report's schedules to some of its rotations.
    class PayReportRotationFilterV2
      # @!attribute [r] rotation_ids
      #   Which of the schedule's rotations to include
      #   @return [Array<String>, nil]
      # @!attribute [r] schedule_id
      #   The schedule to narrow
      #   @return [String, nil]
    end
  end
end
