# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PayReportsUnpublishPayloadV2 = Model.define(
      unpublish_reason: :string
    )

    class PayReportsUnpublishPayloadV2
      # @!attribute [r] unpublish_reason
      #   Why this report is being unpublished
      #   @return [String, nil]
    end
  end
end
