# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PayConfigOneOffRulePayloadV2 = Model.define(
      end_at: :time,
      id: :string,
      name: :string,
      rate_cents: :integer,
      start_at: :time
    )

    # A one-off rule to write. Send an existing rule's ID to keep it stable, and omit it for a rule you are adding.
    class PayConfigOneOffRulePayloadV2
      # @!attribute [r] end_at
      #   When this rule stops applying
      #   @return [Time, nil]
      # @!attribute [r] id
      #   An existing rule's ID, to keep it stable
      #   @return [String, nil]
      # @!attribute [r] name
      #   Human readable name for this rule
      #   @return [String, nil]
      # @!attribute [r] rate_cents
      #   Rate paid while this rule applies, in the lowest denomination of the config's…
      #   @return [Integer, nil]
      # @!attribute [r] start_at
      #   When this rule starts applying
      #   @return [Time, nil]
    end
  end
end
