# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PayReportV2 = Model.define(
      created_at: :time,
      creator: -> { ActorV2 },
      end_date: :string,
      error_code: :string,
      error_message: :string,
      id: :string,
      name: :string,
      overlapping_shifts: :string,
      published_at: :time,
      schedule_ids: [:string],
      start_date: :string,
      status: :string,
      total_duration_seconds: :integer,
      total_pay_by_currency: Model.map_of(:integer),
      unpaid_shifts: :string,
      updated_at: :time
    )

    # A pay report values the time a set of users spent on-call over a date window, using the rates from a pay config.
    #
    # This is a summary: the headline totals, and the parameters the report was generated
    # with. The shifts behind those totals, and the per-user and per-schedule breakdowns, come
    # from downloading the report as CSV.
    #
    # Reports are immutable snapshots: once generated, changing the pay config or the
    # schedules behind it will not change the report. Generate a new one instead.
    #
    # A report starts as a draft and becomes visible to everyone in your organisation when
    # you publish it.
    #
    # Reports are generated in the background, so a report you have just asked for has no
    # totals yet. Its status says whether they are still coming, and a report that failed
    # carries the reason it will never have them.
    class PayReportV2
      # @!attribute [r] created_at
      #   When this report was created
      #   @return [Time, nil]
      # @!attribute [r] creator
      #   The creator field
      #   @return [ActorV2, nil]
      # @!attribute [r] end_date
      #   Last date (YYYY-MM-DD) this report includes shifts from, inclusive
      #   @return [String, nil]
      # @!attribute [r] error_code
      #   Why a report could not be generated One of: invalid_request, timed_out
      #   @return [String, nil]
      # @!attribute [r] error_message
      #   What went wrong, written for whoever asked for the report
      #   @return [String, nil]
      # @!attribute [r] id
      #   Unique identifier for this pay report
      #   @return [String, nil]
      # @!attribute [r] name
      #   Human readable name for this report
      #   @return [String, nil]
      # @!attribute [r] overlapping_shifts
      #   How time spent on more than one schedule at once was paid One of: paid_once,…
      #   @return [String, nil]
      # @!attribute [r] published_at
      #   When this report was published
      #   @return [Time, nil]
      # @!attribute [r] schedule_ids
      #   The schedules this report covers
      #   @return [Array<String>, nil]
      # @!attribute [r] start_date
      #   First date (YYYY-MM-DD) this report includes shifts from, inclusive
      #   @return [String, nil]
      # @!attribute [r] status
      #   How far a report has got through being generated One of: pending, generating,…
      #   @return [String, nil]
      # @!attribute [r] total_duration_seconds
      #   Total time spent on-call across every shift in this report, in seconds
      #   @return [Integer, nil]
      # @!attribute [r] total_pay_by_currency
      #   Total owed for this report, keyed by ISO 4217 currency code, in the lowest…
      #   @return [Hash{String => Integer}, nil]
      # @!attribute [r] unpaid_shifts
      #   Whether shifts that priced to zero are part of the report One of: included,…
      #   @return [String, nil]
      # @!attribute [r] updated_at
      #   When this report was last updated
      #   @return [Time, nil]
    end
  end
end
