# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # Set when policy_type is vacation_conflict. Someone is on call while on holiday.
    #
    # @!attribute [r] end_at
    #   @return [Time, nil] When the conflict ends
    # @!attribute [r] holiday_name
    #   @return [String, nil] What the holiday is called in the external system
    # @!attribute [r] rotation_id
    #   @return [String, nil] The rotation the holiday conflicts with
    # @!attribute [r] schedule_id
    #   @return [String, nil] The schedule the holiday conflicts with
    # @!attribute [r] start_at
    #   @return [Time, nil] When the conflict starts
    # @!attribute [r] user_id
    #   @return [String, nil] The user on holiday
    PolicyFindingVacationConflictV2 = Model.define(
      end_at: :time,
      holiday_name: :string,
      rotation_id: :string,
      schedule_id: :string,
      start_at: :time,
      user_id: :string
    )
  end
end
