# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # Set when policy_type is debrief.
    #
    # @!attribute [r] due_date_config
    #   @return [PolicyDueDateConfigPayloadV2, nil]
    # @!attribute [r] requirements
    #   @return [Array<ConditionGroupPayloadV2>, nil] Conditions a debrief must satisfy to be compliant
    # @!attribute [r] run_on_private_incidents
    #   @return [Boolean, nil] Requires the policies.run_on_private scope
    PolicyDebriefPayloadV2 = Model.define(
      due_date_config: -> { PolicyDueDateConfigPayloadV2 },
      requirements: [-> { ConditionGroupPayloadV2 }],
      run_on_private_incidents: :boolean
    )
  end
end
