# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] bindings
    #   @return [Array<EngineParamBindingV2>, nil] Bindings which define the user to be assigned.
    # @!attribute [r] reminder_cadence_after
    #   @return [PolicyReminderCadenceV2, nil]
    # @!attribute [r] reminder_cadence_before
    #   @return [PolicyReminderCadenceV2, nil]
    # @!attribute [r] reminder_detected_date_offset_hours
    #   @return [Array<Integer>, nil] List of hours relative to when the finding was detected to remind the assignee.
    # @!attribute [r] reminder_due_date_offset_hours
    #   @return [Array<Integer>, nil] List of hours relative to the due date to remind the assignee.
    PolicyAssignmentRulesV2 = Model.define(
      bindings: [-> { EngineParamBindingV2 }],
      reminder_cadence_after: -> { PolicyReminderCadenceV2 },
      reminder_cadence_before: -> { PolicyReminderCadenceV2 },
      reminder_detected_date_offset_hours: [:integer],
      reminder_due_date_offset_hours: [:integer]
    )
  end
end
