# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PolicyPostMortemV2 = Model.define(
      due_date_config: -> { PolicyDueDateConfigV2 },
      requirements: [-> { ConditionGroupV2 }],
      run_on_private_incidents: :boolean
    )

    # Set when policy_type is post_mortem.
    class PolicyPostMortemV2
      # @!attribute [r] due_date_config
      #   The due_date_config field
      #   @return [PolicyDueDateConfigV2, nil]
      # @!attribute [r] requirements
      #   Conditions a post-mortem must satisfy to be compliant
      #   @return [Array<ConditionGroupV2>, nil]
      # @!attribute [r] run_on_private_incidents
      #   Requires the policies.run_on_private scope
      #   @return [Boolean, nil]
    end
  end
end
