# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PolicyDueDateConfigPayloadV2 = Model.define(
      applies_from: :time,
      calculation_timezone: :string,
      calculation_type: :string,
      days: -> { EngineParamBindingPayloadV2 },
      incident_timestamp_id: :string
    )

    class PolicyDueDateConfigPayloadV2
      # @!attribute [r] applies_from
      #   If set, the policy only applies to resources from this timestamp onwards
      #   @return [Time, nil]
      # @!attribute [r] calculation_timezone
      #   Timezone the due date is calculated in
      #   @return [String, nil]
      # @!attribute [r] calculation_type
      #   One of: seven_days, weekdays
      #   @return [String, nil]
      # @!attribute [r] days
      #   The days field
      #   @return [EngineParamBindingPayloadV2, nil]
      # @!attribute [r] incident_timestamp_id
      #   Timestamp the due date counts from
      #   @return [String, nil]
    end
  end
end
