# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # Set when policy_type is follow_up.
    #
    # @!attribute [r] follow_up_id
    #   @return [String, nil] The follow-up that fell short of the policy
    # @!attribute [r] incident_id
    #   @return [String, nil] The incident the follow-up belongs to
    PolicyFindingFollowUpV2 = Model.define(
      follow_up_id: :string,
      incident_id: :string
    )
  end
end
