# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PolicyV2 = Model.define(
      assignment_rules: -> { PolicyAssignmentRulesV2 },
      conditions: [-> { ConditionGroupV2 }],
      created_at: :time,
      debrief: -> { PolicyDebriefV2 },
      description: :string,
      expressions: [-> { ExpressionV2 }],
      follow_up: -> { PolicyFollowUpV2 },
      id: :string,
      name: :string,
      on_call_readiness: -> { PolicyOnCallReadinessV2 },
      policy_type: :string,
      post_mortem: -> { PolicyPostMortemV2 },
      schedule: -> { PolicyScheduleV2 },
      status: :string,
      updated_at: :time
    )

    class PolicyV2
      # @!attribute [r] assignment_rules
      #   The assignment_rules field
      #   @return [PolicyAssignmentRulesV2, nil]
      # @!attribute [r] conditions
      #   Conditions which determine which resources are in scope for this policy
      #   @return [Array<ConditionGroupV2>, nil]
      # @!attribute [r] created_at
      #   The created_at field
      #   @return [Time, nil]
      # @!attribute [r] debrief
      #   The debrief field
      #   @return [PolicyDebriefV2, nil]
      # @!attribute [r] description
      #   Human readable description of the policy
      #   @return [String, nil]
      # @!attribute [r] expressions
      #   The expressions relating to this policy
      #   @return [Array<ExpressionV2>, nil]
      # @!attribute [r] follow_up
      #   The follow_up field
      #   @return [PolicyFollowUpV2, nil]
      # @!attribute [r] id
      #   Unique ID of the policy
      #   @return [String, nil]
      # @!attribute [r] name
      #   Human readable name of the policy
      #   @return [String, nil]
      # @!attribute [r] on_call_readiness
      #   The on_call_readiness field
      #   @return [PolicyOnCallReadinessV2, nil]
      # @!attribute [r] policy_type
      #   Type of the policy, specifying what this applies to One of: debrief,…
      #   @return [String, nil]
      # @!attribute [r] post_mortem
      #   The post_mortem field
      #   @return [PolicyPostMortemV2, nil]
      # @!attribute [r] schedule
      #   The schedule field
      #   @return [PolicyScheduleV2, nil]
      # @!attribute [r] status
      #   Disabled policies stop evaluating but keep their config One of: enabled,…
      #   @return [String, nil]
      # @!attribute [r] updated_at
      #   The updated_at field
      #   @return [Time, nil]
    end
  end
end
