# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # Set when policy_type is on_call_readiness. The assignee is always the user the finding is about and cannot be configured.
    #
    # @!attribute [r] enforcement
    #   @return [String, nil] advisory reports only; blocking also prevents users saving non-compliant notification rules.
    # @!attribute [r] high_urgency
    #   @return [Array<PolicyReadinessRuleV2>, nil]
    # @!attribute [r] low_urgency
    #   @return [Array<PolicyReadinessRuleV2>, nil]
    PolicyOnCallReadinessV2 = Model.define(
      enforcement: :string,
      high_urgency: [-> { PolicyReadinessRuleV2 }],
      low_urgency: [-> { PolicyReadinessRuleV2 }]
    )
  end
end
