# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] dismissed_at
    #   @return [Time, nil]
    # @!attribute [r] dismissed_by
    #   @return [ActorV2, nil]
    # @!attribute [r] reason
    #   @return [String, nil] Why it was dismissed
    PolicyFindingDismissalV2 = Model.define(
      dismissed_at: :time,
      dismissed_by: -> { ActorV2 },
      reason: :string
    )
  end
end
