# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PolicyScheduleV2 = Model.define(
      evaluation_level: :string,
      requirement_type: :string
    )

    # Detects gaps in on-call coverage. Set when policy_type is schedule.
    class PolicyScheduleV2
      # @!attribute [r] evaluation_level
      #   Evaluate coverage across the whole schedule, or per rotation
      #   @return [String, nil]
      # @!attribute [r] requirement_type
      #   One of: contiguous
      #   @return [String, nil]
    end
  end
end
