# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PolicyFindingPostMortemV2 = Model.define(
      incident_id: :string
    )

    # Set when policy_type is post_mortem.
    class PolicyFindingPostMortemV2
      # @!attribute [r] incident_id
      #   The incident whose post-mortem fell short of the policy
      #   @return [String, nil]
    end
  end
end
