# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PolicyReadinessRuleV2 = Model.define(
      max_delay_seconds: :integer,
      method_types: [:string]
    )

    class PolicyReadinessRuleV2
      # @!attribute [r] max_delay_seconds
      #   How quickly the method must fire to count
      #   @return [Integer, nil]
      # @!attribute [r] method_types
      #   One of: slack, email, app, sms, phone, live_call, slack_channel,…
      #   @return [Array<String>, nil]
    end
  end
end
