# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] created_at
    #   @return [Time, nil]
    # @!attribute [r] days
    #   @return [Integer, nil] Days outside the policy's due date
    # @!attribute [r] debrief
    #   @return [PolicyFindingDebriefV2, nil]
    # @!attribute [r] dismissal
    #   @return [PolicyFindingDismissalV2, nil]
    # @!attribute [r] due_at
    #   @return [Time, nil] When this finding becomes overdue
    # @!attribute [r] follow_up
    #   @return [PolicyFindingFollowUpV2, nil]
    # @!attribute [r] id
    #   @return [String, nil] Unique ID of the finding
    # @!attribute [r] last_checked_at
    #   @return [Time, nil] When this finding was last re-evaluated
    # @!attribute [r] on_call_readiness
    #   @return [PolicyFindingOnCallReadinessV2, nil]
    # @!attribute [r] policy_id
    #   @return [String, nil] The policy this finding was raised against
    # @!attribute [r] policy_type
    #   @return [String, nil] Type of the policy this finding was raised against One of: debrief, follow_up, on_call_readiness, post_mortem, schedule, shift_conflict, vacation_conflict.
    # @!attribute [r] post_mortem
    #   @return [PolicyFindingPostMortemV2, nil]
    # @!attribute [r] responsible_users
    #   @return [Array<UserV2>, nil] Who is expected to resolve this finding
    # @!attribute [r] schedule
    #   @return [PolicyFindingScheduleV2, nil]
    # @!attribute [r] state
    #   @return [String, nil] Where this finding is in its lifecycle One of: pending, active, resolved, cancelled, dismissed.
    # @!attribute [r] updated_at
    #   @return [Time, nil]
    # @!attribute [r] vacation_conflict
    #   @return [PolicyFindingVacationConflictV2, nil]
    PolicyFindingV2 = Model.define(
      created_at: :time,
      days: :integer,
      debrief: -> { PolicyFindingDebriefV2 },
      dismissal: -> { PolicyFindingDismissalV2 },
      due_at: :time,
      follow_up: -> { PolicyFindingFollowUpV2 },
      id: :string,
      last_checked_at: :time,
      on_call_readiness: -> { PolicyFindingOnCallReadinessV2 },
      policy_id: :string,
      policy_type: :string,
      post_mortem: -> { PolicyFindingPostMortemV2 },
      responsible_users: [-> { UserV2 }],
      schedule: -> { PolicyFindingScheduleV2 },
      state: :string,
      updated_at: :time,
      vacation_conflict: -> { PolicyFindingVacationConflictV2 }
    )
  end
end
