# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] assignment_rules
    #   @return [PolicyAssignmentRulesPayloadV2, nil]
    # @!attribute [r] conditions
    #   @return [Array<ConditionGroupPayloadV2>, nil] Conditions which determine which resources are in scope for this policy
    # @!attribute [r] debrief
    #   @return [PolicyDebriefPayloadV2, nil]
    # @!attribute [r] description
    #   @return [String, nil] Human readable description of the policy
    # @!attribute [r] expressions
    #   @return [Array<ExpressionPayloadV2>, nil] The expressions to use in this policy
    # @!attribute [r] follow_up
    #   @return [PolicyFollowUpPayloadV2, nil]
    # @!attribute [r] name
    #   @return [String, nil] Human readable name of the policy
    # @!attribute [r] on_call_readiness
    #   @return [PolicyOnCallReadinessV2, nil]
    # @!attribute [r] policy_type
    #   @return [String, nil] Type of the policy, specifying what this applies to.
    # @!attribute [r] post_mortem
    #   @return [PolicyPostMortemPayloadV2, nil]
    # @!attribute [r] schedule
    #   @return [PolicyScheduleV2, nil]
    # @!attribute [r] status
    #   @return [String, nil] Defaults to enabled on create.
    PoliciesCreatePayloadV2 = Model.define(
      assignment_rules: -> { PolicyAssignmentRulesPayloadV2 },
      conditions: [-> { ConditionGroupPayloadV2 }],
      debrief: -> { PolicyDebriefPayloadV2 },
      description: :string,
      expressions: [-> { ExpressionPayloadV2 }],
      follow_up: -> { PolicyFollowUpPayloadV2 },
      name: :string,
      on_call_readiness: -> { PolicyOnCallReadinessV2 },
      policy_type: :string,
      post_mortem: -> { PolicyPostMortemPayloadV2 },
      schedule: -> { PolicyScheduleV2 },
      status: :string
    )
  end
end
