# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    PostmortemDocumentsUpdateStatusPayloadV1 = Model.define(
      status: :string
    )

    class PostmortemDocumentsUpdateStatusPayloadV1
      # @!attribute [r] status
      #   The new status to set the post-mortem document to One of: in_progress,…
      #   @return [String, nil]
    end
  end
end
