# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    RetrospectiveIncidentOptionsV2 = Model.define(
      external_id: :integer,
      postmortem_document_url: :string,
      slack_channel_id: :string
    )

    class RetrospectiveIncidentOptionsV2
      # @!attribute [r] external_id
      #   The external ID (e.g
      #   @return [Integer, nil]
      # @!attribute [r] postmortem_document_url
      #   The URL of the postmortem, if there is one
      #   @return [String, nil]
      # @!attribute [r] slack_channel_id
      #   Pass the ID of a Slack channel to attach the incident to an existing channel
      #   @return [String, nil]
    end
  end
end
