# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] array
    #   @return [Boolean, nil] Whether the return value should be single or multi-value
    # @!attribute [r] type
    #   @return [String, nil] Expected return type of this expression (what to try casting the result to)
    ReturnsMetaV2 = Model.define(
      array: :boolean,
      type: :string
    )
  end
end
