# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ScheduleLayerV2 = Model.define(
      id: :string,
      name: :string
    )

    class ScheduleLayerV2
      # @!attribute [r] id
      #   Unique identifier of the layer
      #   @return [String, nil]
      # @!attribute [r] name
      #   Name of the layer
      #   @return [String, nil]
    end
  end
end
