# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] end_at
    #   @return [Time, nil] End time of the override
    # @!attribute [r] layer_id
    #   @return [String, nil] The layer this override applies to
    # @!attribute [r] rotation_id
    #   @return [String, nil] The rotation this override applies to
    # @!attribute [r] schedule_id
    #   @return [String, nil] The schedule this override applies to
    # @!attribute [r] start_at
    #   @return [Time, nil] Start time of the override
    # @!attribute [r] user
    #   @return [UserReferencePayloadV2, nil]
    SchedulesCreateOverridePayloadV2 = Model.define(
      end_at: :time,
      layer_id: :string,
      rotation_id: :string,
      schedule_id: :string,
      start_at: :time,
      user: -> { UserReferencePayloadV2 }
    )
  end
end
