# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] annotations
    #   @return [Hash{String => String}, nil] Annotations that track metadata about this resource
    # @!attribute [r] config
    #   @return [ScheduleConfigV2, nil]
    # @!attribute [r] created_at
    #   @return [Time, nil]
    # @!attribute [r] current_shifts
    #   @return [Array<ScheduleEntryV2>, nil] Shifts that are ongoing for this schedule
    # @!attribute [r] holidays_public_config
    #   @return [ScheduleHolidaysPublicConfigV2, nil]
    # @!attribute [r] id
    #   @return [String, nil] Unique internal ID of the schedule
    # @!attribute [r] name
    #   @return [String, nil] Human readable name synced from external provider
    # @!attribute [r] next_shifts
    #   @return [Array<ScheduleEntryV2>, nil] The shifts after the next changeover.
    # @!attribute [r] permalink
    #   @return [String, nil] A permanent link to this schedule in the incident.io dashboard
    # @!attribute [r] team_ids
    #   @return [Array<String>, nil] IDs of teams that own this schedule
    # @!attribute [r] timezone
    #   @return [String, nil] Timezone of the schedule, as interpreted at the point of generating the report
    # @!attribute [r] updated_at
    #   @return [Time, nil]
    ScheduleV2 = Model.define(
      annotations: Model.map_of(:string),
      config: -> { ScheduleConfigV2 },
      created_at: :time,
      current_shifts: [-> { ScheduleEntryV2 }],
      holidays_public_config: -> { ScheduleHolidaysPublicConfigV2 },
      id: :string,
      name: :string,
      next_shifts: [-> { ScheduleEntryV2 }],
      permalink: :string,
      team_ids: [:string],
      timezone: :string,
      updated_at: :time
    )
  end
end
