# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ScheduleSyncTargetResourceV2 = Model.define(
      add_bot_to_group: :boolean,
      created_at: :time,
      id: :string,
      linked_schedules: [-> { LinkedScheduleV2 }],
      slack_team_id: :string,
      slack_user_group_id: :string,
      updated_at: :time
    )

    # A sync target is the link between incident.io and a single Slack user group,
    # used to keep that group's membership in step with who is currently on call.
    #
    # A target identifies the group by its Slack user group ID and Slack team ID,
    # and remembers whether the incident.io bot should be added to the group so it
    # can manage membership. On its own a target does nothing: you link it to a
    # schedule by creating a schedule sync rule (see the Schedules service), and
    # that rule decides which schedule members flow into the group. As the
    # schedule's shifts change hands, we update the Slack user group to match.
    #
    # A single target can be referenced by sync rules on several schedules at once;
    # linked_schedules lists every schedule with an active rule pointing at it.
    class ScheduleSyncTargetResourceV2
      # @!attribute [r] add_bot_to_group
      #   Whether the incident.io bot should be added to the group as a member
      #   @return [Boolean, nil]
      # @!attribute [r] created_at
      #   The created_at field
      #   @return [Time, nil]
      # @!attribute [r] id
      #   Unique identifier of the sync target
      #   @return [String, nil]
      # @!attribute [r] linked_schedules
      #   Schedules with an active sync rule pointing at this target
      #   @return [Array<LinkedScheduleV2>, nil]
      # @!attribute [r] slack_team_id
      #   Slack team (workspace) ID the user group lives in
      #   @return [String, nil]
      # @!attribute [r] slack_user_group_id
      #   Slack ID of the user group whose membership is kept in sync
      #   @return [String, nil]
      # @!attribute [r] updated_at
      #   The updated_at field
      #   @return [Time, nil]
    end
  end
end
