# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] add_bot_to_group
    #   @return [Boolean, nil] Whether the incident.io bot should be added to the group
    # @!attribute [r] annotations
    #   @return [Hash{String => String}, nil] Annotations that track metadata about this resource
    ScheduleSyncTargetsUpdatePayloadV2 = Model.define(
      add_bot_to_group: :boolean,
      annotations: Model.map_of(:string)
    )
  end
end
