# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] rotations
    #   @return [Array<ScheduleRotationCreatePayloadV2>, nil]
    ScheduleConfigCreatePayloadV2 = Model.define(
      rotations: [-> { ScheduleRotationCreatePayloadV2 }]
    )
  end
end
