# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] schedule
    #   @return [ScheduleUpdatePayloadV2, nil]
    SchedulesUpdatePayloadV2 = Model.define(
      schedule: -> { ScheduleUpdatePayloadV2 }
    )
  end
end
