# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    SchedulesCreateScheduleReplicaPayloadV2 = Model.define(
      schedule_replica: -> { ScheduleReplicaCreatePayloadV2 }
    )

    class SchedulesCreateScheduleReplicaPayloadV2
      # @!attribute [r] schedule_replica
      #   The schedule_replica field
      #   @return [ScheduleReplicaCreatePayloadV2, nil]
    end
  end
end
