# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # The schedule entries for a window of time, grouped by where they come from.
    #
    # `scheduled` are the entries produced by the schedule's rotation rules before
    # any overrides are taken into account. `overrides` are the one-off changes that
    # apply within the window. `final` is the effective schedule after overrides
    # have been merged in — this is normally the list to use when working out who
    # is on-call.
    #
    # @!attribute [r] final
    #   @return [Array<ScheduleEntryV2>, nil] The effective schedule after overrides have been merged in
    # @!attribute [r] overrides
    #   @return [Array<ScheduleEntryV2>, nil] Overrides that apply within the requested window
    # @!attribute [r] scheduled
    #   @return [Array<ScheduleEntryV2>, nil] Entries from the schedule's rotation rules, before overrides are applied
    ScheduleEntriesListPayloadV2 = Model.define(
      final: [-> { ScheduleEntryV2 }],
      overrides: [-> { ScheduleEntryV2 }],
      scheduled: [-> { ScheduleEntryV2 }]
    )
  end
end
