# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] rotations
    #   @return [Array<ScheduleRotationV2>, nil] Rotas in this schedule
    ScheduleConfigV2 = Model.define(
      rotations: [-> { ScheduleRotationV2 }]
    )
  end
end
