# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] annotations
    #   @return [Hash{String => String}, nil] Annotations that track metadata about this resource
    # @!attribute [r] permanent_member_user_ids
    #   @return [Array<String>, nil] IDs of users to always keep in the Slack user group, regardless of who is on call.
    # @!attribute [r] sync_type
    #   @return [String, nil] Which schedule members sync to the user group One of: on_call, all_users, next_on_call.
    SchedulesUpdateScheduleSyncRulePayloadV2 = Model.define(
      annotations: Model.map_of(:string),
      permanent_member_user_ids: [:string],
      sync_type: :string
    )
  end
end
