# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    ScheduleConfigCreatePayloadV2 = Model.define(
      rotations: [-> { ScheduleRotationCreatePayloadV2 }]
    )

    class ScheduleConfigCreatePayloadV2
      # @!attribute [r] rotations
      #   The rotations field
      #   @return [Array<ScheduleRotationCreatePayloadV2>, nil]
    end
  end
end
