# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    SecretsRotatePayloadV2 = Model.define(
      value: :string
    )

    class SecretsRotatePayloadV2
      # @!attribute [r] value
      #   The secret's new plaintext value
      #   @return [String, nil]
    end
  end
end
