# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] description
    #   @return [String, nil] Optional description of what this secret is for
    # @!attribute [r] name
    #   @return [String, nil] Human-readable name, unique within the organisation amongst unarchived secrets
    # @!attribute [r] owning_team_ids
    #   @return [Array<String>, nil] IDs of the teams that own this secret.
    SecretsUpdatePayloadV2 = Model.define(
      description: :string,
      name: :string,
      owning_team_ids: [:string]
    )
  end
end
