# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] description
    #   @return [String, nil] Description of the severity
    # @!attribute [r] name
    #   @return [String, nil] Human readable name of the severity
    # @!attribute [r] rank
    #   @return [Integer, nil] Rank to help sort severities (lower numbers are less severe)
    SeveritiesCreatePayloadV1 = Model.define(
      description: :string,
      name: :string,
      rank: :integer
    )
  end
end
