# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StatusPagesUpdateStatusPageMaintenancePayloadV2 = Model.define(
      end_at: :time,
      name: :string,
      start_at: :time
    )

    class StatusPagesUpdateStatusPageMaintenancePayloadV2
      # @!attribute [r] end_at
      #   The time the maintenance window ends
      #   @return [Time, nil]
      # @!attribute [r] name
      #   A title for the maintenance window
      #   @return [String, nil]
      # @!attribute [r] start_at
      #   The time the maintenance window starts
      #   @return [Time, nil]
    end
  end
end
