# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] component_statuses
    #   @return [Array<StatusPageIncidentAffectedComponentV2>, nil] An array of mappings from component ID to current component status
    # @!attribute [r] idempotency_key
    #   @return [String, nil] A unique key to de-duplicate requests.
    # @!attribute [r] incident_status
    #   @return [String, nil] Current status for this status page incident One of: investigating, identified, monitoring, resolved.
    # @!attribute [r] message
    #   @return [String, nil] Markdown initial update on this status page incident
    # @!attribute [r] name
    #   @return [String, nil] A title for the incident
    # @!attribute [r] notify_subscribers
    #   @return [Boolean, nil] Whether to notify subscribers about this status page incident.
    # @!attribute [r] status_page_id
    #   @return [String, nil] ID of the status page.
    StatusPagesCreateStatusPageIncidentPayloadV2 = Model.define(
      component_statuses: [-> { StatusPageIncidentAffectedComponentV2 }],
      idempotency_key: :string,
      incident_status: :string,
      message: :string,
      name: :string,
      notify_subscribers: :boolean,
      status_page_id: :string
    )
  end
end
