# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StatusPageV2 = Model.define(
      description: :string,
      id: :string,
      name: :string,
      public_url: :string
    )

    class StatusPageV2
      # @!attribute [r] description
      #   The description of this status page
      #   @return [String, nil]
      # @!attribute [r] id
      #   Unique ID of this status page
      #   @return [String, nil]
      # @!attribute [r] name
      #   The title of this status page
      #   @return [String, nil]
      # @!attribute [r] public_url
      #   The public URL of this status page
      #   @return [String, nil]
    end
  end
end
