# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StatusPagesUpdateStatusPageIncidentPayloadV2 = Model.define(
      name: :string
    )

    class StatusPagesUpdateStatusPageIncidentPayloadV2
      # @!attribute [r] name
      #   A title for the incident
      #   @return [String, nil]
    end
  end
end
