# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] end_at
    #   @return [Time, nil] The time the maintenance window ends
    # @!attribute [r] name
    #   @return [String, nil] A title for the maintenance window
    # @!attribute [r] start_at
    #   @return [Time, nil] The time the maintenance window starts
    StatusPagesUpdateStatusPageMaintenancePayloadV2 = Model.define(
      end_at: :time,
      name: :string,
      start_at: :time
    )
  end
end
