# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StatusPageIncidentV2 = Model.define(
      component_impacts: [-> { StatusPageIncidentComponentImpactV2 }],
      id: :string,
      incident_status: :string,
      name: :string,
      published_at: :time,
      status_page_id: :string,
      updates: [-> { StatusPageIncidentUpdateV2 }]
    )

    class StatusPageIncidentV2
      # @!attribute [r] component_impacts
      #   A list of time periods that this status page incident had an impact on a…
      #   @return [Array<StatusPageIncidentComponentImpactV2>, nil]
      # @!attribute [r] id
      #   A unique ID for this status page incident
      #   @return [String, nil]
      # @!attribute [r] incident_status
      #   Current status for this incident One of: investigating, identified,…
      #   @return [String, nil]
      # @!attribute [r] name
      #   A title for the incident
      #   @return [String, nil]
      # @!attribute [r] published_at
      #   When this status page incident was published to the status page
      #   @return [Time, nil]
      # @!attribute [r] status_page_id
      #   The ID of the corresponding status page
      #   @return [String, nil]
      # @!attribute [r] updates
      #   A list of updates posted to this status page incident
      #   @return [Array<StatusPageIncidentUpdateV2>, nil]
    end
  end
end
