# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # Availability of a status page component over a requested time window.
    #
    # @!attribute [r] availability_percent
    #   @return [String, nil] Availability over the window as a percentage, floored (for example "99.94").
    # @!attribute [r] component_id
    #   @return [String, nil] ID of the component.
    # @!attribute [r] data_available_since
    #   @return [Time, nil] Earliest time we have status data for this component.
    # @!attribute [r] end_at
    #   @return [Time, nil] End of the requested availability window
    # @!attribute [r] start_at
    #   @return [Time, nil] Start of the requested availability window
    # @!attribute [r] status_page_id
    #   @return [String, nil] ID of the status page
    StatusPageComponentAvailabilityV2 = Model.define(
      availability_percent: :string,
      component_id: :string,
      data_available_since: :time,
      end_at: :time,
      start_at: :time,
      status_page_id: :string
    )
  end
end
