# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] component_id
    #   @return [String, nil] The ID of the affected component.
    # @!attribute [r] end_at
    #   @return [Time, nil] When the component stopped being under maintenance.
    # @!attribute [r] start_at
    #   @return [Time, nil] When the component started being under maintenance
    StatusPageMaintenanceComponentMaintenancePeriodV2 = Model.define(
      component_id: :string,
      end_at: :time,
      start_at: :time
    )
  end
end
