# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StatusPageStructureSubPageItemV2 = Model.define(
      component: -> { StatusPageStructureComponentV2 },
      group: -> { StatusPageStructureGroupV2 }
    )

    class StatusPageStructureSubPageItemV2
      # @!attribute [r] component
      #   The component field
      #   @return [StatusPageStructureComponentV2, nil]
      # @!attribute [r] group
      #   The group field
      #   @return [StatusPageStructureGroupV2, nil]
    end
  end
end
