# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StatusPagesCreateStatusPageMaintenanceUpdatePayloadV2 = Model.define(
      component_statuses: [-> { StatusPageMaintenanceAffectedComponentV2 }],
      maintenance_status: :string,
      message: :string,
      notify_subscribers: :boolean,
      status_page_maintenance_id: :string
    )

    class StatusPagesCreateStatusPageMaintenanceUpdatePayloadV2
      # @!attribute [r] component_statuses
      #   An array of mappings from component ID to component status
      #   @return [Array<StatusPageMaintenanceAffectedComponentV2>, nil]
      # @!attribute [r] maintenance_status
      #   Optional new status for this status page maintenance window
      #   @return [String, nil]
      # @!attribute [r] message
      #   Markdown update on what's changed about this status page maintenance window
      #   @return [String, nil]
      # @!attribute [r] notify_subscribers
      #   Whether to notify subscribers about this status page maintenance update
      #   @return [Boolean, nil]
      # @!attribute [r] status_page_maintenance_id
      #   ID of the status page maintenance window
      #   @return [String, nil]
    end
  end
end
