# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StatusPagesCreateStatusPageIncidentPayloadV2 = Model.define(
      component_statuses: [-> { StatusPageIncidentAffectedComponentV2 }],
      idempotency_key: :string,
      incident_status: :string,
      message: :string,
      name: :string,
      notify_subscribers: :boolean,
      status_page_id: :string
    )

    class StatusPagesCreateStatusPageIncidentPayloadV2
      # @!attribute [r] component_statuses
      #   An array of mappings from component ID to current component status
      #   @return [Array<StatusPageIncidentAffectedComponentV2>, nil]
      # @!attribute [r] idempotency_key
      #   A unique key to de-duplicate requests
      #   @return [String, nil]
      # @!attribute [r] incident_status
      #   Current status for this status page incident One of: investigating,…
      #   @return [String, nil]
      # @!attribute [r] message
      #   Markdown initial update on this status page incident
      #   @return [String, nil]
      # @!attribute [r] name
      #   A title for the incident
      #   @return [String, nil]
      # @!attribute [r] notify_subscribers
      #   Whether to notify subscribers about this status page incident
      #   @return [Boolean, nil]
      # @!attribute [r] status_page_id
      #   ID of the status page
      #   @return [String, nil]
    end
  end
end
