# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StatusPagesCreateStatusPageMaintenancePayloadV2 = Model.define(
      affected_component_ids: [:string],
      automate_maintenance_status: :boolean,
      end_at: :time,
      idempotency_key: :string,
      maintenance_status: :string,
      message: :string,
      name: :string,
      notify_subscribers: :boolean,
      start_at: :time,
      status_page_id: :string
    )

    class StatusPagesCreateStatusPageMaintenancePayloadV2
      # @!attribute [r] affected_component_ids
      #   An array of IDs of component affected by the maintenance window
      #   @return [Array<String>, nil]
      # @!attribute [r] automate_maintenance_status
      #   Whether to publish updates automatically, moving this maintenance window to…
      #   @return [Boolean, nil]
      # @!attribute [r] end_at
      #   The time the maintenance window ends
      #   @return [Time, nil]
      # @!attribute [r] idempotency_key
      #   A unique key to de-duplicate requests
      #   @return [String, nil]
      # @!attribute [r] maintenance_status
      #   Current status for this status page maintenance window One of:…
      #   @return [String, nil]
      # @!attribute [r] message
      #   Markdown initial update on this status page maintenance window
      #   @return [String, nil]
      # @!attribute [r] name
      #   A title for the maintenance window
      #   @return [String, nil]
      # @!attribute [r] notify_subscribers
      #   Whether to notify subscribers about this status page maintenance
      #   @return [Boolean, nil]
      # @!attribute [r] start_at
      #   The time the maintenance window starts
      #   @return [Time, nil]
      # @!attribute [r] status_page_id
      #   ID of the status page
      #   @return [String, nil]
    end
  end
end
