# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StatusPageStructureSubPageV2 = Model.define(
      id: :string,
      items: [-> { StatusPageStructureSubPageItemV2 }],
      name: :string
    )

    class StatusPageStructureSubPageV2
      # @!attribute [r] id
      #   Unique ID of this subpage
      #   @return [String, nil]
      # @!attribute [r] items
      #   Array of components and groups belonging to this subpage
      #   @return [Array<StatusPageStructureSubPageItemV2>, nil]
      # @!attribute [r] name
      #   The name of this subpage
      #   @return [String, nil]
    end
  end
end
