# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] component_statuses
    #   @return [Array<StatusPageMaintenanceAffectedComponentV2>, nil] An array of mappings from component ID to component status.
    # @!attribute [r] maintenance_status
    #   @return [String, nil] Optional new status for this status page maintenance window.
    # @!attribute [r] message
    #   @return [String, nil] Markdown update on what's changed about this status page maintenance window
    # @!attribute [r] notify_subscribers
    #   @return [Boolean, nil] Whether to notify subscribers about this status page maintenance update.
    # @!attribute [r] status_page_maintenance_id
    #   @return [String, nil] ID of the status page maintenance window
    StatusPagesCreateStatusPageMaintenanceUpdatePayloadV2 = Model.define(
      component_statuses: [-> { StatusPageMaintenanceAffectedComponentV2 }],
      maintenance_status: :string,
      message: :string,
      notify_subscribers: :boolean,
      status_page_maintenance_id: :string
    )
  end
end
