# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StepConfigPayloadV2 = Model.define(
      for_each: :string,
      id: :string,
      name: :string,
      param_bindings: [-> { EngineParamBindingPayloadV2 }]
    )

    class StepConfigPayloadV2
      # @!attribute [r] for_each
      #   Reference to an expression that returns resources to run this step over
      #   @return [String, nil]
      # @!attribute [r] id
      #   Unique ID of this step in a workflow
      #   @return [String, nil]
      # @!attribute [r] name
      #   Unique name of the step in the engine
      #   @return [String, nil]
      # @!attribute [r] param_bindings
      #   List of parameter bindings
      #   @return [Array<EngineParamBindingPayloadV2>, nil]
    end
  end
end
