# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StepConfigV2 = Model.define(
      for_each: :string,
      id: :string,
      label: :string,
      name: :string,
      param_bindings: [-> { EngineParamBindingV2 }]
    )

    class StepConfigV2
      # @!attribute [r] for_each
      #   Reference to an expression that returns resources to run this step over
      #   @return [String, nil]
      # @!attribute [r] id
      #   Unique ID of this step in a workflow
      #   @return [String, nil]
      # @!attribute [r] label
      #   Human readable identifier for this step
      #   @return [String, nil]
      # @!attribute [r] name
      #   Unique name of the step in the engine
      #   @return [String, nil]
      # @!attribute [r] param_bindings
      #   Bindings for the step parameters
      #   @return [Array<EngineParamBindingV2>, nil]
    end
  end
end
