# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    StepConfigSlimV2 = Model.define(
      label: :string,
      name: :string
    )

    class StepConfigSlimV2
      # @!attribute [r] label
      #   Human readable identifier for this step
      #   @return [String, nil]
      # @!attribute [r] name
      #   Unique name of the step in the engine
      #   @return [String, nil]
    end
  end
end
