# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    TelemetryUpdateDataSourcePayloadV2 = Model.define(
      datadog_config: -> { TelemetryDatadogUpdateConfigV2 },
      grafana_config: -> { TelemetryGrafanaUpdateConfigV2 },
      name: :string
    )

    class TelemetryUpdateDataSourcePayloadV2
      # @!attribute [r] datadog_config
      #   The datadog_config field
      #   @return [TelemetryDatadogUpdateConfigV2, nil]
      # @!attribute [r] grafana_config
      #   The grafana_config field
      #   @return [TelemetryGrafanaUpdateConfigV2, nil]
      # @!attribute [r] name
      #   Updated display name
      #   @return [String, nil]
    end
  end
end
