# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # Grafana-specific credential and endpoint updates
    #
    # @!attribute [r] api_key
    #   @return [String, nil] New Grafana service account token
    # @!attribute [r] api_url
    #   @return [String, nil] Grafana API URL (without protocol)
    TelemetryGrafanaUpdateConfigV2 = Model.define(
      api_key: :string,
      api_url: :string
    )
  end
end
