# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] base_role
    #   @return [RBACRoleV2, nil]
    # @!attribute [r] custom_roles
    #   @return [Array<RBACRoleV2>, nil]
    # @!attribute [r] email
    #   @return [String, nil] Email address of the user.
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier of the user
    # @!attribute [r] is_active
    #   @return [Boolean, nil] Whether the user is active.
    # @!attribute [r] name
    #   @return [String, nil] Name of the user
    # @!attribute [r] role
    #   @return [String, nil] DEPRECATED: Role of the user as of March 9th 2023, this value is no longer updated.
    # @!attribute [r] seats
    #   @return [UserSeatsV2, nil]
    # @!attribute [r] slack_user_id
    #   @return [String, nil] Slack ID of the user
    UserWithRolesV2 = Model.define(
      base_role: -> { RBACRoleV2 },
      custom_roles: [-> { RBACRoleV2 }],
      email: :string,
      id: :string,
      is_active: :boolean,
      name: :string,
      role: :string,
      seats: -> { UserSeatsV2 },
      slack_user_id: :string
    )
  end
end
