# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] email
    #   @return [String, nil] Email address of the user.
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier of the user
    # @!attribute [r] name
    #   @return [String, nil] Name of the user
    # @!attribute [r] slack_user_id
    #   @return [String, nil] Slack ID of the user
    UserV3 = Model.define(
      email: :string,
      id: :string,
      name: :string,
      slack_user_id: :string
    )
  end
end
