# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhooksPublicEscalationCreatedV1ResponseBody = Model.define(
      event_type: :string,
      "public_escalation.escalation_created_v1": -> { EscalationV2 }
    )

    class WebhooksPublicEscalationCreatedV1ResponseBody
      # @!attribute [r] event_type
      #   What type of event is this webhook for?
      #   @return [String, nil]
      # @!attribute [r] public_escalation_escalation_created_v1
      #   The public_escalation.escalation_created_v1 field
      #   @return [EscalationV2, nil]
    end
  end
end
