# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] event_type
    #   @return [String, nil] What type of event is this webhook for?
    # @!attribute [r] private_incident_follow_up_created_v1
    #   @return [WebhookPrivateResourceV2, nil]
    WebhooksPrivateIncidentFollowUpCreatedV1ResponseBody = Model.define(
      event_type: :string,
      "private_incident.follow_up_created_v1": -> { WebhookPrivateResourceV2 }
    )
  end
end
