# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhooksPublicEscalationStatusUpdatedV1ResponseBody = Model.define(
      event_type: :string,
      "public_escalation.escalation_status_updated_v1": -> { EscalationWithStatusChangeV2 }
    )

    class WebhooksPublicEscalationStatusUpdatedV1ResponseBody
      # @!attribute [r] event_type
      #   What type of event is this webhook for?
      #   @return [String, nil]
      # @!attribute [r] public_escalation_escalation_status_updated_v1
      #   The public_escalation.escalation_status_updated_v1 field
      #   @return [EscalationWithStatusChangeV2, nil]
    end
  end
end
