# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhooksPublicAlertCreatedV1ResponseBody = Model.define(
      event_type: :string,
      "public_alert.alert_created_v1": -> { AlertV2 }
    )

    class WebhooksPublicAlertCreatedV1ResponseBody
      # @!attribute [r] event_type
      #   What type of event is this webhook for?
      #   @return [String, nil]
      # @!attribute [r] public_alert_alert_created_v1
      #   The public_alert.alert_created_v1 field
      #   @return [AlertV2, nil]
    end
  end
end
