# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhooksPublicIncidentActionUpdatedV1ResponseBody = Model.define(
      event_type: :string,
      "public_incident.action_updated_v1": -> { ActionV1 }
    )

    class WebhooksPublicIncidentActionUpdatedV1ResponseBody
      # @!attribute [r] event_type
      #   What type of event is this webhook for?
      #   @return [String, nil]
      # @!attribute [r] public_incident_action_updated_v1
      #   The public_incident.action_updated_v1 field
      #   @return [ActionV1, nil]
    end
  end
end
