# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhooksPrivateIncidentFollowUpUpdatedV2ResponseBody = Model.define(
      event_type: :string,
      "private_incident.follow_up_updated_v2": -> { WebhookPrivateResourceV2 }
    )

    class WebhooksPrivateIncidentFollowUpUpdatedV2ResponseBody
      # @!attribute [r] event_type
      #   What type of event is this webhook for?
      #   @return [String, nil]
      # @!attribute [r] private_incident_follow_up_updated_v2
      #   The private_incident.follow_up_updated_v2 field
      #   @return [WebhookPrivateResourceV2, nil]
    end
  end
end
