# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] actor_user_id
    #   @return [String, nil] The ID of the user who performed this action.
    # @!attribute [r] incident_id
    #   @return [String, nil] The ID of the incident
    # @!attribute [r] user_id
    #   @return [String, nil] The ID of the user
    WebhookIncidentUserV2 = Model.define(
      actor_user_id: :string,
      incident_id: :string,
      user_id: :string
    )
  end
end
