# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhookDeliveryRequestV2 = Model.define(
      body: :string,
      body_truncated: :boolean,
      headers: Model.map_of(:string)
    )

    class WebhookDeliveryRequestV2
      # @!attribute [r] body
      #   The interpolated request body
      #   @return [String, nil]
      # @!attribute [r] body_truncated
      #   Whether the body was truncated, in which case it may not be valid JSON
      #   @return [Boolean, nil]
      # @!attribute [r] headers
      #   Headers sent with the request, including those added automatically
      #   @return [Hash{String => String}, nil]
    end
  end
end
