# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhooksPrivateIncidentPostmortemDocumentStatusUpdatedV1ResponseBody = Model.define(
      event_type: :string,
      "private_incident.postmortem_document_status_updated_v1": -> { WebhookPrivateResourceV2 }
    )

    class WebhooksPrivateIncidentPostmortemDocumentStatusUpdatedV1ResponseBody
      # @!attribute [r] event_type
      #   What type of event is this webhook for?
      #   @return [String, nil]
      # @!attribute [r] private_incident_postmortem_document_status_updated_v1
      #   The private_incident.postmortem_document_status_updated_v1 field
      #   @return [WebhookPrivateResourceV2, nil]
    end
  end
end
