# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] event_type
    #   @return [String, nil] What type of event is this webhook for?
    # @!attribute [r] public_alert_alert_resolved_v1
    #   @return [AlertV2, nil]
    WebhooksPublicAlertResolvedV1ResponseBody = Model.define(
      event_type: :string,
      "public_alert.alert_resolved_v1": -> { AlertV2 }
    )
  end
end
