# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhookPrivateResourceV2 = Model.define(
      id: :string
    )

    class WebhookPrivateResourceV2
      # @!attribute [r] id
      #   The ID of the resource
      #   @return [String, nil]
    end
  end
end
