# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhooksPublicIncidentIncidentCreatedV2ResponseBody = Model.define(
      event_type: :string,
      "public_incident.incident_created_v2": -> { WebhookIncidentV2 }
    )

    class WebhooksPublicIncidentIncidentCreatedV2ResponseBody
      # @!attribute [r] event_type
      #   What type of event is this webhook for?
      #   @return [String, nil]
      # @!attribute [r] public_incident_incident_created_v2
      #   The public_incident.incident_created_v2 field
      #   @return [WebhookIncidentV2, nil]
    end
  end
end
