# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhooksPublicIncidentFollowUpUpdatedV2ResponseBody = Model.define(
      event_type: :string,
      "public_incident.follow_up_updated_v2": -> { FollowUpV2 }
    )

    class WebhooksPublicIncidentFollowUpUpdatedV2ResponseBody
      # @!attribute [r] event_type
      #   What type of event is this webhook for?
      #   @return [String, nil]
      # @!attribute [r] public_incident_follow_up_updated_v2
      #   The public_incident.follow_up_updated_v2 field
      #   @return [FollowUpV2, nil]
    end
  end
end
