# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WebhooksScheduleCreatedV1ResponseBody = Model.define(
      event_type: :string,
      "schedule.created_v1": -> { ScheduleSlimV2 }
    )

    class WebhooksScheduleCreatedV1ResponseBody
      # @!attribute [r] event_type
      #   What type of event is this webhook for?
      #   @return [String, nil]
      # @!attribute [r] schedule_created_v1
      #   The schedule.created_v1 field
      #   @return [ScheduleSlimV2, nil]
    end
  end
end
