# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WeekdayIntervalV2 = Model.define(
      end_time: :string,
      start_time: :string,
      weekday: :string
    )

    class WeekdayIntervalV2
      # @!attribute [r] end_time
      #   End time of the interval, in 24hr format
      #   @return [String, nil]
      # @!attribute [r] start_time
      #   Start time of the interval, in 24hr format
      #   @return [String, nil]
      # @!attribute [r] weekday
      #   Weekdays for use within a schedule or escalation path One of: monday,…
      #   @return [String, nil]
    end
  end
end
