# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WorkflowDelayV2 = Model.define(
      conditions_apply_over_delay: :boolean,
      for_seconds: :integer
    )

    class WorkflowDelayV2
      # @!attribute [r] conditions_apply_over_delay
      #   If this workflow is delayed, whether the conditions should be rechecked…
      #   @return [Boolean, nil]
      # @!attribute [r] for_seconds
      #   Delay in seconds between trigger firing and running the workflow
      #   @return [Integer, nil]
    end
  end
end
