# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WorkflowFormFieldV2 = Model.define(
      array: :boolean,
      description: :string,
      id: :string,
      key: :string,
      required: :boolean,
      title: :string,
      type: :string
    )

    class WorkflowFormFieldV2
      # @!attribute [r] array
      #   Whether this field holds a list of values rather than a single value
      #   @return [Boolean, nil]
      # @!attribute [r] description
      #   Optional help text shown beneath the field
      #   @return [String, nil]
      # @!attribute [r] id
      #   Stable identifier for this form field, preserved across versions
      #   @return [String, nil]
      # @!attribute [r] key
      #   The key used to reference this field in the workflow scope
      #   @return [String, nil]
      # @!attribute [r] required
      #   Whether this field must be filled in when running the workflow
      #   @return [Boolean, nil]
      # @!attribute [r] title
      #   Human readable title shown in the form
      #   @return [String, nil]
      # @!attribute [r] type
      #   The engine resource type of this field
      #   @return [String, nil]
    end
  end
end
