# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] data_synced_at
    #   @return [Time, nil] The time the workload figures are calculated up to.
    WorkloadMetadataV2 = Model.define(
      data_synced_at: :time
    )
  end
end
