# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    WorkflowsUpdateWorkflowPayloadV2 = Model.define(
      annotations: Model.map_of(:string),
      condition_groups: [-> { ConditionGroupPayloadV2 }],
      continue_on_step_error: :boolean,
      delay: -> { WorkflowDelayV2 },
      expressions: [-> { ExpressionPayloadV2 }],
      folder: :string,
      form_fields: [-> { WorkflowFormFieldPayloadV2 }],
      include_private_escalations: :boolean,
      include_private_incidents: :boolean,
      name: :string,
      once_for: [:string],
      owning_team_ids: [:string],
      private_incident_scope: :string,
      runs_on_incident_modes: [:string],
      runs_on_incidents: :string,
      shortform: :string,
      skip_step_upgrades: :boolean,
      state: :string,
      steps: [-> { StepConfigPayloadV2 }]
    )

    class WorkflowsUpdateWorkflowPayloadV2
      # @!attribute [r] annotations
      #   Annotations that track metadata about this resource
      #   @return [Hash{String => String}, nil]
      # @!attribute [r] condition_groups
      #   Conditions that apply to the workflow trigger
      #   @return [Array<ConditionGroupPayloadV2>, nil]
      # @!attribute [r] continue_on_step_error
      #   Whether to continue executing the workflow if a step fails
      #   @return [Boolean, nil]
      # @!attribute [r] delay
      #   The delay field
      #   @return [WorkflowDelayV2, nil]
      # @!attribute [r] expressions
      #   The expressions to use in the workflow
      #   @return [Array<ExpressionPayloadV2>, nil]
      # @!attribute [r] folder
      #   Folder to display the workflow in
      #   @return [String, nil]
      # @!attribute [r] form_fields
      #   User-configured form fields available in the workflow scope (manual triggers…
      #   @return [Array<WorkflowFormFieldPayloadV2>, nil]
      # @!attribute [r] include_private_escalations
      #   Whether to include private escalations
      #   @return [Boolean, nil]
      # @!attribute [r] include_private_incidents
      #   DEPRECATED: use `private_incident_scope` instead
      #   @return [Boolean, nil]
      # @!attribute [r] name
      #   Name provided by the user when creating the workflow
      #   @return [String, nil]
      # @!attribute [r] once_for
      #   This workflow will run 'once for' a list of references
      #   @return [Array<String>, nil]
      # @!attribute [r] owning_team_ids
      #   IDs of the teams that own this workflow
      #   @return [Array<String>, nil]
      # @!attribute [r] private_incident_scope
      #   Which private incidents this workflow acts on: every private incident (all),…
      #   @return [String, nil]
      # @!attribute [r] runs_on_incident_modes
      #   Which incident modes should this workflow run on?
      #   @return [Array<String>, nil]
      # @!attribute [r] runs_on_incidents
      #   Which incidents should the workflow be applied to?
      #   @return [String, nil]
      # @!attribute [r] shortform
      #   The shortform used to trigger this workflow (only applicable for manual…
      #   @return [String, nil]
      # @!attribute [r] skip_step_upgrades
      #   Skips workflow step upgrades, when the parameters for an existing workflow…
      #   @return [Boolean, nil]
      # @!attribute [r] state
      #   What state this workflow is in One of: active, disabled, draft, error
      #   @return [String, nil]
      # @!attribute [r] steps
      #   Steps that are executed as part of the workflow
      #   @return [Array<StepConfigPayloadV2>, nil]
    end
  end
end
