# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] id
    #   @return [String, nil] Unique identifier for the workflow
    # @!attribute [r] name
    #   @return [String, nil] Name provided by the user when creating the workflow
    WorkflowActorV2 = Model.define(
      id: :string,
      name: :string
    )
  end
end
