# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Models
    # @!attribute [r] conditions_apply_over_delay
    #   @return [Boolean, nil] If this workflow is delayed, whether the conditions should be rechecked between trigger firing and execution
    # @!attribute [r] for_seconds
    #   @return [Integer, nil] Delay in seconds between trigger firing and running the workflow
    WorkflowDelayV2 = Model.define(
      conditions_apply_over_delay: :boolean,
      for_seconds: :integer
    )
  end
end
