# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V3
      # Manage and browse catalog resources.
      #
      # Use the incident.io catalog to track services, teams, product features and anything
      # else that helps build a map of your organisation. These different categories of thing
      # become catalog types, and each instance (like a particular service or team) is a
      # catalog entry.
      #
      # Each type is made up of a series of attributes, and each attribute has a type. Types
      # can even have attributes that refer to other catalog types.
      #
      # We automatically create catalog types when you connect an integration, such as GitHub
      # repositories or PagerDuty services and teams. You can use this API to create custom
      # types, that are specifically tailored to your organisation.
      #
      # Examples might be a 'Service' type with an 'Alert channel' which you can point at a
      # Slack channel, or 'Team' which specifies its 'Manager' and 'Technical Lead' as Slack
      # users. You can then use these types to create powerful new workflows.
      #
      # Consider using our official [catalog importer](https://github.com/incident-io/catalog-importer).
      # It can be used to sync catalog data from sources like local files or GitHub and push
      # them into the incident.io catalog without having to directly interact with our public API.
      class Catalog < Resource
        # Update multiple catalog entries in a single operation. You can update up to 250 entries at once. This operation is atomic - either all entries are updated successfully, or none are updated.
        #
        # Endpoint: `POST /v3/catalog_entries/actions/bulk_update`. Scopes: catalog_entries.edit.
        #
        # @param catalog_type_id [String] The unique identifier of the catalog type containing the entries.
        # @param entries [Array<Models::PartialEntryPayloadV3, Hash>] A list of entries to update with their new values. Maximum 250 entries per request.
        # @param update_attributes [Array<String>] Optional list of specific attribute IDs to update across all entries. When provided, only these attributes in attribute_values will be updated and all other attributes will be preserved. This parameter only affects attribute_values - it does not affect core entry fields like name, rank, aliases, or external_id, which follow their individual omission rules.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def bulk_update_entries(catalog_type_id:, entries:, update_attributes: nil, request_options: {})
          request(
            :post,
            "/v3/catalog_entries/actions/bulk_update",
            body: { catalog_type_id:, entries:, update_attributes: }.compact,
            request_options:
          )
        end

        # Create an entry within the catalog. We support a maximum of 50,000 entries per type.
        #
        # If you call this API with a payload where the external_id and catalog_type_id match an existing entry, the existing entry will be updated.
        #
        # Endpoint: `POST /v3/catalog_entries`. Scopes: catalog_entries.create.
        #
        # @param attribute_values [Hash{String => Models::CatalogEngineParamBindingPayloadV3}] Values of this entry.
        # @param catalog_type_id [String] ID of this catalog type.
        # @param name [String] Name is the human readable name of this entry.
        # @param aliases [Array<String>] Optional aliases that can be used to reference this entry.
        # @param external_id [String] An optional alternative ID for this entry, which is ensured to be unique for the type.
        # @param rank [Integer] When catalog type is ranked, this is used to help order things.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogEntryV3]
        def create_entry(
          attribute_values:,
          catalog_type_id:,
          name:,
          aliases: nil,
          external_id: nil,
          rank: nil,
          request_options: {}
        )
          request(
            :post,
            "/v3/catalog_entries",
            body: { aliases:, attribute_values:, catalog_type_id:, external_id:, name:, rank: }.compact,
            unwrap: "catalog_entry",
            model: Models::CatalogEntryV3,
            request_options:
          )
        end

        # Create a catalog type. The schema must be updated using the UpdateTypeSchema endpoint.
        #
        # Endpoint: `POST /v3/catalog_types`. Scopes: catalog_types.create.
        #
        # @param description [String] Human readble description of this type.
        # @param name [String] Name is the human readable name of this type.
        # @param annotations [Hash{String => String}] Annotations that can track metadata about this type.
        # @param categories [Array<String>] What categories is this type considered part of One of: customer, issue-tracker, product-feature, service, on-call, team, user.
        # @param color [String] Sets the display color of this type in the dashboard One of: yellow, green, blue, violet, pink, cyan, orange.
        # @param icon [String] Sets the display icon of this type in the dashboard One of: alert, bolt, box, briefcase, browser, bulb, calendar, clock, cog, components, database, doc, email, escalation-path, files, flag, folder, globe, incident-template, money, server, severity, status-page, store, star, tag, user, users.
        # @param owning_team_ids [Array<String>] IDs of the teams that own this catalog type.
        # @param ranked [Boolean] If this type should be ranked.
        # @param source_repo_url [String] The url of the external repository where this type is managed.
        # @param type_name [String] The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"].
        # @param use_name_as_identifier [Boolean] If enabled, you can refer to entries of this type by their name, as well as their external ID and any aliases.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogTypeV3]
        def create_type(
          description:,
          name:,
          annotations: nil,
          categories: nil,
          color: nil,
          icon: nil,
          owning_team_ids: nil,
          ranked: nil,
          source_repo_url: nil,
          type_name: nil,
          use_name_as_identifier: nil,
          request_options: {}
        )
          request(
            :post,
            "/v3/catalog_types",
            body: {
              annotations:,
              categories:,
              color:,
              description:,
              icon:,
              name:,
              owning_team_ids:,
              ranked:,
              source_repo_url:,
              type_name:,
              use_name_as_identifier:
            }.compact,
            unwrap: "catalog_type",
            model: Models::CatalogTypeV3,
            request_options:
          )
        end

        # Archives a catalog entry.
        #
        # Endpoint: `DELETE /v3/catalog_entries/{id}`. Scopes: catalog_entries.destroy.
        #
        # @param id [String] ID of this catalog entry.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def destroy_entry(id, request_options: {})
          request(
            :delete,
            path("/v3/catalog_entries/%s", id),
            request_options:
          )
        end

        # Archives a catalog type and associated entries.
        #
        # Endpoint: `DELETE /v3/catalog_types/{id}`. Scopes: catalog_types.destroy.
        #
        # @param id [String] ID of this catalog type.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def destroy_type(id, request_options: {})
          request(
            :delete,
            path("/v3/catalog_types/%s", id),
            request_options:
          )
        end

        # List entries for a catalog type.
        #
        # Endpoint: `GET /v3/catalog_entries`. Scopes: catalog_entries.view.
        #
        # @param catalog_type_id [String] ID of this catalog type.
        # @param page_size [Integer] The integer number of records to return.
        # @param after [String] An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.
        # @param identifier [String] If specified, only entries with this identifier will be returned. This will search by ID, external ID, and aliases. If 'use name as identifier' is enabled for the catalog type, this will also match on name.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::CatalogEntryV3>]
        def list_entries(catalog_type_id:, page_size:, after: nil, identifier: nil, request_options: {})
          paginate(
            "/v3/catalog_entries",
            items_key: "catalog_entries",
            query: { catalog_type_id:, page_size:, after:, identifier: },
            model: Models::CatalogEntryV3,
            request_options:
          )
        end

        # List available engine resources for the catalog.
        #
        # A resource represents a type of data that can be held within the catalog, so this
        # endpoint can be used to see what attribute types can be used when updating the
        # schema of a catalog type.
        #
        # Endpoint: `GET /v3/catalog_resources`. Scopes: catalog_types.view.
        #
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Array<Models::CatalogResourceV3>]
        def list_resources(request_options: {})
          request(
            :get,
            "/v3/catalog_resources",
            unwrap: "resources",
            model: [Models::CatalogResourceV3],
            request_options:
          )
        end

        # List all catalog types for an organisation, including those synced from external resources.
        #
        # Endpoint: `GET /v3/catalog_types`. Scopes: catalog_types.view.
        #
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Array<Models::CatalogTypeV3>]
        def list_types(request_options: {})
          request(
            :get,
            "/v3/catalog_types",
            unwrap: "catalog_types",
            model: [Models::CatalogTypeV3],
            request_options:
          )
        end

        # Show a single catalog entry.
        #
        # Endpoint: `GET /v3/catalog_entries/{id}`. Scopes: catalog_entries.view.
        #
        # @param id [String] ID of this catalog entry.
        # @param expand [Boolean] Whether to include details of all attribute links (forwards and backwards) within the response. Default behaviour (no query param) is to include only forward links. When expand is false, we only show attributes of the catalog entry itself.When expand is true, we show forward and backward links.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogShowEntryResultV3]
        def show_entry(id, expand: nil, request_options: {})
          request(
            :get,
            path("/v3/catalog_entries/%s", id),
            query: { expand: },
            model: Models::CatalogShowEntryResultV3,
            request_options:
          )
        end

        # Show a single catalog type.
        #
        # Endpoint: `GET /v3/catalog_types/{id}`. Scopes: catalog_types.view.
        #
        # @param id [String] ID of this catalog type.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogTypeV3]
        def show_type(id, request_options: {})
          request(
            :get,
            path("/v3/catalog_types/%s", id),
            unwrap: "catalog_type",
            model: Models::CatalogTypeV3,
            request_options:
          )
        end

        # Updates an existing catalog entry.
        #
        # Endpoint: `PUT /v3/catalog_entries/{id}`. Scopes: catalog_entries.edit.
        #
        # @param id [String] ID of this catalog entry.
        # @param attribute_values [Hash{String => Models::CatalogEngineParamBindingPayloadV3}] Values of this entry.
        # @param name [String] Name is the human readable name of this entry.
        # @param aliases [Array<String>] Optional aliases that can be used to reference this entry.
        # @param external_id [String] An optional alternative ID for this entry, which is ensured to be unique for the type.
        # @param rank [Integer] When catalog type is ranked, this is used to help order things.
        # @param update_attributes [Array<String>] If provided, only update these attribute_values keys. If not provided, update all attribute values. If you specify an attribute key that's not in your payload, the associated attribute value will be cleared.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogUpdateEntryResultV3]
        def update_entry(
          id,
          attribute_values:,
          name:,
          aliases: nil,
          external_id: nil,
          rank: nil,
          update_attributes: nil,
          request_options: {}
        )
          request(
            :put,
            path("/v3/catalog_entries/%s", id),
            body: { aliases:, attribute_values:, external_id:, name:, rank:, update_attributes: }.compact,
            model: Models::CatalogUpdateEntryResultV3,
            request_options:
          )
        end

        # Updates an existing catalog type. The schema must be updated using the UpdateTypeSchema endpoint.
        #
        # Endpoint: `PUT /v3/catalog_types/{id}`. Scopes: catalog_types.edit.
        #
        # @param id [String] ID of this catalog type.
        # @param description [String] Human readble description of this type.
        # @param name [String] Name is the human readable name of this type.
        # @param annotations [Hash{String => String}] Annotations that can track metadata about this type.
        # @param categories [Array<String>] What categories is this type considered part of One of: customer, issue-tracker, product-feature, service, on-call, team, user.
        # @param color [String] Sets the display color of this type in the dashboard One of: yellow, green, blue, violet, pink, cyan, orange.
        # @param icon [String] Sets the display icon of this type in the dashboard One of: alert, bolt, box, briefcase, browser, bulb, calendar, clock, cog, components, database, doc, email, escalation-path, files, flag, folder, globe, incident-template, money, server, severity, status-page, store, star, tag, user, users.
        # @param owning_team_ids [Array<String>] IDs of the teams that own this catalog type.
        # @param ranked [Boolean] If this type should be ranked.
        # @param source_repo_url [String] The url of the external repository where this type is managed.
        # @param use_name_as_identifier [Boolean] If enabled, you can refer to entries of this type by their name, as well as their external ID and any aliases.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogTypeV3]
        def update_type(
          id,
          description:,
          name:,
          annotations: nil,
          categories: nil,
          color: nil,
          icon: nil,
          owning_team_ids: nil,
          ranked: nil,
          source_repo_url: nil,
          use_name_as_identifier: nil,
          request_options: {}
        )
          request(
            :put,
            path("/v3/catalog_types/%s", id),
            body: {
              annotations:,
              categories:,
              color:,
              description:,
              icon:,
              name:,
              owning_team_ids:,
              ranked:,
              source_repo_url:,
              use_name_as_identifier:
            }.compact,
            unwrap: "catalog_type",
            model: Models::CatalogTypeV3,
            request_options:
          )
        end

        # Update an existing catalog types schema, adding or removing attributes.
        #
        # Updating the schema is handled separately from creating and updating types, so that you don't
        # have to worry about dependencies between types. For example, if type A has an attribute that
        # relies on type B, you would have to create type B first.
        #
        # By allowing the creation of types without a schema, they can be created in any order, but it
        # means that you need to make a separate call to this endpoint to update the schema.
        #
        # Endpoint: `POST /v3/catalog_types/{id}/actions/update_schema`. Scopes: catalog_types.edit.
        #
        # @param id [String] ID of this catalog type.
        # @param attributes [Array<Models::CatalogTypeAttributePayloadV3, Hash>]
        # @param version [Integer]
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogTypeV3]
        def update_type_schema(id, attributes:, version:, request_options: {})
          request(
            :post,
            path("/v3/catalog_types/%s/actions/update_schema", id),
            body: { attributes:, version: }.compact,
            unwrap: "catalog_type",
            model: Models::CatalogTypeV3,
            request_options:
          )
        end
      end
    end
  end
end
