module IncidentIo
  # A raw HTTP response. Header names are lower case.
  class Response < ::Data
    attr_reader status: Integer
    attr_reader headers: Hash[String, String]
    attr_reader body: String?

    def self.new: (status: Integer, headers: Hash[String, String], body: String?) -> instance

    def initialize: (status: Integer, headers: Hash[String, String], body: String?) -> void

    def success?: () -> bool

    def json?: () -> bool

    def parsed: () -> untyped
  end
end
