module IncidentIo
  module Util
    def self?.serialize: (untyped value) -> untyped

    def self?.escape_path: (_ToS segment) -> String

    def self?.parse_time: (untyped value, ?httpdate: bool) -> Time?
  end
end
