# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V2
      # Read your alerts in incident.io.
      #
      # Alerts are events ingested from third parties by alert sources. They can trigger incidents and escalations, as configured in alert routes.
      # To view your alerts, you can list all alerts, or show a single alert.
      # If you'd like to view only alerts that are currently firing, you can filter by status.
      # To view the alert that was created for an event in your external system, filter by deduplication key.
      #
      # If you'd like to view alerts connected to a particular incident, you can list incident alerts. You can filter by incident_id to find all alerts attached to a particular incident, or by alert_id to find the incident that a particular alert triggered.
      class Alerts < Resource
        # Add tags to an alert without changing its existing tags
        #
        # Add tags to an alert without changing its existing tags.
        #
        # Each tag is a name. A name that does not exist is created, except on private alerts,
        # where only names already in the organisation's tag vocabulary can be used. Tags that are
        # already present are ignored.
        #
        # Endpoint: `POST /v2/alerts/{id}/actions/add_tags`. Scopes: alerts.edit.
        #
        # @param id [String] Unique identifier for the alert.
        # @param tags [Array<String>] Tag names to add to this alert.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::AlertV2]
        def add_tags(id, tags:, request_options: {})
          request(
            :post,
            path("/v2/alerts/%s/actions/add_tags", id),
            body: given({tags:}),
            unwrap: "alert",
            model: Models::AlertV2,
            request_options:
          )
        end

        # Attach an alert to an incident, creating the connection between them
        #
        # Attach an alert to an incident, creating the connection between them.
        #
        # The API key also needs the 'manage incident alerts' scope, which is what actually relates
        # the alert once the connection exists.
        #
        # If the alert is already related to this incident, the existing connection is returned
        # unchanged. If someone previously marked the alert as unrelated to this incident, that
        # decision is preserved and this endpoint returns a 422 — set re_relate to override it.
        #
        # Private alerts can only be attached to private incidents, including when re_relate is set.
        # An API key that cannot see the alert or the incident receives a 404.
        #
        # Busy incidents can be locked by another operation, in which case this endpoint returns a
        # 409 and the request can be retried.
        #
        # Note that this endpoint returns 201 even when it re-relates or returns an existing
        # connection rather than creating a new one.
        #
        # Endpoint: `POST /v2/incident_alerts`. Scopes: alerts.attach_to_incident.
        #
        # @param alert_id [String] Alert to attach to the incident.
        # @param incident_id [String] Incident to attach the alert to.
        # @param re_relate [Boolean] Relate the alert again even though someone previously marked it unrelated to this incident. Defaults to false, which preserves that decision and returns a 422.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentAlertV2]
        def create_incident_alert(alert_id:, incident_id:, re_relate: NOT_GIVEN, request_options: {})
          request(
            :post,
            "/v2/incident_alerts",
            body: given({alert_id:, incident_id:, re_relate:}),
            unwrap: "incident_alert",
            model: Models::IncidentAlertV2,
            request_options:
          )
        end

        # List all alerts for your account
        #
        # List all alerts for your account.
        #
        # This endpoint supports a number of filters, which can help find alerts matching certain
        # criteria. These filters work similarly to the filters on the incidents endpoint, where
        # a field is specified alongside a comparison operator in the query string.
        #
        # Note that:
        # - Filters may be used together, and the result will be alerts that match all filters.
        # - All query parameters must be URI encoded.
        #
        # ### By deduplication_key
        #
        # Find all alerts with deduplication_key ABC:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'deduplication_key[is]=ABC'
        #
        # ### By status
        #
        # Find all alerts in a firing state:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'status[one_of]=firing'
        #
        # ### By alert_source
        #
        # Find all alerts from a specific alert source (by alert source ID):
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'alert_source[one_of]=01GBSQF3FHF7FWZQNWGHAVQ804'
        #
        # Find all alerts not from a specific alert source:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'alert_source[not_in]=01GBSQF3FHF7FWZQNWGHAVQ804'
        #
        # ### By alert_group_id
        #
        # Find all alerts in a specific alert group:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'alert_group_id[one_of]=01GBSQF3FHF7FWZQNWGHAVQ804'
        #
        # ### By created_at
        # Find all alerts that follow specified date parameters for created_at field.
        # Possible values are "gte" (greater than or equal to), "lte" (less than or equal to), and
        # "date_range" (between two dates). The following example finds all alerts created after
        # 2025-01-01:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'created_at[gte]=2025-01-01'
        #
        # To find alerts created within a specific date range, use the date_range option with
        # tilde-separated dates:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'created_at[date_range]=2024-12-02~2024-12-08'
        #
        # ### By updated_at
        # Find all alerts that follow specified date parameters for updated_at field, using the same
        # "gte", "lte" and "date_range" operators as created_at. This is useful for incrementally
        # syncing alerts: poll with updated_at[gte] set to your last sync time instead of re-fetching
        # the full history. Note that updated_at moves whenever the alert row is written, which can
        # happen without a visible change to the alert payload, so treat matches as candidates to
        # re-fetch rather than guaranteed changes — and overlap your sync window by a few minutes to
        # allow for writes that commit out of timestamp order:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'updated_at[gte]=2025-01-01T00:00:00Z'
        #
        # ### By has_notes
        #
        # Find all alerts that have notes attached:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'has_notes[is]=true'
        #
        # Find all alerts that have no notes attached:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'has_notes[is]=false'
        #
        # ### By tags
        #
        # Filter by tag name, matched case-insensitively.
        #
        # Find all alerts that have any of the given tags:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'tags[one_of]=known issue'
        #
        # Find all alerts that have all of the given tags:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'tags[all_of]=known issue' \
        # 			--data 'tags[all_of]=customer impacting'
        #
        # Find all alerts that do not have any of the given tags. Untagged alerts are included:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'tags[not_in]=known issue'
        #
        # ### By attributes
        #
        # Alerts can be filtered by their attribute values. Each filter is keyed by the alert
        # attribute ID, followed by an operator and the values to match. The accepted operators
        # depend on the attribute's type.
        #
        # Find all alerts where attribute 01GBSQF3FHF7FWZQNWGHAVQ804 is one of two catalog entries:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'attributes[01GBSQF3FHF7FWZQNWGHAVQ804][one_of]=01GBSQF3FHF7FWZQNWGHAVQ804' \
        # 			--data 'attributes[01GBSQF3FHF7FWZQNWGHAVQ804][one_of]=01ET65M7ZARSFZ6TFDFVQDN9AA'
        #
        # You can filter on multiple attributes at once, and the result will be alerts that match
        # all of them.
        #
        # ### Maintenance windows
        # By default, all alerts are returned including those held by a maintenance window.
        # To exclude alerts that are held by a maintenance window:
        #
        # 		curl --get 'https://api.incident.io/v2/alerts' \
        # 			--data 'include_maintenance_window[is]=false'
        #
        # Endpoint: `GET /v2/alerts`. Scopes: alerts.view.
        #
        # @param page_size [Integer] Number of alerts to return per page.
        # @param after [String] If provided, pass this as the 'after' param to load the next page.
        # @param deduplication_key [Hash{String => Array<String>}] Filter on alert deduplication key. The accepted operator is 'is'.
        # @param status [Hash{String => Array<String>}] Filter on alert status. The accepted operators are 'one_of', or 'not_in'.
        # @param alert_source [Hash{String => Array<String>}] Filter on alert source by ID. The accepted operators are 'one_of', or 'not_in'.
        # @param alert_group_id [Hash{String => Array<String>}] Filter on alert group ID. Returns alerts that belong to any of the specified groups. The accepted operator is 'one_of'.
        # @param created_at [Hash{String => Array<String>}] Filter on alert created at timestamp. Accepted operators are 'gte', 'lte' and 'date_range'.
        # @param updated_at [Hash{String => Array<String>}] Filter on alert updated at timestamp. Accepted operators are 'gte', 'lte' and 'date_range'.
        # @param attributes [Hash{String => Hash{String => Array<String>}}] Filter on an alerts attributes. Alert attribute ID should be sent, followed by the operator and values. Accepted operator will depend on the attribute type.
        # @param has_notes [Hash{String => Array<String>}] Filter on whether an alert has notes. The accepted operator is 'is'.
        # @param tags [Hash{String => Array<String>}] Filter on the tags applied to an alert, by tag name. The accepted operators are 'one_of', 'all_of' and 'not_in'.
        # @param include_maintenance_window [Hash{String => Array<String>}] Filter on whether to include maintenance window alerts. The accepted operator is 'is'.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::AlertV2>]
        def list(
          page_size:,
          after: nil,
          deduplication_key: nil,
          status: nil,
          alert_source: nil,
          alert_group_id: nil,
          created_at: nil,
          updated_at: nil,
          attributes: nil,
          has_notes: nil,
          tags: nil,
          include_maintenance_window: nil,
          request_options: {}
        )
          paginate(
            "/v2/alerts",
            items_key: "alerts",
            query: {
              page_size:,
              after:,
              deduplication_key:,
              status:,
              alert_source:,
              alert_group_id:,
              created_at:,
              updated_at:,
              attributes:,
              has_notes:,
              tags:,
              include_maintenance_window:
            },
            model: Models::AlertV2,
            request_options:
          )
        end

        # List the alert tags in your organisation's vocabulary
        #
        # List the alert tags in your organisation's vocabulary.
        #
        # Alert tags are the reusable labels you can apply to alerts. This endpoint lists the
        # organisation's active tags, ordered by name, and excludes archived tags.
        #
        # To narrow the list, filter by search, which matches tags whose name contains the given
        # value (case-insensitive):
        #
        # 		curl --get 'https://api.incident.io/v2/alert_tags' \
        # 			--data 'search=noisy'
        #
        # Endpoint: `GET /v2/alert_tags`. Scopes: alerts.view.
        #
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] A tag's ID. This endpoint will return a list of tags after this ID in relation to the API response order.
        # @param search [String] Filter to tags whose name contains this value (case-insensitive)
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::AlertTagV2>]
        def list_alert_tags(page_size: nil, after: nil, search: nil, request_options: {})
          paginate(
            "/v2/alert_tags",
            items_key: "alert_tags",
            query: {page_size:, after:, search:},
            model: Models::AlertTagV2,
            request_options:
          )
        end

        # List the connections between incidents and alerts
        #
        # Endpoint: `GET /v2/incident_alerts`. Scopes: alerts.view.
        #
        # @param page_size [Integer] Number of incident alerts to return per page.
        # @param after [String] If provided, pass this as the 'after' param to load the next page.
        # @param alert_id [String] Alert that this incident alert refers to.
        # @param incident_id [String] Incident that this incident alert is attached to.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::IncidentAlertV2>]
        def list_incident_alerts(page_size:, after: nil, alert_id: nil, incident_id: nil, request_options: {})
          paginate(
            "/v2/incident_alerts",
            items_key: "incident_alerts",
            query: {page_size:, after:, alert_id:, incident_id:},
            model: Models::IncidentAlertV2,
            request_options:
          )
        end

        # Remove tags from an alert without changing its other tags
        #
        # Remove tags from an alert without changing its other tags.
        #
        # Each tag is a name. Tags that are not present on the alert are ignored.
        #
        # Endpoint: `POST /v2/alerts/{id}/actions/remove_tags`. Scopes: alerts.edit.
        #
        # @param id [String] Unique identifier for the alert.
        # @param tags [Array<String>] Tag names to remove from this alert.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::AlertV2]
        def remove_tags(id, tags:, request_options: {})
          request(
            :post,
            path("/v2/alerts/%s/actions/remove_tags", id),
            body: given({tags:}),
            unwrap: "alert",
            model: Models::AlertV2,
            request_options:
          )
        end

        # Resolve a currently firing alert
        #
        # Resolve a currently firing alert.
        #
        # This marks the alert as resolved with the current time, attributing the resolution to the API key that made the request. Resolving an already-resolved alert is a no-op and returns the alert unchanged.
        #
        # Some alert sources are 'externally resolved' (for example, Datadog) — those alerts can only be resolved by the third-party system itself, and this endpoint will return a 422 explaining that.
        #
        # Private alerts: an API key without the 'view all alerts' scope can only resolve non-private alerts; private alerts will return a 404. Grant the API key a role that includes the global alerts access scope to resolve private alerts.
        #
        # Endpoint: `POST /v2/alerts/{id}/actions/resolve`. Scopes: alerts.resolve.
        #
        # @param id [String] Unique identifier for the alert.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::AlertV2]
        def resolve(id, request_options: {})
          request(
            :post,
            path("/v2/alerts/%s/actions/resolve", id),
            unwrap: "alert",
            model: Models::AlertV2,
            request_options:
          )
        end

        # Replace all tags on an alert
        #
        # Replace all tags on an alert.
        #
        # Each tag is a name. A name that does not exist is created, except on private alerts,
        # where only names already in the organisation's tag vocabulary can be used. Passing an
        # empty list removes every tag.
        #
        # Endpoint: `POST /v2/alerts/{id}/actions/set_tags`. Scopes: alerts.edit.
        #
        # @param id [String] Unique identifier for the alert.
        # @param tags [Array<String>] The complete set of tag names for this alert.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::AlertV2]
        def set_tags(id, tags:, request_options: {})
          request(
            :post,
            path("/v2/alerts/%s/actions/set_tags", id),
            body: given({tags:}),
            unwrap: "alert",
            model: Models::AlertV2,
            request_options:
          )
        end

        # Show a single alert for your account
        #
        # Endpoint: `GET /v2/alerts/{id}`. Scopes: alerts.view.
        #
        # @param id [String] Unique identifier for the alert.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::AlertV2]
        def show(id, request_options: {})
          request(
            :get,
            path("/v2/alerts/%s", id),
            unwrap: "alert",
            model: Models::AlertV2,
            request_options:
          )
        end

        # Confirm or detach the connection between an alert and an incident
        #
        # Confirm or detach the connection between an alert and an incident.
        #
        # Set state to 'related' to confirm the connection, or 'unrelated' to detach the alert from
        # the incident. The API key also needs the 'manage incident alerts' scope.
        #
        # A detached connection no longer appears in the list endpoint, which returns related
        # connections only.
        #
        # Busy incidents can be locked by another operation, in which case this endpoint returns a
        # 409 and the request can be retried.
        #
        # Endpoint: `POST /v2/incident_alerts/{id}/actions/transition`. Scopes: incident_alerts.transition.
        #
        # @param id [String] Unique identifier for the incident alert.
        # @param state [String] What state to move the connection to One of: related, unrelated.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentAlertV2]
        def transition_incident_alert(id, state:, request_options: {})
          request(
            :post,
            path("/v2/incident_alerts/%s/actions/transition", id),
            body: given({state:}),
            unwrap: "incident_alert",
            model: Models::IncidentAlertV2,
            request_options:
          )
        end
      end
    end
  end
end
