# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V2
      # Create alerts within incident.io.
      #
      # The alerts API allows you to create alerts within incident.io by posting alert events. You
      # can use alerts to automatically trigger incidents.
      #
      # To create an alert, you must first configure an alert source in the incident.io dashboard.
      class AlertEvents < Resource
        # Create an alert event using an HTTP source
        #
        # Endpoint: `POST /v2/alert_events/http/{alert_source_config_id}`.
        # Does not use your API key; pass the alert source token instead.
        #
        # @param alert_source_config_id [String] Which alert source config produced this alert.
        # @param status [String] Current status of this alert One of: firing, resolved.
        # @param title [String] The title of the alert, parsed from the alert payload according to the alert source configuration.
        # @param token [String] Token used to authenticate the request, generated when configuring the alert source. Will be consumed via a URL query string parameter.
        # @param query [Hash] Query parameters.
        # @param deduplication_key [String] A deduplication key which uniquely references this alert from your alert source. For newly created HTTP sources, this field is required. If you send an event with the same deduplication_key multiple times, only one alert will be created in incident.io for this alert source config. You can filter on this field to find the alert created by an event you've sent us.
        # @param description [String] Description that optionally adds more detail to title. Supports markdown.
        # @param metadata [Hash] Any additional metadata that you've configured your alert source to parse.
        # @param source_url [String] If applicable, a link to the alert in the upstream system.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::AlertEventsCreateHTTPResultV2]
        def create_http(
          alert_source_config_id,
          status:,
          title:,
          token: nil,
          query: nil,
          deduplication_key: NOT_GIVEN,
          description: NOT_GIVEN,
          metadata: NOT_GIVEN,
          source_url: NOT_GIVEN,
          request_options: {}
        )
          request(
            :post,
            path("/v2/alert_events/http/%s", alert_source_config_id),
            query: {token:, query:},
            body: given({deduplication_key:, description:, metadata:, source_url:, status:, title:}),
            model: Models::AlertEventsCreateHTTPResultV2,
            request_options:
          )
        end
      end
    end
  end
end
