# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V2
      # Create and manage announcement rules.
      #
      # An announcement rule posts an announcement of each incident that matches its conditions
      # into the channels it lists, rendered with an announcement template.
      class AnnouncementRules < Resource
        # Create an announcement rule
        #
        # Endpoint: `POST /v2/announcement_rules`. Scopes: announcement_rules.create.
        #
        # @param condition_groups [Array<Models::ConditionGroupPayloadV2, Hash>] Incidents are announced when they match any of these condition groups.
        # @param mode [String] Which incidents are announced: live incidents only, or triage incidents too One of: live_and_closed, include_triage, include_triage_and_merged, include_declined_and_merged, include_all.
        # @param name [String] Human readable name for the rule.
        # @param update_sharing_mode [String] Where incident updates are shared once the incident is announced One of: none, thread, thread_and_channel.
        # @param conditions_no_longer_apply_behaviour [String] Whether to remove announcement posts when the incident no longer matches this rule's conditions. Defaults to leaving them in place. One of: leave_in_place, remove.
        # @param microsoft_teams_channel_ids [Array<String>] Microsoft Teams channels to post announcements into, as team_id/channel_id. Required when the organisation uses Microsoft Teams.
        # @param owning_team_ids [Array<String>] IDs of the teams that own this rule.
        # @param private_incident_scope [String] Which private incidents this rule announces: every private incident (all), those an owning team can see (owning_teams), or none. Defaults to none on create, and is left unchanged on update when omitted. One of: all, owning_teams, none.
        # @param slack_channel_ids [Array<String>] IDs of the Slack channels to post announcements into. Required when the organisation uses Slack.
        # @param template_id [String] ID of the announcement template used to render this rule's posts. Defaults to the organisation's default template when omitted.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::AnnouncementRuleV2]
        def create(
          condition_groups:,
          mode:,
          name:,
          update_sharing_mode:,
          conditions_no_longer_apply_behaviour: NOT_GIVEN,
          microsoft_teams_channel_ids: NOT_GIVEN,
          owning_team_ids: NOT_GIVEN,
          private_incident_scope: NOT_GIVEN,
          slack_channel_ids: NOT_GIVEN,
          template_id: NOT_GIVEN,
          request_options: {}
        )
          request(
            :post,
            "/v2/announcement_rules",
            body: given({
              condition_groups:,
              conditions_no_longer_apply_behaviour:,
              microsoft_teams_channel_ids:,
              mode:,
              name:,
              owning_team_ids:,
              private_incident_scope:,
              slack_channel_ids:,
              template_id:,
              update_sharing_mode:
            }),
            unwrap: "announcement_rule",
            model: Models::AnnouncementRuleV2,
            request_options:
          )
        end

        # Delete an announcement rule
        #
        # Endpoint: `DELETE /v2/announcement_rules/{id}`. Scopes: announcement_rules.destroy.
        #
        # @param id [String] Unique identifier for this announcement rule.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def destroy(id, request_options: {})
          request(
            :delete,
            path("/v2/announcement_rules/%s", id),
            request_options:
          )
        end

        # List announcement rules for this organisation
        #
        # Endpoint: `GET /v2/announcement_rules`. Scopes: announcement_rules.view.
        #
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] An announcement rule's ID.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::AnnouncementRuleV2>]
        def list(page_size: nil, after: nil, request_options: {})
          paginate(
            "/v2/announcement_rules",
            items_key: "announcement_rules",
            query: {page_size:, after:},
            model: Models::AnnouncementRuleV2,
            request_options:
          )
        end

        # Show an announcement rule
        #
        # Endpoint: `GET /v2/announcement_rules/{id}`. Scopes: announcement_rules.view.
        #
        # @param id [String] Unique identifier for this announcement rule.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::AnnouncementRuleV2]
        def show(id, request_options: {})
          request(
            :get,
            path("/v2/announcement_rules/%s", id),
            unwrap: "announcement_rule",
            model: Models::AnnouncementRuleV2,
            request_options:
          )
        end

        # Update an announcement rule
        #
        # Endpoint: `PUT /v2/announcement_rules/{id}`. Scopes: announcement_rules.update.
        #
        # @param id [String] Unique identifier for this announcement rule.
        # @param condition_groups [Array<Models::ConditionGroupPayloadV2, Hash>] Incidents are announced when they match any of these condition groups.
        # @param mode [String] Which incidents are announced: live incidents only, or triage incidents too One of: live_and_closed, include_triage, include_triage_and_merged, include_declined_and_merged, include_all.
        # @param name [String] Human readable name for the rule.
        # @param update_sharing_mode [String] Where incident updates are shared once the incident is announced One of: none, thread, thread_and_channel.
        # @param conditions_no_longer_apply_behaviour [String] Whether to remove announcement posts when the incident no longer matches this rule's conditions. Defaults to leaving them in place. One of: leave_in_place, remove.
        # @param microsoft_teams_channel_ids [Array<String>] Microsoft Teams channels to post announcements into, as team_id/channel_id. Required when the organisation uses Microsoft Teams.
        # @param owning_team_ids [Array<String>] IDs of the teams that own this rule. The existing owning teams are kept when omitted.
        # @param private_incident_scope [String] Which private incidents this rule announces: every private incident (all), those an owning team can see (owning_teams), or none. Defaults to none on create, and is left unchanged on update when omitted. One of: all, owning_teams, none.
        # @param slack_channel_ids [Array<String>] IDs of the Slack channels to post announcements into. Required when the organisation uses Slack.
        # @param template_id [String] ID of the announcement template used to render this rule's posts. The existing template is kept when omitted.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::AnnouncementRuleV2]
        def update(
          id,
          condition_groups:,
          mode:,
          name:,
          update_sharing_mode:,
          conditions_no_longer_apply_behaviour: NOT_GIVEN,
          microsoft_teams_channel_ids: NOT_GIVEN,
          owning_team_ids: NOT_GIVEN,
          private_incident_scope: NOT_GIVEN,
          slack_channel_ids: NOT_GIVEN,
          template_id: NOT_GIVEN,
          request_options: {}
        )
          request(
            :put,
            path("/v2/announcement_rules/%s", id),
            body: given({
              condition_groups:,
              conditions_no_longer_apply_behaviour:,
              microsoft_teams_channel_ids:,
              mode:,
              name:,
              owning_team_ids:,
              private_incident_scope:,
              slack_channel_ids:,
              template_id:,
              update_sharing_mode:
            }),
            unwrap: "announcement_rule",
            model: Models::AnnouncementRuleV2,
            request_options:
          )
        end
      end
    end
  end
end
