# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V2
      # Manage and browse catalog resources.
      #
      # These endpoints have been deprecated in favour of CatalogV3. The only breaking change is
      # that the 'manual' attribute mode is now split into 'api' and 'dashboard'. We also removed
      # the usage of some types that were deprecated in the V2 API.
      #
      # Use the incident.io catalog to track services, teams, product features and anything
      # else that helps build a map of your organisation. These different categories of thing
      # become catalog types, and each instance (like a particular service or team) is a
      # catalog entry.
      #
      # Each type is made up of a series of attributes, and each attribute has a type. Types
      # can even have attributes that refer to other catalog types.
      #
      # We automatically create catalog types when you connect an integration, such as GitHub
      # repositories or PagerDuty services and teams. You can use this API to create custom
      # types, that are specifically tailored to your organisation.
      #
      # Examples might be a 'Service' type with an 'Alert channel' which you can point at a
      # Slack channel, or 'Team' which specifies its 'Manager' and 'Technical Lead' as Slack
      # users. You can then use these types to create powerful new workflows.
      #
      # Consider using our official [catalog importer](https://github.com/incident-io/catalog-importer).
      # It can be used to sync catalog data from sources like local files or GitHub and push
      # them into the incident.io catalog without having to directly interact with our public API.
      class Catalog < Resource
        # Create an entry within the catalog. We support a maximum of 50,000 entries per type.
        #
        # If you call this API with a payload where the external_id and catalog_type_id match an existing entry, the existing entry will be updated.
        #
        # Endpoint: `POST /v2/catalog_entries`. Scopes: catalog_entries.create.
        #
        # @deprecated Use `client.catalog.create_entry` instead.
        # @param attribute_values [Hash{String => Models::EngineParamBindingPayloadV2}] Values of this entry.
        # @param catalog_type_id [String] ID of this catalog type.
        # @param name [String] Name is the human readable name of this entry.
        # @param aliases [Array<String>] Optional aliases that can be used to reference this entry.
        # @param external_id [String] An optional alternative ID for this entry, which is ensured to be unique for the type.
        # @param rank [Integer] When catalog type is ranked, this is used to help order things.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogEntryV2]
        def create_entry(
          attribute_values:,
          catalog_type_id:,
          name:,
          aliases: NOT_GIVEN,
          external_id: NOT_GIVEN,
          rank: NOT_GIVEN,
          request_options: {}
        )
          deprecated!("client.v2.catalog.create_entry", "client.catalog.create_entry")
          request(
            :post,
            "/v2/catalog_entries",
            body: given({aliases:, attribute_values:, catalog_type_id:, external_id:, name:, rank:}),
            unwrap: "catalog_entry",
            model: Models::CatalogEntryV2,
            request_options:
          )
        end

        # Create a catalog type. The schema must be updated using the UpdateTypeSchema endpoint.
        #
        # Endpoint: `POST /v2/catalog_types`. Scopes: catalog_types.create.
        #
        # @deprecated Use `client.catalog.create_type` instead.
        # @param description [String] Human readble description of this type.
        # @param name [String] Name is the human readable name of this type.
        # @param annotations [Hash{String => String}] Annotations that can track metadata about this type.
        # @param categories [Array<String>] What categories is this type considered part of One of: customer, issue-tracker, product-feature, service, on-call, team, user.
        # @param color [String] Sets the display color of this type in the dashboard One of: yellow, green, blue, violet, pink, cyan, orange.
        # @param icon [String] Sets the display icon of this type in the dashboard One of: alert, bolt, box, briefcase, browser, bulb, calendar, clock, cog, components, database, doc, email, escalation-path, files, flag, folder, globe, incident-template, money, server, severity, status-page, store, star, tag, user, users.
        # @param ranked [Boolean] If this type should be ranked.
        # @param source_repo_url [String] The url of the external repository where this type is managed.
        # @param type_name [String] The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"].
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogTypeV2]
        def create_type(
          description:,
          name:,
          annotations: NOT_GIVEN,
          categories: NOT_GIVEN,
          color: NOT_GIVEN,
          icon: NOT_GIVEN,
          ranked: NOT_GIVEN,
          source_repo_url: NOT_GIVEN,
          type_name: NOT_GIVEN,
          request_options: {}
        )
          deprecated!("client.v2.catalog.create_type", "client.catalog.create_type")
          request(
            :post,
            "/v2/catalog_types",
            body: given({
              annotations:,
              categories:,
              color:,
              description:,
              icon:,
              name:,
              ranked:,
              source_repo_url:,
              type_name:
            }),
            unwrap: "catalog_type",
            model: Models::CatalogTypeV2,
            request_options:
          )
        end

        # Archives a catalog entry.
        #
        # Endpoint: `DELETE /v2/catalog_entries/{id}`. Scopes: catalog_entries.destroy.
        #
        # @deprecated Use `client.catalog.destroy_entry` instead.
        # @param id [String] ID of this catalog entry.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def destroy_entry(id, request_options: {})
          deprecated!("client.v2.catalog.destroy_entry", "client.catalog.destroy_entry")
          request(
            :delete,
            path("/v2/catalog_entries/%s", id),
            request_options:
          )
        end

        # Archives a catalog type and associated entries.
        #
        # Endpoint: `DELETE /v2/catalog_types/{id}`. Scopes: catalog_types.destroy.
        #
        # @deprecated Use `client.catalog.destroy_type` instead.
        # @param id [String] ID of this catalog type.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def destroy_type(id, request_options: {})
          deprecated!("client.v2.catalog.destroy_type", "client.catalog.destroy_type")
          request(
            :delete,
            path("/v2/catalog_types/%s", id),
            request_options:
          )
        end

        # List entries for a catalog type.
        #
        # Endpoint: `GET /v2/catalog_entries`. Scopes: catalog_entries.view.
        #
        # @deprecated Use `client.catalog.list_entries` instead.
        # @param catalog_type_id [String] ID of this catalog type.
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::CatalogEntryV2>]
        def list_entries(catalog_type_id:, page_size: nil, after: nil, request_options: {})
          deprecated!("client.v2.catalog.list_entries", "client.catalog.list_entries")
          paginate(
            "/v2/catalog_entries",
            items_key: "catalog_entries",
            query: {catalog_type_id:, page_size:, after:},
            model: Models::CatalogEntryV2,
            request_options:
          )
        end

        # List available engine resources for the catalog.
        #
        # A resource represents a type of data that can be held within the catalog, so this
        # endpoint can be used to see what attribute types can be used when updating the
        # schema of a catalog type.
        #
        # Endpoint: `GET /v2/catalog_resources`. Scopes: catalog_types.view.
        #
        # @deprecated Use `client.catalog.list_resources` instead.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Array<Models::CatalogResourceV2>]
        def list_resources(request_options: {})
          deprecated!("client.v2.catalog.list_resources", "client.catalog.list_resources")
          request(
            :get,
            "/v2/catalog_resources",
            unwrap: "resources",
            model: [Models::CatalogResourceV2],
            request_options:
          )
        end

        # List all catalog types for an organisation, including those synced from external resources.
        #
        # Endpoint: `GET /v2/catalog_types`. Scopes: catalog_types.view.
        #
        # @deprecated Use `client.catalog.list_types` instead.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Array<Models::CatalogTypeV2>]
        def list_types(request_options: {})
          deprecated!("client.v2.catalog.list_types", "client.catalog.list_types")
          request(
            :get,
            "/v2/catalog_types",
            unwrap: "catalog_types",
            model: [Models::CatalogTypeV2],
            request_options:
          )
        end

        # Show a single catalog entry.
        #
        # Endpoint: `GET /v2/catalog_entries/{id}`. Scopes: catalog_entries.view.
        #
        # @deprecated Use `client.catalog.show_entry` instead.
        # @param id [String] ID of this catalog entry.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogShowEntryResultV2]
        def show_entry(id, request_options: {})
          deprecated!("client.v2.catalog.show_entry", "client.catalog.show_entry")
          request(
            :get,
            path("/v2/catalog_entries/%s", id),
            model: Models::CatalogShowEntryResultV2,
            request_options:
          )
        end

        # Show a single catalog type.
        #
        # Endpoint: `GET /v2/catalog_types/{id}`. Scopes: catalog_types.view.
        #
        # @deprecated Use `client.catalog.show_type` instead.
        # @param id [String] ID of this catalog type.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogTypeV2]
        def show_type(id, request_options: {})
          deprecated!("client.v2.catalog.show_type", "client.catalog.show_type")
          request(
            :get,
            path("/v2/catalog_types/%s", id),
            unwrap: "catalog_type",
            model: Models::CatalogTypeV2,
            request_options:
          )
        end

        # Updates an existing catalog entry.
        #
        # Endpoint: `PUT /v2/catalog_entries/{id}`. Scopes: catalog_entries.edit.
        #
        # @deprecated Use `client.catalog.update_entry` instead.
        # @param id [String] ID of this catalog entry.
        # @param attribute_values [Hash{String => Models::EngineParamBindingPayloadV2}] Values of this entry.
        # @param name [String] Name is the human readable name of this entry.
        # @param aliases [Array<String>] Optional aliases that can be used to reference this entry.
        # @param external_id [String] An optional alternative ID for this entry, which is ensured to be unique for the type.
        # @param rank [Integer] When catalog type is ranked, this is used to help order things.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogUpdateEntryResultV2]
        def update_entry(
          id,
          attribute_values:,
          name:,
          aliases: NOT_GIVEN,
          external_id: NOT_GIVEN,
          rank: NOT_GIVEN,
          request_options: {}
        )
          deprecated!("client.v2.catalog.update_entry", "client.catalog.update_entry")
          request(
            :put,
            path("/v2/catalog_entries/%s", id),
            body: given({aliases:, attribute_values:, external_id:, name:, rank:}),
            model: Models::CatalogUpdateEntryResultV2,
            request_options:
          )
        end

        # Updates an existing catalog type. The schema must be updated using the UpdateTypeSchema endpoint.
        #
        # Endpoint: `PUT /v2/catalog_types/{id}`. Scopes: catalog_types.edit.
        #
        # @deprecated Use `client.catalog.update_type` instead.
        # @param id [String] ID of this catalog type.
        # @param description [String] Human readble description of this type.
        # @param name [String] Name is the human readable name of this type.
        # @param annotations [Hash{String => String}] Annotations that can track metadata about this type.
        # @param categories [Array<String>] What categories is this type considered part of One of: customer, issue-tracker, product-feature, service, on-call, team, user.
        # @param color [String] Sets the display color of this type in the dashboard One of: yellow, green, blue, violet, pink, cyan, orange.
        # @param icon [String] Sets the display icon of this type in the dashboard One of: alert, bolt, box, briefcase, browser, bulb, calendar, clock, cog, components, database, doc, email, escalation-path, files, flag, folder, globe, incident-template, money, server, severity, status-page, store, star, tag, user, users.
        # @param ranked [Boolean] If this type should be ranked.
        # @param source_repo_url [String] The url of the external repository where this type is managed.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogTypeV2]
        def update_type(
          id,
          description:,
          name:,
          annotations: NOT_GIVEN,
          categories: NOT_GIVEN,
          color: NOT_GIVEN,
          icon: NOT_GIVEN,
          ranked: NOT_GIVEN,
          source_repo_url: NOT_GIVEN,
          request_options: {}
        )
          deprecated!("client.v2.catalog.update_type", "client.catalog.update_type")
          request(
            :put,
            path("/v2/catalog_types/%s", id),
            body: given({
              annotations:,
              categories:,
              color:,
              description:,
              icon:,
              name:,
              ranked:,
              source_repo_url:
            }),
            unwrap: "catalog_type",
            model: Models::CatalogTypeV2,
            request_options:
          )
        end

        # Update an existing catalog types schema, adding or removing attributes.
        #
        # Updating the schema is handled separately from creating and updating types, so that you don't
        # have to worry about dependencies between types. For example, if type A has an attribute that
        # relies on type B, you would have to create type B first.
        #
        # By allowing the creation of types without a schema, they can be created in any order, but it
        # means that you need to make a separate call to this endpoint to update the schema.
        #
        # Endpoint: `POST /v2/catalog_types/{id}/actions/update_schema`. Scopes: catalog_types.edit.
        #
        # @deprecated Use `client.catalog.update_type_schema` instead.
        # @param id [String] ID of this catalog type.
        # @param attributes [Array<Models::CatalogTypeAttributePayloadV2, Hash>]
        # @param version [Integer]
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CatalogTypeV2]
        def update_type_schema(id, attributes:, version:, request_options: {})
          deprecated!("client.v2.catalog.update_type_schema", "client.catalog.update_type_schema")
          request(
            :post,
            path("/v2/catalog_types/%s/actions/update_schema", id),
            body: given({attributes:, version:}),
            unwrap: "catalog_type",
            model: Models::CatalogTypeV2,
            request_options:
          )
        end
      end
    end
  end
end
