# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V2
      # Manage custom fields.
      #
      # Custom fields are used to attach metadata to incidents, which you can use when searching
      # for incidents in the dashboard, triggering workflows, building announcement rules or for
      # your own data needs.
      #
      # Each field has a type:
      #
      # - Single-select, single value selected from a predefined list of options (e.g. Detection Method)
      # - Multi-select, as above but you can pick more than one option (e.g. Affected Teams)
      # - Text, freeform text field (e.g. Customer ID)
      # - Link, link URL that is synced to Slack bookmarks on the incident channel (e.g. External Status Page)
      # - Number, integer or fractional numbers (e.g. # Customers Affected)
      #
      # We may add more custom field types in the future - we'd love to hear any other types you'd like to use!
      class CustomFields < Resource
        # Create a new custom field
        #
        # Endpoint: `POST /v2/custom_fields`. Scopes: organisation_settings.update.
        #
        # @param description [String] Description of the custom field.
        # @param field_type [String] Type of custom field One of: single_select, multi_select, text, link, numeric.
        # @param name [String] Human readable name for the custom field.
        # @param catalog_type_id [String] For catalog fields, the ID of the associated catalog type.
        # @param filter_by [Models::CustomFieldFilterByOptionsV2, Hash]
        # @param fixed_filter [Models::CustomFieldFixedFilterOptionsV2, Hash]
        # @param group_by_catalog_attribute_id [String] For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
        # @param helptext_catalog_attribute_id [String] Which catalog attribute provides helptext for the options.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CustomFieldV2]
        def create(
          description:,
          field_type:,
          name:,
          catalog_type_id: nil,
          filter_by: nil,
          fixed_filter: nil,
          group_by_catalog_attribute_id: nil,
          helptext_catalog_attribute_id: nil,
          request_options: {}
        )
          request(
            :post,
            "/v2/custom_fields",
            body: {
              catalog_type_id:,
              description:,
              field_type:,
              filter_by:,
              fixed_filter:,
              group_by_catalog_attribute_id:,
              helptext_catalog_attribute_id:,
              name:
            }.compact,
            unwrap: "custom_field",
            model: Models::CustomFieldV2,
            request_options:
          )
        end

        # Delete a custom field
        #
        # Endpoint: `DELETE /v2/custom_fields/{id}`. Scopes: organisation_settings.update.
        #
        # @param id [String] Unique identifier for the custom field.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def delete(id, request_options: {})
          request(
            :delete,
            path("/v2/custom_fields/%s", id),
            request_options:
          )
        end

        # List all custom fields for an organisation.
        #
        # Endpoint: `GET /v2/custom_fields`. Scopes: custom_fields.view.
        #
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Array<Models::CustomFieldV2>]
        def list(request_options: {})
          request(
            :get,
            "/v2/custom_fields",
            unwrap: "custom_fields",
            model: [Models::CustomFieldV2],
            request_options:
          )
        end

        # Get a single custom field.
        #
        # Endpoint: `GET /v2/custom_fields/{id}`. Scopes: custom_fields.view.
        #
        # @param id [String] Unique identifier for the custom field.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CustomFieldV2]
        def show(id, request_options: {})
          request(
            :get,
            path("/v2/custom_fields/%s", id),
            unwrap: "custom_field",
            model: Models::CustomFieldV2,
            request_options:
          )
        end

        # Update the details of a custom field
        #
        # Endpoint: `PUT /v2/custom_fields/{id}`. Scopes: organisation_settings.update.
        #
        # @param id [String] Unique identifier for the custom field.
        # @param description [String] Description of the custom field.
        # @param name [String] Human readable name for the custom field.
        # @param filter_by [Models::CustomFieldFilterByOptionsV2, Hash]
        # @param fixed_filter [Models::CustomFieldFixedFilterOptionsV2, Hash]
        # @param group_by_catalog_attribute_id [String] For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
        # @param helptext_catalog_attribute_id [String] Which catalog attribute provides helptext for the options.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::CustomFieldV2]
        def update(
          id,
          description:,
          name:,
          filter_by: nil,
          fixed_filter: nil,
          group_by_catalog_attribute_id: nil,
          helptext_catalog_attribute_id: nil,
          request_options: {}
        )
          request(
            :put,
            path("/v2/custom_fields/%s", id),
            body: {
              description:,
              filter_by:,
              fixed_filter:,
              group_by_catalog_attribute_id:,
              helptext_catalog_attribute_id:,
              name:
            }.compact,
            unwrap: "custom_field",
            model: Models::CustomFieldV2,
            request_options:
          )
        end
      end
    end
  end
end
