# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V2
      # Create and manage reusable, parameterised escalation path templates.
      #
      # An escalation path template declares parameters and a binding-aware path. Escalation
      # paths built from a template bind those parameters to concrete values.
      class EscalationPathTemplates < Resource
        # Create a new escalation path template.
        #
        # Endpoint: `POST /v2/escalation_path_templates`. Scopes: escalation_path_templates.create.
        #
        # @param name [String] The name of this template, for the user's reference.
        # @param path [Array<Models::EscalationPathTemplateNodePayloadV2, Hash>] The nodes that form the levels and branches of this template.
        # @param description [String] A description of what this template is for.
        # @param expressions [Array<Models::ExpressionPayloadV2, Hash>] Expressions backing the template's binding targets.
        # @param params [Array<Models::EngineParamV2, Hash>] The parameters declared by this template, bound per templated path.
        # @param repeat_config [Models::EscalationPathRepeatConfigV2, Hash]
        # @param working_hours [Array<Models::WeekdayIntervalConfigV2, Hash>] The working hours for this template.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::EscalationPathTemplateV2]
        def create(
          name:,
          path:,
          description: NOT_GIVEN,
          expressions: NOT_GIVEN,
          params: NOT_GIVEN,
          repeat_config: NOT_GIVEN,
          working_hours: NOT_GIVEN,
          request_options: {}
        )
          request(
            :post,
            "/v2/escalation_path_templates",
            body: given({description:, expressions:, name:, params:, path:, repeat_config:, working_hours:}),
            unwrap: "escalation_path_template",
            model: Models::EscalationPathTemplateV2,
            request_options:
          )
        end

        # Archives a particular escalation path template.
        #
        # Endpoint: `DELETE /v2/escalation_path_templates/{id}`. Scopes: escalation_path_templates.destroy.
        #
        # @param id [String] Unique identifier for this template.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def destroy(id, request_options: {})
          request(
            :delete,
            path("/v2/escalation_path_templates/%s", id),
            request_options:
          )
        end

        # List active escalation path templates.
        #
        # Endpoint: `GET /v2/escalation_path_templates`. Scopes: escalation_path_templates.view.
        #
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.
        # @param search [String] Search query to filter results by name.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::EscalationPathTemplateV2>]
        def list(page_size: nil, after: nil, search: nil, request_options: {})
          paginate(
            "/v2/escalation_path_templates",
            items_key: "escalation_path_templates",
            query: {page_size:, after:, search:},
            model: Models::EscalationPathTemplateV2,
            request_options:
          )
        end

        # Show a particular escalation path template.
        #
        # Endpoint: `GET /v2/escalation_path_templates/{id}`. Scopes: escalation_path_templates.view.
        #
        # @param id [String] Unique identifier for this template.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::EscalationPathTemplateV2]
        def show(id, request_options: {})
          request(
            :get,
            path("/v2/escalation_path_templates/%s", id),
            unwrap: "escalation_path_template",
            model: Models::EscalationPathTemplateV2,
            request_options:
          )
        end

        # Update a particular escalation path template.
        #
        # Endpoint: `PUT /v2/escalation_path_templates/{id}`. Scopes: escalation_path_templates.update.
        #
        # @param id [String] Unique identifier for this template.
        # @param name [String] The name of this template, for the user's reference.
        # @param path [Array<Models::EscalationPathTemplateNodePayloadV2, Hash>] The nodes that form the levels and branches of this template.
        # @param description [String] A description of what this template is for.
        # @param expressions [Array<Models::ExpressionPayloadV2, Hash>] Expressions backing the template's binding targets.
        # @param params [Array<Models::EngineParamV2, Hash>] The parameters declared by this template, bound per templated path.
        # @param repeat_config [Models::EscalationPathRepeatConfigV2, Hash]
        # @param working_hours [Array<Models::WeekdayIntervalConfigV2, Hash>] The working hours for this template.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::EscalationPathTemplateV2]
        def update(
          id,
          name:,
          path:,
          description: NOT_GIVEN,
          expressions: NOT_GIVEN,
          params: NOT_GIVEN,
          repeat_config: NOT_GIVEN,
          working_hours: NOT_GIVEN,
          request_options: {}
        )
          request(
            :put,
            path("/v2/escalation_path_templates/%s", id),
            body: given({description:, expressions:, name:, params:, path:, repeat_config:, working_hours:}),
            unwrap: "escalation_path_template",
            model: Models::EscalationPathTemplateV2,
            request_options:
          )
        end
      end
    end
  end
end
