# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V2
      # Read and write the items on an incident's timeline.
      #
      # The timeline is the curated narrative of an incident: the handful of moments that explain what
      # happened, rather than the activity log, which records everything that did. Items are either
      # promoted or custom. Promoted items are activity lifted onto the timeline - a pinned message,
      # an escalation, an incident update, an event added by a workflow - and carry the ID of the
      # activity log entry they came from. Custom items are written by hand, in the dashboard or
      # through this API, and have no activity_log_id.
      #
      # Use this to pull an incident's narrative into your own systems - a retrospective template, a
      # report, a record you keep outside incident.io - and to put the things you know about back on
      # it, like a deploy, a config change or a load test you halted.
      class IncidentTimelineItems < Resource
        # Add a custom item to an incident's timeline
        #
        # Add a custom item to an incident's timeline.
        #
        # Items created here are custom, so they carry no activity_log_id and their timestamp stays
        # editable. Set it to when the thing actually happened rather than when you're telling us about
        # it - a deploy you shipped an hour ago belongs an hour back on the timeline.
        #
        # Every request needs an idempotency_key. Retrying with a key we've already seen returns the
        # item the first request created rather than writing a second one, so an automation that
        # retries on a timeout doesn't leave a duplicate behind.
        #
        # Endpoint: `POST /v2/incident_timeline_items`. Scopes: timeline_items.create.
        #
        # @param incident_id [String] Incident to add this item to.
        # @param timestamp [Time] When the thing this item describes happened. This is where the item sits on the timeline, and can be in the past.
        # @param title [String] Title of the timeline item.
        # @param description [String] Description of the timeline item, in markdown.
        # @param idempotency_key [String] Unique string used to de-duplicate timeline item requests. Retrying with the same key returns the item the first request created, rather than adding a second one. Generated when not given.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentTimelineItemV2]
        def create(
          incident_id:,
          timestamp:,
          title:,
          description: NOT_GIVEN,
          idempotency_key: SecureRandom.uuid,
          request_options: {}
        )
          request(
            :post,
            "/v2/incident_timeline_items",
            body: given({description:, idempotency_key:, incident_id:, timestamp:, title:}),
            idempotent: true,
            unwrap: "incident_timeline_item",
            model: Models::IncidentTimelineItemV2,
            request_options:
          )
        end

        # List the timeline items for an incident, oldest first
        #
        # List the timeline items for an incident, oldest first.
        #
        # Items are ordered by timestamp, then by ID to break ties, which is the order the dashboard
        # shows them in. If the incident has streams, this returns the items on its streams too -
        # they're part of the same narrative - and incident_id on each item tells you which stream it
        # came from.
        #
        # Items can be edited after they're written, and this endpoint always returns their current
        # state, so listing an incident again gives you the timeline as it stands today.
        #
        # Endpoint: `GET /v2/incident_timeline_items`. Scopes: incidents.view.
        #
        # @param incident_id [String] Incident whose timeline you want to list.
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] A timeline item's ID. This endpoint returns the items that follow it.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::IncidentTimelineItemV2>]
        def list(incident_id:, page_size: nil, after: nil, request_options: {})
          paginate(
            "/v2/incident_timeline_items",
            items_key: "incident_timeline_items",
            query: {incident_id:, page_size:, after:},
            model: Models::IncidentTimelineItemV2,
            request_options:
          )
        end

        # Edit a timeline item
        #
        # Edit a timeline item.
        #
        # Fields you leave out are unchanged, and an empty description removes it. Timestamp can only
        # be changed on a custom item: a promoted one follows the activity it came from.
        #
        # Endpoint: `PATCH /v2/incident_timeline_items/{id}`. Scopes: timeline_items.update.
        #
        # @param id [String] Timeline item to edit.
        # @param description [String] Description of the timeline item, in markdown. Send an empty string to remove it.
        # @param timestamp [Time] When the thing this item describes happened. Only editable on a custom item.
        # @param title [String] Title of the timeline item.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentTimelineItemV2]
        def update(id, description: NOT_GIVEN, timestamp: NOT_GIVEN, title: NOT_GIVEN, request_options: {})
          request(
            :patch,
            path("/v2/incident_timeline_items/%s", id),
            body: given({description:, timestamp:, title:}),
            unwrap: "incident_timeline_item",
            model: Models::IncidentTimelineItemV2,
            request_options:
          )
        end
      end
    end
  end
end
