# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V2
      # View incident timestamps.
      #
      # Each incident has a number of timestamps; some being defaults that we set on
      # each incident for you, and other being configured for your organisation within
      # settings.
      #
      # Timestamps help to communicate when a given action was taken for a specific
      # incident, for example when it was reported, closed or fixed.
      class IncidentTimestamps < Resource
        # List all incident timestamps for an organisation
        #
        # Endpoint: `GET /v2/incident_timestamps`.
        #
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Array<Models::IncidentTimestampV2>]
        def list(request_options: {})
          request(
            :get,
            "/v2/incident_timestamps",
            unwrap: "incident_timestamps",
            model: [Models::IncidentTimestampV2],
            request_options:
          )
        end

        # Get a single incident timestamp
        #
        # Endpoint: `GET /v2/incident_timestamps/{id}`.
        #
        # @param id [String] Unique ID of this incident timestamp.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::IncidentTimestampV2]
        def show(id, request_options: {})
          request(
            :get,
            path("/v2/incident_timestamps/%s", id),
            unwrap: "incident_timestamp",
            model: Models::IncidentTimestampV2,
            request_options:
          )
        end
      end
    end
  end
end
