# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V2
      # Manage the policies that encode how your organisation should handle incidents.
      #
      # A policy scopes itself to a set of resources with conditions, states the requirements
      # those resources must meet, and describes who to chase when they don't.
      #
      # Every policy has a <code>policy_type</code>, which selects exactly one matching
      # configuration block: a <code>follow_up</code> policy carries <code>follow_up</code>
      # config, a <code>schedule</code> policy carries <code>schedule</code> config, and so
      # on. Sending a block that doesn't match the policy type is rejected.
      class Policies < Resource
        # Create a new policy
        #
        # Endpoint: `POST /v2/policies`. Scopes: policies.create.
        #
        # @param conditions [Array<Models::ConditionGroupPayloadV2, Hash>] Conditions which determine which resources are in scope for this policy.
        # @param description [String] Human readable description of the policy.
        # @param name [String] Human readable name of the policy.
        # @param policy_type [String] Type of the policy, specifying what this applies to. Cannot be changed after the policy is created. One of: debrief, follow_up, on_call_readiness, post_mortem, schedule, shift_conflict, vacation_conflict.
        # @param assignment_rules [Models::PolicyAssignmentRulesPayloadV2, Hash]
        # @param debrief [Models::PolicyDebriefPayloadV2, Hash]
        # @param expressions [Array<Models::ExpressionPayloadV2, Hash>] The expressions to use in this policy.
        # @param follow_up [Models::PolicyFollowUpPayloadV2, Hash]
        # @param on_call_readiness [Models::PolicyOnCallReadinessV2, Hash]
        # @param post_mortem [Models::PolicyPostMortemPayloadV2, Hash]
        # @param schedule [Models::PolicyScheduleV2, Hash]
        # @param status [String] Defaults to enabled on create. Settable on update — there is no separate disable endpoint. One of: enabled, disabled.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::PolicyV2]
        def create(
          conditions:,
          description:,
          name:,
          policy_type:,
          assignment_rules: NOT_GIVEN,
          debrief: NOT_GIVEN,
          expressions: NOT_GIVEN,
          follow_up: NOT_GIVEN,
          on_call_readiness: NOT_GIVEN,
          post_mortem: NOT_GIVEN,
          schedule: NOT_GIVEN,
          status: NOT_GIVEN,
          request_options: {}
        )
          request(
            :post,
            "/v2/policies",
            body: given({
              assignment_rules:,
              conditions:,
              debrief:,
              description:,
              expressions:,
              follow_up:,
              name:,
              on_call_readiness:,
              policy_type:,
              post_mortem:,
              schedule:,
              status:
            }),
            unwrap: "policy",
            model: Models::PolicyV2,
            request_options:
          )
        end

        # Archive a policy
        #
        # Archive a policy. Archived policies stop evaluating and no longer appear in the API.
        #
        # Endpoint: `DELETE /v2/policies/{id}`. Scopes: policies.destroy.
        #
        # @param id [String] Unique identifier for the policy.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def delete(id, request_options: {})
          request(
            :delete,
            path("/v2/policies/%s", id),
            request_options:
          )
        end

        # List all policies for an organisation
        #
        # Endpoint: `GET /v2/policies`. Scopes: policies.view.
        #
        # @param page_size [Integer] Number of policies to return per page.
        # @param after [String] The ID of the last policy on the previous page.
        # @param policy_type [String] Filter to policies of this type One of: debrief, follow_up, on_call_readiness, post_mortem, schedule, shift_conflict, vacation_conflict.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::PolicyV2>]
        def list(page_size: nil, after: nil, policy_type: nil, request_options: {})
          paginate(
            "/v2/policies",
            items_key: "policies",
            query: {page_size:, after:, policy_type:},
            model: Models::PolicyV2,
            request_options:
          )
        end

        # Get a single policy
        #
        # Endpoint: `GET /v2/policies/{id}`. Scopes: policies.view.
        #
        # @param id [String] Unique identifier for the policy.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::PolicyV2]
        def show(id, request_options: {})
          request(
            :get,
            path("/v2/policies/%s", id),
            unwrap: "policy",
            model: Models::PolicyV2,
            request_options:
          )
        end

        # Update an existing policy
        #
        # Update an existing policy.
        #
        # The <code>policy_type</code> of an existing policy cannot be changed: sending a
        # different type is rejected. Create a new policy instead.
        #
        # Endpoint: `PUT /v2/policies/{id}`. Scopes: policies.create.
        #
        # @param id [String] Unique identifier for the policy.
        # @param conditions [Array<Models::ConditionGroupPayloadV2, Hash>] Conditions which determine which resources are in scope for this policy.
        # @param description [String] Human readable description of the policy.
        # @param name [String] Human readable name of the policy.
        # @param policy_type [String] Type of the policy, specifying what this applies to. Cannot be changed after the policy is created. One of: debrief, follow_up, on_call_readiness, post_mortem, schedule, shift_conflict, vacation_conflict.
        # @param assignment_rules [Models::PolicyAssignmentRulesPayloadV2, Hash]
        # @param debrief [Models::PolicyDebriefPayloadV2, Hash]
        # @param expressions [Array<Models::ExpressionPayloadV2, Hash>] The expressions to use in this policy.
        # @param follow_up [Models::PolicyFollowUpPayloadV2, Hash]
        # @param on_call_readiness [Models::PolicyOnCallReadinessV2, Hash]
        # @param post_mortem [Models::PolicyPostMortemPayloadV2, Hash]
        # @param schedule [Models::PolicyScheduleV2, Hash]
        # @param status [String] Defaults to enabled on create. Settable on update — there is no separate disable endpoint. One of: enabled, disabled.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::PolicyV2]
        def update(
          id,
          conditions:,
          description:,
          name:,
          policy_type:,
          assignment_rules: NOT_GIVEN,
          debrief: NOT_GIVEN,
          expressions: NOT_GIVEN,
          follow_up: NOT_GIVEN,
          on_call_readiness: NOT_GIVEN,
          post_mortem: NOT_GIVEN,
          schedule: NOT_GIVEN,
          status: NOT_GIVEN,
          request_options: {}
        )
          request(
            :put,
            path("/v2/policies/%s", id),
            body: given({
              assignment_rules:,
              conditions:,
              debrief:,
              description:,
              expressions:,
              follow_up:,
              name:,
              on_call_readiness:,
              policy_type:,
              post_mortem:,
              schedule:,
              status:
            }),
            unwrap: "policy",
            model: Models::PolicyV2,
            request_options:
          )
        end
      end
    end
  end
end
