# frozen_string_literal: true

# This file is generated by `rake generate` from openapi/openapi.json.
# Do not edit it by hand.

module IncidentIo
  module Resources
    module V2
      # Manage and publish to status pages.
      #
      # Before using these endpoints, you must create a status page in the incident.io dashboard (find Status Pages in the left navigation bar). You can then use the ListStatusPages endpoint to find your status page IDs, and the ShowStatusPageStructure endpoint to find component IDs and group IDs for your status page.
      #
      # For read-only access (listing status pages, viewing structure, incidents, maintenance windows, and component availability), any valid API key will work. For write requests (creating incidents, maintenance windows, and publishing updates), you will need an API key with the "Create status page incidents, status page maintenance windows, and publish status page updates" scope.
      class StatusPages < Resource
        # Create a status page incident.
        #
        # This endpoint requires an API key with the "Create status page incidents, status page maintenance windows, and publish status page updates" scope.
        #
        # Endpoint: `POST /v2/status_page_incidents`. Scopes: status_pages.publish_updates.
        #
        # @param incident_status [String] Current status for this status page incident One of: investigating, identified, monitoring, resolved.
        # @param message [String] Markdown initial update on this status page incident.
        # @param name [String] A title for the incident.
        # @param notify_subscribers [Boolean] Whether to notify subscribers about this status page incident. This will not work if your status page has more than 1000 subscribers.
        # @param status_page_id [String] ID of the status page. You can find this by calling the ListStatusPages endpoint.
        # @param component_statuses [Array<Models::StatusPageIncidentAffectedComponentV2, Hash>] An array of mappings from component ID to current component status.
        # @param idempotency_key [String] A unique key to de-duplicate requests. If you send a request with an idempotency_key that was already used, the original response will be returned. Generated when not given.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageIncidentV2]
        def create_status_page_incident(
          incident_status:,
          message:,
          name:,
          notify_subscribers:,
          status_page_id:,
          component_statuses: NOT_GIVEN,
          idempotency_key: SecureRandom.uuid,
          request_options: {}
        )
          request(
            :post,
            "/v2/status_page_incidents",
            body: given({
              component_statuses:,
              idempotency_key:,
              incident_status:,
              message:,
              name:,
              notify_subscribers:,
              status_page_id:
            }),
            idempotent: true,
            unwrap: "status_page_incident",
            model: Models::StatusPageIncidentV2,
            request_options:
          )
        end

        # Post an update on a Status Page incident.
        #
        # This is the endpoint to use when resolving an incident - set incident_status to "resolved" to end the incident. There is a limit of 100 updates per incident.
        #
        # This endpoint requires an API key with the "Create status page incidents, status page maintenance windows, and publish status page updates" scope.
        #
        # Endpoint: `POST /v2/status_page_incident_updates`. Scopes: status_pages.publish_updates.
        #
        # @param message [String] Markdown update on what's changed about this status page incident.
        # @param notify_subscribers [Boolean] Whether to notify subscribers about this incident update. This will not work if your status page has more than 1000 subscribers.
        # @param status_page_incident_id [String] ID of the status page incident.
        # @param component_statuses [Array<Models::StatusPageIncidentAffectedComponentV2, Hash>] An array of mappings from component ID to component status. This must not be set if the status page incident status is being set to "resolved", as all components statuses will update to "operational".
        # @param incident_status [String] Optional new status for this status page incident. If not provided, the status will remain unchanged. Setting to "resolved" will end the incident and all component statuses will update to "operational". One of: investigating, identified, monitoring, resolved.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageIncidentUpdateV2]
        def create_status_page_incident_update(
          message:,
          notify_subscribers:,
          status_page_incident_id:,
          component_statuses: NOT_GIVEN,
          incident_status: NOT_GIVEN,
          request_options: {}
        )
          request(
            :post,
            "/v2/status_page_incident_updates",
            body: given({
              component_statuses:,
              incident_status:,
              message:,
              notify_subscribers:,
              status_page_incident_id:
            }),
            unwrap: "status_page_incident_update",
            model: Models::StatusPageIncidentUpdateV2,
            request_options:
          )
        end

        # Schedule a Status Page maintenance window.
        #
        # This endpoint requires an API key with the "Create status page incidents, status page maintenance windows, and publish status page updates" scope.
        #
        # Endpoint: `POST /v2/status_page_maintenances`. Scopes: status_pages.publish_updates.
        #
        # @param affected_component_ids [Array<String>] An array of IDs of component affected by the maintenance window.
        # @param end_at [Time] The time the maintenance window ends.
        # @param maintenance_status [String] Current status for this status page maintenance window One of: maintenance_scheduled, maintenance_in_progress, maintenance_complete.
        # @param message [String] Markdown initial update on this status page maintenance window.
        # @param name [String] A title for the maintenance window.
        # @param notify_subscribers [Boolean] Whether to notify subscribers about this status page maintenance. This will not work if your status page has more than 1000 subscribers.
        # @param start_at [Time] The time the maintenance window starts.
        # @param status_page_id [String] ID of the status page. You can find this by calling the ListStatusPages endpoint.
        # @param automate_maintenance_status [Boolean] Whether to publish updates automatically, moving this maintenance window to in progress at start_at and to complete at end_at. Defaults to false, which means you publish those updates yourself. When notify_subscribers is true, the automated updates notify subscribers too. Publishing your own update that sets maintenance_status turns automation off.
        # @param idempotency_key [String] A unique key to de-duplicate requests. If you send a request with an idempotency_key that was already used, the original response will be returned. Generated when not given.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageMaintenanceV2]
        def create_status_page_maintenance(
          affected_component_ids:,
          end_at:,
          maintenance_status:,
          message:,
          name:,
          notify_subscribers:,
          start_at:,
          status_page_id:,
          automate_maintenance_status: NOT_GIVEN,
          idempotency_key: SecureRandom.uuid,
          request_options: {}
        )
          request(
            :post,
            "/v2/status_page_maintenances",
            body: given({
              affected_component_ids:,
              automate_maintenance_status:,
              end_at:,
              idempotency_key:,
              maintenance_status:,
              message:,
              name:,
              notify_subscribers:,
              start_at:,
              status_page_id:
            }),
            idempotent: true,
            unwrap: "status_page_maintenance",
            model: Models::StatusPageMaintenanceV2,
            request_options:
          )
        end

        # Post an update on a Status Page maintenance window.
        #
        # This is the endpoint to use when completing a maintenance window - set maintenance_status to "maintenance_complete" to end the maintenance. There is a limit of 100 updates per maintenance window.
        #
        # This endpoint requires an API key with the "Create status page incidents, status page maintenance windows, and publish status page updates" scope.
        #
        # Endpoint: `POST /v2/status_page_maintenance_updates`. Scopes: status_pages.publish_updates.
        #
        # @param message [String] Markdown update on what's changed about this status page maintenance window.
        # @param notify_subscribers [Boolean] Whether to notify subscribers about this status page maintenance update. This will not work if your status page has more than 1000 subscribers.
        # @param status_page_maintenance_id [String] ID of the status page maintenance window.
        # @param component_statuses [Array<Models::StatusPageMaintenanceAffectedComponentV2, Hash>] An array of mappings from component ID to component status. This must not be set if the status page maintenance window status is being set to "maintenance_complete", as all components statuses will update to "operational".
        # @param maintenance_status [String] Optional new status for this status page maintenance window. If not provided, the status will remain unchanged. Setting to "maintenance_complete" will end the maintenance window and all component statuses will update to "operational". One of: maintenance_scheduled, maintenance_in_progress, maintenance_complete.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageMaintenanceUpdateV2]
        def create_status_page_maintenance_update(
          message:,
          notify_subscribers:,
          status_page_maintenance_id:,
          component_statuses: NOT_GIVEN,
          maintenance_status: NOT_GIVEN,
          request_options: {}
        )
          request(
            :post,
            "/v2/status_page_maintenance_updates",
            body: given({
              component_statuses:,
              maintenance_status:,
              message:,
              notify_subscribers:,
              status_page_maintenance_id:
            }),
            unwrap: "status_page_maintenance_update",
            model: Models::StatusPageMaintenanceUpdateV2,
            request_options:
          )
        end

        # Create a retrospective (historical) status page incident.
        #
        # Use this to backfill a completed incident with a reconstructed timeline of past updates, for example when migrating from another status page provider. Every update's published_at must be in the past, the updates must be ordered chronologically (earliest first), and the final update must set incident_status to "resolved".
        #
        # Retrospective incidents never notify subscribers.
        #
        # As this endpoint is intended for bulk historical backfill, it has a dedicated rate limit of 5 requests per second (with a burst allowance of 300 requests) per API key. If you exceed it you'll receive a 429 response with a Retry-After header; back off and retry to resume your backfill.
        #
        # This endpoint requires an API key with the "Create status page incidents, status page maintenance windows, and publish status page updates" scope.
        #
        # Endpoint: `POST /v2/status_page_retrospective_incidents`. Scopes: status_pages.publish_updates.
        #
        # @param name [String] A title for the incident.
        # @param status_page_id [String] ID of the status page. You can find this by calling the ListStatusPages endpoint.
        # @param updates [Array<Models::StatusPageRetrospectiveIncidentUpdateV2, Hash>] The reconstructed timeline of updates for this incident, ordered chronologically (earliest first). The final update must set incident_status to "resolved".
        # @param idempotency_key [String] A unique key to de-duplicate requests. If you send a request with an idempotency_key that was already used, the original response will be returned. Generated when not given.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageIncidentV2]
        def create_status_page_retrospective_incident(
          name:,
          status_page_id:,
          updates:,
          idempotency_key: SecureRandom.uuid,
          request_options: {}
        )
          request(
            :post,
            "/v2/status_page_retrospective_incidents",
            body: given({idempotency_key:, name:, status_page_id:, updates:}),
            idempotent: true,
            unwrap: "status_page_incident",
            model: Models::StatusPageIncidentV2,
            request_options:
          )
        end

        # Delete a Status Page maintenance window.
        #
        # The maintenance window and its updates stop appearing on your public status page, links to it stop working, and a window that has not yet run publishes no further automated updates. This cannot be undone.
        #
        # Subscribers are not told the window has been deleted, so anyone already emailed about it will have updates for a maintenance window they can no longer find.
        #
        # This endpoint requires an API key with the "Create status page incidents, status page maintenance windows, and publish status page updates" scope.
        #
        # Endpoint: `DELETE /v2/status_page_maintenances/{status_page_maintenance_id}`. Scopes: status_pages.publish_updates.
        #
        # @param status_page_maintenance_id [String] ID of the status page maintenance window.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [nil]
        def delete_status_page_maintenance(status_page_maintenance_id, request_options: {})
          request(
            :delete,
            path("/v2/status_page_maintenances/%s", status_page_maintenance_id),
            request_options:
          )
        end

        # List status page incidents.
        #
        # This endpoint requires a valid API key but no specific scopes.
        #
        # Endpoint: `GET /v2/status_page_incidents`.
        #
        # @param status_page_id [String] ID of the status page. You can find this by calling the ListStatusPages endpoint.
        # @param component_id [String] Filter status page incidents to only those that impacted the specified component. This ID may be found by calling the ShowStatusPageStructure endpoint.
        # @param group_id [String] Filter status page incidents to only those that impacted components in the specified group. This ID may be found by calling the ShowStatusPageStructure endpoint.
        # @param sub_page_id [String] Filter status page incidents to only those that impacted the specified sub-page. This ID may be found by calling the ShowStatusPageStructure endpoint.
        # @param start_at [Time] Filter status page incidents to only those that had impacts during or after this time.
        # @param end_at [Time] Filter status page incidents to only those that had impacts during or before this time.
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::StatusPageIncidentV2>]
        def list_status_page_incidents(
          status_page_id:,
          component_id: nil,
          group_id: nil,
          sub_page_id: nil,
          start_at: nil,
          end_at: nil,
          page_size: nil,
          after: nil,
          request_options: {}
        )
          paginate(
            "/v2/status_page_incidents",
            items_key: "status_page_incidents",
            query: {
              status_page_id:,
              component_id:,
              group_id:,
              sub_page_id:,
              start_at:,
              end_at:,
              page_size:,
              after:
            },
            model: Models::StatusPageIncidentV2,
            request_options:
          )
        end

        # List status page maintenances.
        #
        # This endpoint requires a valid API key but no specific scopes.
        #
        # Endpoint: `GET /v2/status_page_maintenances`.
        #
        # @param status_page_id [String] ID of the status page. You can find this by calling the ListStatusPages endpoint.
        # @param component_id [String] Filter status page maintenance windows to only those that impacted the specified component. This ID may be found by calling the ShowStatusPageStructure endpoint.
        # @param group_id [String] Filter status page maintenance windows to only those that impacted components in the specified group. This ID may be found by calling the ShowStatusPageStructure endpoint.
        # @param sub_page_id [String] Filter status page maintenance windows to only those that impacted the specified sub-page. This ID may be found by calling the ShowStatusPageStructure endpoint.
        # @param start_at [Time] Filter status page maintenance windows to only those that had impacts during or after this time.
        # @param end_at [Time] Filter status page maintenance windows to only those that had impacts during or before this time.
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::StatusPageMaintenanceV2>]
        def list_status_page_maintenances(
          status_page_id:,
          component_id: nil,
          group_id: nil,
          sub_page_id: nil,
          start_at: nil,
          end_at: nil,
          page_size: nil,
          after: nil,
          request_options: {}
        )
          paginate(
            "/v2/status_page_maintenances",
            items_key: "status_page_maintenances",
            query: {
              status_page_id:,
              component_id:,
              group_id:,
              sub_page_id:,
              start_at:,
              end_at:,
              page_size:,
              after:
            },
            model: Models::StatusPageMaintenanceV2,
            request_options:
          )
        end

        # List all status pages for your organisation.
        #
        # This endpoint requires a valid API key but no specific scopes. Use this to find status page IDs for use in other endpoints.
        #
        # Endpoint: `GET /v2/status_pages`.
        #
        # @param page_size [Integer] Integer number of records to return.
        # @param after [String] An record's ID. This endpoint will return a list of records after this ID in relation to the API response order.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [IncidentIo::Pager<Models::StatusPageV2>]
        def list_status_pages(page_size: nil, after: nil, request_options: {})
          paginate(
            "/v2/status_pages",
            items_key: "status_pages",
            query: {page_size:, after:},
            model: Models::StatusPageV2,
            request_options:
          )
        end

        # Show availability for a status page component over a time window.
        #
        # Pass start_at and end_at as RFC3339 timestamps. The window cannot be longer than 366 days. Availability uses the same rules as the public status page: full and partial outages count as downtime, overlapping impacts are merged, and time before we have data for the component is excluded rather than counted as up.
        #
        # This endpoint requires a valid API key but no specific scopes. Use ListStatusPages and ShowStatusPageStructure to find status page and component IDs.
        #
        # Endpoint: `GET /v2/status_pages/{status_page_id}/components/{component_id}/availability`.
        #
        # @param status_page_id [String] ID of the status page. You can find this by calling the ListStatusPages endpoint.
        # @param component_id [String] ID of the component. You can find this by calling the ShowStatusPageStructure endpoint.
        # @param start_at [Time] Start of the availability window.
        # @param end_at [Time] End of the availability window.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageComponentAvailabilityV2]
        def show_status_page_component_availability(
          status_page_id,
          component_id,
          start_at:,
          end_at:,
          request_options: {}
        )
          request(
            :get,
            path("/v2/status_pages/%s/components/%s/availability", status_page_id, component_id),
            query: {start_at:, end_at:},
            unwrap: "availability",
            model: Models::StatusPageComponentAvailabilityV2,
            request_options:
          )
        end

        # Show a status page incident.
        #
        # This endpoint requires a valid API key but no specific scopes.
        #
        # Endpoint: `GET /v2/status_page_incidents/{status_page_incident_id}`.
        #
        # @param status_page_incident_id [String] ID of the status page incident.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageIncidentV2]
        def show_status_page_incident(status_page_incident_id, request_options: {})
          request(
            :get,
            path("/v2/status_page_incidents/%s", status_page_incident_id),
            unwrap: "status_page_incident",
            model: Models::StatusPageIncidentV2,
            request_options:
          )
        end

        # Show a status page maintenance window.
        #
        # This endpoint requires a valid API key but no specific scopes.
        #
        # Endpoint: `GET /v2/status_page_maintenances/{status_page_maintenance_id}`.
        #
        # @param status_page_maintenance_id [String] ID of the status page maintenance window.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageMaintenanceV2]
        def show_status_page_maintenance(status_page_maintenance_id, request_options: {})
          request(
            :get,
            path("/v2/status_page_maintenances/%s", status_page_maintenance_id),
            unwrap: "status_page_maintenance",
            model: Models::StatusPageMaintenanceV2,
            request_options:
          )
        end

        # Show the structure of a status page.
        #
        # This endpoint requires a valid API key but no specific scopes. Returns the components and component groups configured on a status page. Use this to find component IDs when specifying affected components for incidents or maintenance windows.
        #
        # Endpoint: `GET /v2/status_page_structures/{status_page_id}`.
        #
        # @param status_page_id [String] ID of the status page.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageStructureV2]
        def show_status_page_structure(status_page_id, request_options: {})
          request(
            :get,
            path("/v2/status_page_structures/%s", status_page_id),
            unwrap: "current_structure",
            model: Models::StatusPageStructureV2,
            request_options:
          )
        end

        # Update a status page incident.
        #
        # This endpoint requires an API key with the "Create status page incidents, status page maintenance windows, and publish status page updates" scope.
        #
        # Endpoint: `PUT /v2/status_page_incidents/{status_page_incident_id}`. Scopes: status_pages.publish_updates.
        #
        # @param status_page_incident_id [String] ID of the status page incident.
        # @param name [String] A title for the incident.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageIncidentV2]
        def update_status_page_incident(status_page_incident_id, name:, request_options: {})
          request(
            :put,
            path("/v2/status_page_incidents/%s", status_page_incident_id),
            body: given({name:}),
            unwrap: "status_page_incident",
            model: Models::StatusPageIncidentV2,
            request_options:
          )
        end

        # Update the name and scheduled window of a Status Page maintenance window.
        #
        # The new start_at and end_at apply to every component this maintenance window affects.
        #
        # This does not publish an update to your status page and does not notify subscribers. Automated updates only move a window forwards, so one that has already started or completed will not move back to an earlier status. To move a status backwards, or to tell subscribers the schedule has changed, post a maintenance update to POST /status_page_maintenance_updates.
        #
        # This endpoint requires an API key with the "Create status page incidents, status page maintenance windows, and publish status page updates" scope.
        #
        # Endpoint: `PUT /v2/status_page_maintenances/{status_page_maintenance_id}`. Scopes: status_pages.publish_updates.
        #
        # @param status_page_maintenance_id [String] ID of the status page maintenance window.
        # @param end_at [Time] The time the maintenance window ends.
        # @param name [String] A title for the maintenance window.
        # @param start_at [Time] The time the maintenance window starts.
        # @param request_options [Hash] Per-call options, see IncidentIo::Client#request.
        # @return [Models::StatusPageMaintenanceV2]
        def update_status_page_maintenance(
          status_page_maintenance_id,
          end_at:,
          name:,
          start_at:,
          request_options: {}
        )
          request(
            :put,
            path("/v2/status_page_maintenances/%s", status_page_maintenance_id),
            body: given({end_at:, name:, start_at:}),
            unwrap: "status_page_maintenance",
            model: Models::StatusPageMaintenanceV2,
            request_options:
          )
        end
      end
    end
  end
end
